/-
  R3Cert.BGSpiderCand -- GENERATED by proof/verification/bg_spider_cand_certs.py; do not edit.

  **`candProp_492 : CandProp 492`** (spider certificate, part L2, 2026-09-25): inside the bounded candidate
  set `Cand` (<= 8 cherries, arms of 4/5/6 only, never both 4- and 6-arms, <= 10 of each), the rule winner
  `W n` maximizes `F` at every size `n >= 492`.

  A candidate is fixed by its counts (C, k4, k5, k6); `F_eq_Φ` gives `F` in closed form `Φ` from the counts.
  The 189 combos (C, k4, k6) are dispatched to `combo_C_k4_k6` (files `BGSpiderCandCells{C}`), each of which
  reads off the residue class and the rule winner and applies a quadratic certificate: 223 certificates
  (221 with nonnegative coefficients in t = m - L on [L, oo), 2 Bernstein on a bounded range).
  Exact rational arithmetic; no `sorry`, no `native_decide`; axioms propext, Classical.choice, Quot.sound.
-/
import Mathlib
import R3Cert.BGSpiderCandCells0
import R3Cert.BGSpiderCandCells1
import R3Cert.BGSpiderCandCells2
import R3Cert.BGSpiderCandCells3
import R3Cert.BGSpiderCandCells4
import R3Cert.BGSpiderCandCells5
import R3Cert.BGSpiderCandCells6
import R3Cert.BGSpiderCandCells7
import R3Cert.BGSpiderCandCells8

namespace R3Cert
namespace BGSpiderCand

open BGSpiderOpt BGSpiderRule

/-- The count-level statement: every combo loses to (or equals) the rule winner. -/
theorem cand_counts (c a b d : ℕ) (hc : c ≤ 8) (ha : a ≤ 10) (hd : d ≤ 10) (had : a = 0 ∨ d = 0)
    (hn : 492 ≤ 1 + 2 * c + 9 * a + 11 * b + 13 * d) :
    Φ c a b d ≤ Φ 0 (w4 (1 + 2 * c + 9 * a + 11 * b + 13 * d)) (w5 (1 + 2 * c + 9 * a + 11 * b + 13 * d)) (w6 (1 + 2 * c + 9 * a + 11 * b + 13 * d)) := by
  rcases had with rfl | rfl
  · interval_cases c
    · interval_cases d
      · exact combo_0_0_0 b hn
      · exact combo_0_0_1 b hn
      · exact combo_0_0_2 b hn
      · exact combo_0_0_3 b hn
      · exact combo_0_0_4 b hn
      · exact combo_0_0_5 b hn
      · exact combo_0_0_6 b hn
      · exact combo_0_0_7 b hn
      · exact combo_0_0_8 b hn
      · exact combo_0_0_9 b hn
      · exact combo_0_0_10 b hn
    · interval_cases d
      · exact combo_1_0_0 b hn
      · exact combo_1_0_1 b hn
      · exact combo_1_0_2 b hn
      · exact combo_1_0_3 b hn
      · exact combo_1_0_4 b hn
      · exact combo_1_0_5 b hn
      · exact combo_1_0_6 b hn
      · exact combo_1_0_7 b hn
      · exact combo_1_0_8 b hn
      · exact combo_1_0_9 b hn
      · exact combo_1_0_10 b hn
    · interval_cases d
      · exact combo_2_0_0 b hn
      · exact combo_2_0_1 b hn
      · exact combo_2_0_2 b hn
      · exact combo_2_0_3 b hn
      · exact combo_2_0_4 b hn
      · exact combo_2_0_5 b hn
      · exact combo_2_0_6 b hn
      · exact combo_2_0_7 b hn
      · exact combo_2_0_8 b hn
      · exact combo_2_0_9 b hn
      · exact combo_2_0_10 b hn
    · interval_cases d
      · exact combo_3_0_0 b hn
      · exact combo_3_0_1 b hn
      · exact combo_3_0_2 b hn
      · exact combo_3_0_3 b hn
      · exact combo_3_0_4 b hn
      · exact combo_3_0_5 b hn
      · exact combo_3_0_6 b hn
      · exact combo_3_0_7 b hn
      · exact combo_3_0_8 b hn
      · exact combo_3_0_9 b hn
      · exact combo_3_0_10 b hn
    · interval_cases d
      · exact combo_4_0_0 b hn
      · exact combo_4_0_1 b hn
      · exact combo_4_0_2 b hn
      · exact combo_4_0_3 b hn
      · exact combo_4_0_4 b hn
      · exact combo_4_0_5 b hn
      · exact combo_4_0_6 b hn
      · exact combo_4_0_7 b hn
      · exact combo_4_0_8 b hn
      · exact combo_4_0_9 b hn
      · exact combo_4_0_10 b hn
    · interval_cases d
      · exact combo_5_0_0 b hn
      · exact combo_5_0_1 b hn
      · exact combo_5_0_2 b hn
      · exact combo_5_0_3 b hn
      · exact combo_5_0_4 b hn
      · exact combo_5_0_5 b hn
      · exact combo_5_0_6 b hn
      · exact combo_5_0_7 b hn
      · exact combo_5_0_8 b hn
      · exact combo_5_0_9 b hn
      · exact combo_5_0_10 b hn
    · interval_cases d
      · exact combo_6_0_0 b hn
      · exact combo_6_0_1 b hn
      · exact combo_6_0_2 b hn
      · exact combo_6_0_3 b hn
      · exact combo_6_0_4 b hn
      · exact combo_6_0_5 b hn
      · exact combo_6_0_6 b hn
      · exact combo_6_0_7 b hn
      · exact combo_6_0_8 b hn
      · exact combo_6_0_9 b hn
      · exact combo_6_0_10 b hn
    · interval_cases d
      · exact combo_7_0_0 b hn
      · exact combo_7_0_1 b hn
      · exact combo_7_0_2 b hn
      · exact combo_7_0_3 b hn
      · exact combo_7_0_4 b hn
      · exact combo_7_0_5 b hn
      · exact combo_7_0_6 b hn
      · exact combo_7_0_7 b hn
      · exact combo_7_0_8 b hn
      · exact combo_7_0_9 b hn
      · exact combo_7_0_10 b hn
    · interval_cases d
      · exact combo_8_0_0 b hn
      · exact combo_8_0_1 b hn
      · exact combo_8_0_2 b hn
      · exact combo_8_0_3 b hn
      · exact combo_8_0_4 b hn
      · exact combo_8_0_5 b hn
      · exact combo_8_0_6 b hn
      · exact combo_8_0_7 b hn
      · exact combo_8_0_8 b hn
      · exact combo_8_0_9 b hn
      · exact combo_8_0_10 b hn
  · interval_cases c
    · interval_cases a
      · exact combo_0_0_0 b hn
      · exact combo_0_1_0 b hn
      · exact combo_0_2_0 b hn
      · exact combo_0_3_0 b hn
      · exact combo_0_4_0 b hn
      · exact combo_0_5_0 b hn
      · exact combo_0_6_0 b hn
      · exact combo_0_7_0 b hn
      · exact combo_0_8_0 b hn
      · exact combo_0_9_0 b hn
      · exact combo_0_10_0 b hn
    · interval_cases a
      · exact combo_1_0_0 b hn
      · exact combo_1_1_0 b hn
      · exact combo_1_2_0 b hn
      · exact combo_1_3_0 b hn
      · exact combo_1_4_0 b hn
      · exact combo_1_5_0 b hn
      · exact combo_1_6_0 b hn
      · exact combo_1_7_0 b hn
      · exact combo_1_8_0 b hn
      · exact combo_1_9_0 b hn
      · exact combo_1_10_0 b hn
    · interval_cases a
      · exact combo_2_0_0 b hn
      · exact combo_2_1_0 b hn
      · exact combo_2_2_0 b hn
      · exact combo_2_3_0 b hn
      · exact combo_2_4_0 b hn
      · exact combo_2_5_0 b hn
      · exact combo_2_6_0 b hn
      · exact combo_2_7_0 b hn
      · exact combo_2_8_0 b hn
      · exact combo_2_9_0 b hn
      · exact combo_2_10_0 b hn
    · interval_cases a
      · exact combo_3_0_0 b hn
      · exact combo_3_1_0 b hn
      · exact combo_3_2_0 b hn
      · exact combo_3_3_0 b hn
      · exact combo_3_4_0 b hn
      · exact combo_3_5_0 b hn
      · exact combo_3_6_0 b hn
      · exact combo_3_7_0 b hn
      · exact combo_3_8_0 b hn
      · exact combo_3_9_0 b hn
      · exact combo_3_10_0 b hn
    · interval_cases a
      · exact combo_4_0_0 b hn
      · exact combo_4_1_0 b hn
      · exact combo_4_2_0 b hn
      · exact combo_4_3_0 b hn
      · exact combo_4_4_0 b hn
      · exact combo_4_5_0 b hn
      · exact combo_4_6_0 b hn
      · exact combo_4_7_0 b hn
      · exact combo_4_8_0 b hn
      · exact combo_4_9_0 b hn
      · exact combo_4_10_0 b hn
    · interval_cases a
      · exact combo_5_0_0 b hn
      · exact combo_5_1_0 b hn
      · exact combo_5_2_0 b hn
      · exact combo_5_3_0 b hn
      · exact combo_5_4_0 b hn
      · exact combo_5_5_0 b hn
      · exact combo_5_6_0 b hn
      · exact combo_5_7_0 b hn
      · exact combo_5_8_0 b hn
      · exact combo_5_9_0 b hn
      · exact combo_5_10_0 b hn
    · interval_cases a
      · exact combo_6_0_0 b hn
      · exact combo_6_1_0 b hn
      · exact combo_6_2_0 b hn
      · exact combo_6_3_0 b hn
      · exact combo_6_4_0 b hn
      · exact combo_6_5_0 b hn
      · exact combo_6_6_0 b hn
      · exact combo_6_7_0 b hn
      · exact combo_6_8_0 b hn
      · exact combo_6_9_0 b hn
      · exact combo_6_10_0 b hn
    · interval_cases a
      · exact combo_7_0_0 b hn
      · exact combo_7_1_0 b hn
      · exact combo_7_2_0 b hn
      · exact combo_7_3_0 b hn
      · exact combo_7_4_0 b hn
      · exact combo_7_5_0 b hn
      · exact combo_7_6_0 b hn
      · exact combo_7_7_0 b hn
      · exact combo_7_8_0 b hn
      · exact combo_7_9_0 b hn
      · exact combo_7_10_0 b hn
    · interval_cases a
      · exact combo_8_0_0 b hn
      · exact combo_8_1_0 b hn
      · exact combo_8_2_0 b hn
      · exact combo_8_3_0 b hn
      · exact combo_8_4_0 b hn
      · exact combo_8_5_0 b hn
      · exact combo_8_6_0 b hn
      · exact combo_8_7_0 b hn
      · exact combo_8_8_0 b hn
      · exact combo_8_9_0 b hn
      · exact combo_8_10_0 b hn

/-- **`CandProp 492`.**  Inside `Cand`, the rule winner `W n` is optimal at every size `n ≥ 492`. -/
theorem candProp_492 : CandProp 492 := by
  intro l hl hcand
  obtain ⟨hC, hmem, h46, ha, hd⟩ := hcand
  have hadm : Adm l := hmem
  have had : c4 l = 0 ∨ c6 l = 0 := by
    rcases Nat.eq_zero_or_pos (c4 l) with h | h
    · exact Or.inl h
    · refine Or.inr (Nat.eq_zero_of_not_pos fun h' => h46 ?_)
      exact ⟨List.count_pos_iff.mp h, List.count_pos_iff.mp h'⟩
  have hnv := nv_eq l hadm
  rw [F_eq_Φ l hadm, F_W_eq, hnv]
  rw [hnv] at hl
  exact cand_counts _ _ _ _ hC ha hd had hl

end BGSpiderCand
end R3Cert
