/-
  R3Cert.BGSpiderCandCells1 -- GENERATED by proof/verification/bg_spider_cand_certs.py; do not edit.

  Per-combo certificates for `CandProp 492` with 1 cherries at the centre: for each (k4, k6) the
  comparison `Φ C k4 k5 k6 ≤ F (W n)` for every n >= 492 in the combo's residue class.
-/
import Mathlib
import R3Cert.BGSpiderCandBase

namespace R3Cert
namespace BGSpiderCand

open BGSpiderOpt BGSpiderRule

theorem cert_1_0_0_0 (m : ℕ) (hm : 44 ≤ m) :
    Φ 1 0 (m + 1) 0 ≤ Φ 0 0 (m + 0) 1 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 0 1 0 1 0 (44 + t) =
      (29403 / 448 : ℚ) + (31239 / 5152 : ℚ) * t + (1053 / 10304 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (44 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 44)
  rw [show (44 : ℚ) + ((m : ℚ) - 44) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 0) :
    Φ 1 0 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 0) = 1 := by unfold sres; omega
  have hw := w_six _ 1 hs (by omega) (by omega) (by omega)
  obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
  have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 0) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 0) = 1 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_0_0_0 m (by omega)

theorem cert_1_1_0_0 (m : ℕ) (hm : 44 ≤ m) :
    Φ 1 1 (m + 0) 0 ≤ Φ 0 0 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 1 0 0 0 0 1 (44 + t) =
      (8991 / 92 : ℚ) + (23787 / 3680 : ℚ) * t + (351 / 3680 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (44 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 44)
  rw [show (44 : ℚ) + ((m : ℚ) - 44) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_1_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 1 + 11 * b + 13 * 0) :
    Φ 1 1 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 1 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 1 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 1 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 1 + 11 * b + 13 * 0) = 0 := by unfold sres; omega
  have hw := w_zero _ hs
  have h4 : w4 (1 + 2 * 1 + 9 * 1 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 1 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 1 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_1_0_0 b (by omega)

theorem cert_1_2_0_0 (m : ℕ) (hm : 43 ≤ m) :
    Φ 1 2 (m + 0) 0 ≤ Φ 0 1 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 2 0 0 1 0 1 (43 + t) =
      (4629879 / 7360 : ℚ) + (2441421 / 58880 : ℚ) * t + (180063 / 294400 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (43 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 43)
  rw [show (43 : ℚ) + ((m : ℚ) - 43) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_2_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 2 + 11 * b + 13 * 0) :
    Φ 1 2 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 2 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 2 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 2 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 2 + 11 * b + 13 * 0) = 10 := by unfold sres; omega
  have hw := w_four _ 10 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 2 + 11 * b + 13 * 0) = 1 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 2 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 2 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_2_0_0 b (by omega)

theorem cert_1_3_0_0 (m : ℕ) (hm : 42 ≤ m) :
    Φ 1 3 (m + 0) 0 ≤ Φ 0 2 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 3 0 0 2 0 1 (42 + t) =
      (95364135 / 23552 : ℚ) + (6264488727 / 23552000 : ℚ) * t + (92372319 / 23552000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (42 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 42)
  rw [show (42 : ℚ) + ((m : ℚ) - 42) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_3_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 3 + 11 * b + 13 * 0) :
    Φ 1 3 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 3 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 3 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 3 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 3 + 11 * b + 13 * 0) = 9 := by unfold sres; omega
  have hw := w_four _ 9 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 3 + 11 * b + 13 * 0) = 2 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 3 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 3 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_3_0_0 b (by omega)

theorem cert_1_4_0_0 (m : ℕ) (hm : 42 ≤ m) :
    Φ 1 4 (m + 0) 0 ≤ Φ 0 3 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 4 0 0 3 0 1 (42 + t) =
      (569219546367 / 20480000 : ℚ) + (3309607817451 / 1884160000 : ℚ) * t + (47386999647 / 1884160000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (42 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 42)
  rw [show (42 : ℚ) + ((m : ℚ) - 42) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_4_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 4 + 11 * b + 13 * 0) :
    Φ 1 4 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 4 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 4 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 4 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 4 + 11 * b + 13 * 0) = 8 := by unfold sres; omega
  have hw := w_four _ 8 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 4 + 11 * b + 13 * 0) = 3 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 4 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 4 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_4_0_0 b (by omega)

theorem cert_1_5_0_0 (m : ℕ) (hm : 41 ≤ m) :
    Φ 1 5 (m + 0) 0 ≤ Φ 0 4 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 5 0 0 4 0 1 (41 + t) =
      (117217211357583 / 655360000 : ℚ) + (1698419325271041 / 150732800000 : ℚ) * t + (24309530818911 / 150732800000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (41 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 41)
  rw [show (41 : ℚ) + ((m : ℚ) - 41) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_5_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 5 + 11 * b + 13 * 0) :
    Φ 1 5 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 5 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 5 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 5 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 5 + 11 * b + 13 * 0) = 7 := by unfold sres; omega
  have hw := w_four _ 7 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 5 + 11 * b + 13 * 0) = 4 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 5 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 5 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_5_0_0 b (by omega)

theorem cert_1_6_0_0 (m : ℕ) (hm : 40 ≤ m) :
    Φ 1 6 (m + 0) 0 ≤ Φ 0 5 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 6 0 0 5 0 1 (40 + t) =
      (37715302083585843 / 32768000000 : ℚ) + (871592048017325847 / 12058624000000 : ℚ) * t + (12470789310101343 / 12058624000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (40 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 40)
  rw [show (40 : ℚ) + ((m : ℚ) - 40) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_6_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 6 + 11 * b + 13 * 0) :
    Φ 1 6 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 6 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 6 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 6 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 6 + 11 * b + 13 * 0) = 6 := by unfold sres; omega
  have hw := w_four _ 6 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 6 + 11 * b + 13 * 0) = 5 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 6 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 6 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_6_0_0 b (by omega)

theorem cert_1_7_0_0 (m : ℕ) (hm : 39 ≤ m) :
    Φ 1 7 (m + 0) 0 ≤ Φ 0 6 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 7 0 0 6 0 1 (39 + t) =
      (155327518023253796709 / 20971520000000 : ℚ) + (447282125853521730093 / 964689920000000 : ℚ) * t + (6397514916081988959 / 964689920000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_7_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 7 + 11 * b + 13 * 0) :
    Φ 1 7 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 7 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 7 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 7 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 7 + 11 * b + 13 * 0) = 5 := by unfold sres; omega
  have hw := w_four _ 5 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 7 + 11 * b + 13 * 0) = 6 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 7 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 7 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_7_0_0 b (by omega)

theorem cert_1_8_0_0 (m : ℕ) (hm : 38 ≤ m) (hmU : m ≤ 204) :
    Φ 1 8 (m + 0) 0 ≤ Φ 0 7 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 8 0 0 7 0 1 (38 + t) =
      (39981023409788386845849 / 838860800000000 : ℚ) + (9181418137641666769851 / 3087007744000000 : ℚ) * t + (3281925151950060335967 / 77175193600000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (38 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 38)
  rw [show (38 : ℚ) + ((m : ℚ) - 38) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_1_8_0_1 (m : ℕ) (hm : 205 ≤ m) :
    Φ 1 8 (m + 0) 0 ≤ Φ 0 0 (m + 2) 4 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 8 0 0 0 4 2 (205 + t) =
      (635380869751391515648787505729 / 370595279667200000000 : ℚ) + (13536749572358520210222035781 / 741190559334400000000 : ℚ) * t + (35595517726082942387717373 / 741190559334400000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (205 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 205)
  rw [show (205 : ℚ) + ((m : ℚ) - 205) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_8_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0) :
    Φ 1 8 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0) = 4 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0) 2320 with hlo | hhi
  · have hw := w_four _ 4 hs (by omega) (by omega)
    have h4 : w4 (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0) = 7 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_1_8_0_0 b (by omega) (by omega)
  · have hw := w_six _ 4 hs (by omega) (by omega) (by omega)
    have h4 : w4 (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0) = 4 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 1 + 9 * 8 + 11 * b + 13 * 0) = b + 2 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_1_8_0_1 b (by omega)

theorem cert_1_9_0_0 (m : ℕ) (hm : 38 ≤ m) (hmU : m ≤ 58) :
    Φ 1 9 (m + 0) 0 ≤ Φ 0 8 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 9 0 0 8 0 1 (38 + t) =
      (1006502572790510938482232773 / 3087007744000000000 : ℚ) + (4846393626306562174581423 / 246960619520000000 : ℚ) * t + (1683627602950380952351071 / 6174015488000000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (38 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 38)
  rw [show (38 : ℚ) + ((m : ℚ) - 38) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_1_9_0_1 (m : ℕ) (hm : 59 ≤ m) :
    Φ 1 9 (m + 0) 0 ≤ Φ 0 0 (m + 4) 3 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 9 0 0 0 3 4 (59 + t) =
      (7099364978541297772082040266793 / 8470749249536000000000 : ℚ) + (260021791321488138635131520853 / 6776599399628800000000 : ℚ) * t + (13141794866255668817313888753 / 33882996998144000000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (59 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 59)
  rw [show (59 : ℚ) + ((m : ℚ) - 59) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_9_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0) :
    Φ 1 9 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0) = 3 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0) 723 with hlo | hhi
  · have hw := w_four _ 3 hs (by omega) (by omega)
    have h4 : w4 (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0) = 8 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_1_9_0_0 b (by omega) (by omega)
  · have hw := w_six _ 3 hs (by omega) (by omega) (by omega)
    have h4 : w4 (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0) = 3 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 1 + 9 * 9 + 11 * b + 13 * 0) = b + 4 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_1_9_0_1 b (by omega)

theorem cert_1_10_0_0 (m : ℕ) (hm : 37 ≤ m) :
    Φ 1 10 (m + 0) 0 ≤ Φ 0 0 (m + 6) 2 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 10 0 0 0 2 6 (37 + t) =
      (45702338944454214874123564465947 / 19361712570368000000000 : ℚ) + (291125034374311107847871144900613 / 1548937005629440000000000 : ℚ) * t + (4648046083487447408629968207933 / 1548937005629440000000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (37 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 37)
  rw [show (37 : ℚ) + ((m : ℚ) - 37) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_10_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 10 + 11 * b + 13 * 0) :
    Φ 1 10 b 0 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 10 + 11 * b + 13 * 0)) (w5 (1 + 2 * 1 + 9 * 10 + 11 * b + 13 * 0)) (w6 (1 + 2 * 1 + 9 * 10 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 1 + 9 * 10 + 11 * b + 13 * 0) = 2 := by unfold sres; omega
  have hw := w_six _ 2 hs (by omega) (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 10 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 10 + 11 * b + 13 * 0) = 2 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 10 + 11 * b + 13 * 0) = b + 6 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_10_0_0 b (by omega)

theorem cert_1_0_1_0 (m : ℕ) (hm : 43 ≤ m) :
    Φ 1 0 (m + 1) 1 ≤ Φ 0 0 (m + 0) 2 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 1 1 0 2 0 (43 + t) =
      (191850201 / 200704 : ℚ) + (102450015 / 1154048 : ℚ) * t + (6908733 / 4616192 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (43 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 43)
  rw [show (43 : ℚ) + ((m : ℚ) - 43) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_1 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 1) :
    Φ 1 0 b 1 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 1)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 1)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 1)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 1) = 2 := by unfold sres; omega
  have hw := w_six _ 2 hs (by omega) (by omega) (by omega)
  obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
  have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 1) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 1) = 2 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 1) = m + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_0_1_0 m (by omega)

theorem cert_1_0_2_0 (m : ℕ) (hm : 39 ≤ m) (hmU : m ≤ 59) :
    Φ 1 0 (m + 4) 2 ≤ Φ 0 8 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 2 4 8 0 0 (39 + t) =
      (32234692834705239807982443 / 1315333734400000000 : ℚ) + (13887033096760903600963389 / 15126337945600000000 : ℚ) * t + (246709979177093295144489 / 30252675891200000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_1_0_2_1 (m : ℕ) (hm : 63 ≤ m) :
    Φ 1 0 (m + 1) 2 ≤ Φ 0 0 (m + 0) 3 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 2 1 0 3 0 (63 + t) =
      (13153313022039 / 258506752 : ℚ) + (1147926908907 / 517013504 : ℚ) * t + (45328197213 / 2068054016 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (63 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 63)
  rw [show (63 : ℚ) + ((m : ℚ) - 63) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_2 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 2) :
    Φ 1 0 b 2 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 2)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 2)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 2)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 2) = 3 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 2) 723 with hlo | hhi
  · have hw := w_four _ 3 hs (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 4 := by exact ⟨b - 4, by omega⟩
    have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * (m + 4) + 13 * 2) = 8 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * (m + 4) + 13 * 2) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * (m + 4) + 13 * 2) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_1_0_2_0 m (by omega) (by omega)
  · have hw := w_six _ 3 hs (by omega) (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
    have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 2) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 2) = 3 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 2) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_1_0_2_1 m (by omega)

theorem cert_1_0_3_0 (m : ℕ) (hm : 39 ≤ m) (hmU : m ≤ 205) :
    Φ 1 0 (m + 2) 3 ≤ Φ 0 7 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 3 2 7 0 0 (39 + t) =
      (25534018038012912814941 / 4136108032000000 : ℚ) + (83805010515315195740199 / 330888642560000000 : ℚ) * t + (1686154364483113944549 / 661777285120000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_1_0_3_1 (m : ℕ) (hm : 207 ≤ m) :
    Φ 1 0 (m + 1) 3 ≤ Φ 0 0 (m + 0) 4 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 3 1 0 4 0 (207 + t) =
      (491721402624416721 / 40282095616 : ℚ) + (4155950629317915 / 33088864256 : ℚ) * t + (297398301914493 / 926488199168 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (207 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 207)
  rw [show (207 : ℚ) + ((m : ℚ) - 207) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_3 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 3) :
    Φ 1 0 b 3 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 3)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 3)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 3)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 3) = 4 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 3) 2320 with hlo | hhi
  · have hw := w_four _ 4 hs (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 2 := by exact ⟨b - 2, by omega⟩
    have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * (m + 2) + 13 * 3) = 7 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * (m + 2) + 13 * 3) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * (m + 2) + 13 * 3) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_1_0_3_0 m (by omega) (by omega)
  · have hw := w_six _ 4 hs (by omega) (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
    have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 3) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 3) = 4 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * (m + 1) + 13 * 3) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_1_0_3_1 m (by omega)

theorem cert_1_0_4_0 (m : ℕ) (hm : 40 ≤ m) :
    Φ 1 0 (m + 0) 4 ≤ Φ 0 6 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 4 0 6 0 0 (40 + t) =
      (69808452534670988259 / 51701350400000 : ℚ) + (412654100472615478293 / 7238189056000000 : ℚ) * t + (8625697493435723259 / 14476378112000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (40 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 40)
  rw [show (40 : ℚ) + ((m : ℚ) - 40) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_4 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 4) :
    Φ 1 0 b 4 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 4)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 4)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 4)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 4) = 5 := by unfold sres; omega
  have hw := w_four _ 5 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 4) = 6 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 4) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 4) = b + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_0_4_0 b (by omega)

theorem cert_1_0_5_0 (m : ℕ) (hm : 39 ≤ m) :
    Φ 1 0 (m + 0) 5 ≤ Φ 0 5 (m + 2) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 5 0 5 0 2 (39 + t) =
      (35943378513158694386619 / 1409873346560000 : ℚ) + (2836525588791907949263323 / 2594166957670400000 : ℚ) * t + (30236652772668545889933 / 2594166957670400000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_5 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 5) :
    Φ 1 0 b 5 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 5)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 5)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 5)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 5) = 6 := by unfold sres; omega
  have hw := w_four _ 6 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 5) = 5 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 5) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 5) = b + 2 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_0_5_0 b (by omega)

theorem cert_1_0_6_0 (m : ℕ) (hm : 38 ≤ m) :
    Φ 1 0 (m + 0) 6 ≤ Φ 0 4 (m + 4) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 6 0 4 0 4 (38 + t) =
      (1848436860891928151767455009 / 4042388859256832000 : ℚ) + (18415440786109498589645266311 / 929749437629071360000 : ℚ) * t + (198695239863521419249171317 / 929749437629071360000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (38 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 38)
  rw [show (38 : ℚ) + ((m : ℚ) - 38) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_6 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 6) :
    Φ 1 0 b 6 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 6)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 6)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 6)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 6) = 7 := by unfold sres; omega
  have hw := w_four _ 7 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 6) = 4 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 6) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 6) = b + 4 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_0_6_0 b (by omega)

theorem cert_1_0_7_0 (m : ℕ) (hm : 37 ≤ m) :
    Φ 1 0 (m + 0) 7 ≤ Φ 0 3 (m + 6) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 7 0 3 0 6 (37 + t) =
      (1148507852756615384388960533283 / 144879216715764858880 : ℚ) + (3291725196766022217221433795273 / 9520634241321690726400 : ℚ) * t + (1253340516374328021242052457683 / 333222198446259175424000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (37 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 37)
  rw [show (37 : ℚ) + ((m : ℚ) - 37) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_7 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 7) :
    Φ 1 0 b 7 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 7)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 7)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 7)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 7) = 8 := by unfold sres; omega
  have hw := w_four _ 8 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 7) = 3 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 7) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 7) = b + 6 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_0_7_0 b (by omega)

theorem cert_1_0_8_0 (m : ℕ) (hm : 35 ≤ m) :
    Φ 1 0 (m + 0) 8 ≤ Φ 0 2 (m + 8) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 8 0 2 0 8 (35 + t) =
      (3831587812856228157020057601467813967 / 29856708980784822117990400 : ℚ) + (137383901134930149086194630826238549 / 23885367184627857694392320 : ℚ) * t + (7685844017502493166820461353697517 / 119426835923139288471961600 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (35 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 35)
  rw [show (35 : ℚ) + ((m : ℚ) - 35) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_8 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 8) :
    Φ 1 0 b 8 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 8)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 8)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 8)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 8) = 9 := by unfold sres; omega
  have hw := w_four _ 9 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 8) = 2 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 8) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 8) = b + 8 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_0_8_0 b (by omega)

theorem cert_1_0_9_0 (m : ℕ) (hm : 34 ≤ m) :
    Φ 1 0 (m + 0) 9 ≤ Φ 0 1 (m + 10) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 9 0 1 0 10 (34 + t) =
      (22817837232493872333669119368768769977959 / 10700644498713280247087759360 : ℚ) + (586723539083313544633124554511925024543 / 6114653999264731569764433920 : ℚ) * t + (46168299795893614734417135607457856243 / 42802577994853120988351037440 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (34 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 34)
  rw [show (34 : ℚ) + ((m : ℚ) - 34) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_9 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 9) :
    Φ 1 0 b 9 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 9)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 9)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 9)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 9) = 10 := by unfold sres; omega
  have hw := w_four _ 10 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 9) = 1 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 9) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 9) = b + 10 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_0_9_0 b (by omega)

theorem cert_1_0_10_0 (m : ℕ) (hm : 33 ≤ m) :
    Φ 1 0 (m + 0) 10 ≤ Φ 0 0 (m + 12) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 1 0 10 0 0 0 12 (33 + t) =
      (133994845079680036541204826147483766757150595 / 3835110988338839640556252954624 : ℚ) + (24195199885933578188414682595097740018257189 / 15340443953355358562225011818496 : ℚ) * t + (272989933110267097438934030710846041379245 / 15340443953355358562225011818496 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (33 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 33)
  rw [show (33 : ℚ) + ((m : ℚ) - 33) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_1_0_10 (b : ℕ) (hn : 492 ≤ 1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 10) :
    Φ 1 0 b 10 ≤ Φ 0 (w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 10)) (w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 10)) (w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 10)) := by
  have hs : sres (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 10) = 0 := by unfold sres; omega
  have hw := w_zero _ hs
  have h4 : w4 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 10) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 10) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 1 + 9 * 0 + 11 * b + 13 * 10) = b + 12 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_1_0_10_0 b (by omega)

end BGSpiderCand
end R3Cert
