#!/usr/bin/env python3
"""Generate the Lean spider-table sweep (BGSpiderTableData, BGSpiderTableChunk_*, BGSpiderTableAll).

Input: bg_spider_table_canon_491.json from bg_spider_table_sweep.py (which re-checks every configuration
exactly).  Each table entry (C, s, a, b) is re-verified here: 1 + 2C + a(2s+1) + b(2s+3) = n.
The kernel re-evaluates every comparison itself (`decide +kernel`); this script only emits data, the
exact table value as a literal (which the kernel checks against `tabV n`), and the split points.

Kernel memory (2026-10-08).  The kernel keeps its whole reduction cache for one declaration, so the cost
of a `decide +kernel` grows with the number of cases it evaluates.  The first version (PR #642) checked
whole ranges of n in one declaration (peak 19.1 GB RSS for n = 490..491).  Now each n is split:
  * `Sweep.tabV_n`   : `tabV n = (N, D)`, the table value as a literal;
  * `Sweep.bal_n_k`  : a block of rows `C` of `checkBal` (`balRow n (N, D)`), at most DECL_CASES cases;
  * `Sweep.small_n`  : `checkSmallFast n (N, D)` (linear in n, replaces the (n+2)^2 pair loop);
  * `Sweep.checkN_n` : `checkN n = true`, glued by `checkN_of_parts` (no kernel evaluation).
Each module `BGSpiderTableChunk_a_b` still proves `chunk_a_b : (List.range' a (b-a+1)).all checkN = true`
(glued from the `Sweep.checkN_n`), so `BGSpiderTableAll` and everything downstream is unchanged.
`set_option Elab.async false` keeps the kernel checks of one module sequential, so a module's peak is
one block, not the sum of blocks.
"""
import json, os
N = 491
DECL_CASES = 12000     # max balanced cases (m values) per kernel declaration
MODULE_CASES = 200000  # target balanced cases per module (~1 min of kernel time)
R3 = os.environ.get('BG_R3OUT') or os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'formalization', 'R3Cert')
tab = json.load(open(os.environ.get('BG_CANON') or os.path.join(os.path.dirname(os.path.abspath(__file__)), 'bg_spider_table_canon_491.json')))
rows, vals = [], {}
for n in range(4, N + 1):
    C, s, a, b = tab[str(n)]
    assert 1 + 2 * C + a * (2 * s + 1) + b * (2 * s + 3) == n and C + a + b > 0, n
    rows.append(f"({C}, {s}, {a}, {b})")
    A, B, D = 4 * s + 3, 4 * s + 7, C + a + b
    vals[n] = (3 ** C * (3 ** s * A) ** a * (3 ** (s + 1) * B) ** b * (D * (3 * A * B) + (C * A * B + 9 * a * B + 9 * b * A)),
               2 ** C * (2 ** s * (3 * (s + 1))) ** a * (2 ** (s + 1) * (3 * (s + 2))) ** b * (D * (3 * A * B)))
data = f'''/-
  R3Cert.BGSpiderTableData -- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
  The table maximizer of the spider family for n = 4..{N} in canonical form (C, s, a, b), the per-n
  kernel check `checkN`, and its soundness `spider_opt_of_checkN`.
-/
import Mathlib
import R3Cert.BGSpiderTable

namespace R3Cert
namespace BGSpiderTable

open BGSpiderOpt

set_option maxRecDepth 100000 in
/-- Table rows for n = 4, 5, ..., {N}. -/
def tabData : List (ℕ × ℕ × ℕ × ℕ) := [{", ".join(rows)}]

def row (n : ℕ) : ℕ × ℕ × ℕ × ℕ := tabData.getD (n - 4) (0, 0, 0, 1)

/-- The table maximizer at size `n`. -/
def tab (n : ℕ) : List Child := canon (row n).1 (row n).2.1 (row n).2.2.1 (row n).2.2.2

/-- Its exact value as a numerator/denominator pair. -/
def tabV (n : ℕ) : ℕ × ℕ :=
  (fnum (row n).1 (row n).2.1 (row n).2.2.1 (row n).2.2.2, fden (row n).1 (row n).2.1 (row n).2.2.1 (row n).2.2.2)

/-- The per-`n` kernel check. -/
def checkN (n : ℕ) : Bool :=
  Nat.beq (1 + 2 * (row n).1 + (row n).2.2.1 * (2 * (row n).2.1 + 1) + (row n).2.2.2 * (2 * (row n).2.1 + 3)) n &&
  Nat.blt 0 ((row n).1 + (row n).2.2.1 + (row n).2.2.2) &&
  checkBal n (tabV n) && checkSmall n (tabV n)

theorem spider_opt_of_checkN (n : ℕ) (hn : 2 ≤ n) (h : checkN n = true) :
    nv (tab n) = n ∧ ∀ l : List Child, nv l = n → F l ≤ F (tab n) := by
  simp only [checkN, Bool.and_eq_true] at h
  obtain ⟨⟨⟨h1, h2⟩, h3⟩, h4⟩ := h
  have hnv : nv (tab n) = n := by
    rw [tab, nv_canon]; exact Nat.eq_of_beq_eq_true h1
  have hpos : 0 < (row n).1 + (row n).2.2.1 + (row n).2.2.2 := Nat.blt_eq.mp h2
  refine ⟨hnv, spider_opt_of_check n hn (tab n) (tabV n) (fden_pos _ _ _ _ hpos) ?_ h3 h4⟩
  rw [tab, F_canon_eq _ _ _ _ hpos]; rfl

theorem checkN_of_all {{lo len : ℕ}} (h : (List.range' lo len).all checkN = true) (n : ℕ)
    (h1 : lo ≤ n) (h2 : n < lo + len) : checkN n = true := by
  rw [List.all_eq_true] at h
  exact h n (List.mem_range'_1.mpr ⟨h1, h2⟩)

/-- `checkN n` from its kernel-cheap pieces (`BGSpiderTableChunk_*`): the table value `T` as a literal,
    the balanced rows `balRow n T C` for all `C`, and the linear small check `checkSmallFast`. -/
theorem checkN_of_parts {{n : ℕ}} {{T : ℕ × ℕ}} (hT : tabV n = T)
    (hrow : (Nat.beq (1 + 2 * (row n).1 + (row n).2.2.1 * (2 * (row n).2.1 + 1) +
      (row n).2.2.2 * (2 * (row n).2.1 + 3)) n && Nat.blt 0 ((row n).1 + (row n).2.2.1 + (row n).2.2.2)) = true)
    {{K : ℕ}} (hK : (n - 1) / 2 + 1 = K) (hb : (List.range' 0 K).all (balRow n T) = true)
    (hs : checkSmallFast n T = true) : checkN n = true := by
  subst hK
  have h1 : checkBal n T = true := (checkBal_eq_balRow n T).trans hb
  have h2 : checkSmall n T = true := checkSmall_of_fast n T hs
  unfold checkN
  rw [hT, hrow, h1, h2]; rfl

end BGSpiderTable
end R3Cert
'''
open(os.path.join(R3, 'BGSpiderTableData.lean'), 'w').write(data)


def cases(n, C):
    """Number of m values in row C of checkBal at size n (the kernel's per-row work)."""
    return n - 1 - 2 * C + 1


def blocks(n):
    """Split rows C = 0..(n-1)//2 into consecutive blocks of at most DECL_CASES cases."""
    out, lo, acc = [], 0, 0
    K = (n - 1) // 2 + 1
    for C in range(K):
        c = cases(n, C)
        if acc and acc + c > DECL_CASES:
            out.append((lo, C - lo)); lo, acc = C, 0
        acc += c
    out.append((lo, K - lo))
    return out


def per_n(n):
    Nn, Dn = vals[n]
    T = f"T{n}"
    K = (n - 1) // 2 + 1
    bl = blocks(n)
    s = [f"/-- The table value at n = {n}. -/",
         f"def {T} : ℕ × ℕ := ({Nn}, {Dn})",
         f"theorem tabV_{n} : tabV {n} = {T} := by decide +kernel"]
    for k, (lo, ln) in enumerate(bl):
        s.append(f"theorem bal_{n}_{k} : (List.range' {lo} {ln}).all (balRow {n} {T}) = true := by decide +kernel")
    s.append(f"theorem small_{n} : checkSmallFast {n} {T} = true := by decide +kernel")
    s.append(f"theorem checkN_{n} : checkN {n} = true := by")
    s.append(f"  have h : (List.range' 0 {bl[0][1]}).all (balRow {n} {T}) = true := bal_{n}_0")
    acc = bl[0][1]
    for k, (lo, ln) in enumerate(bl[1:], 1):
        assert lo == acc
        acc += ln
        s.append(f"  have h : (List.range' 0 {acc}).all (balRow {n} {T}) = true := all_range'_append (by decide) (by decide) h bal_{n}_{k}")
    assert acc == K
    s.append(f"  exact checkN_of_parts tabV_{n} (by decide +kernel) (by decide) h small_{n}")
    return "\n".join(s)


# modules: consecutive ranges of n with about MODULE_CASES balanced cases each
work = {n: sum(cases(n, C) for C in range((n - 1) // 2 + 1)) for n in range(4, N + 1)}
chunks, lo, acc = [], 4, 0
for n in range(4, N + 1):
    acc += work[n]
    if acc >= MODULE_CASES or n == N or (n < N and acc + work[n + 1] > 1.25 * MODULE_CASES):
        chunks.append((lo, n)); lo, acc = n + 1, 0
for f in os.listdir(R3):
    if f.startswith('BGSpiderTableChunk_') and f.endswith('.lean'):
        os.remove(os.path.join(R3, f))
names = []
for (a, b) in chunks:
    nm = f"BGSpiderTableChunk_{a}_{b}"
    names.append((nm, a, b))
    glue = [f"  have h : (List.range' {a} 1).all checkN = true := all_range'_one Sweep.checkN_{a}"]
    for n in range(a + 1, b + 1):
        glue.append(f"  have h : (List.range' {a} {n - a + 1}).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_{n}")
    glue.append("  exact h")
    body = "\n\n".join(per_n(n) for n in range(a, b + 1))
    open(os.path.join(R3, nm + '.lean'), 'w').write(f'''-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for {a} <= n <= {b}, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

{body}

end Sweep

theorem chunk_{a}_{b} : (List.range' {a} {b - a + 1}).all checkN = true := by
{chr(10).join(glue)}

end BGSpiderTable
end R3Cert
''')
# assembly
imports = "\n".join(f"import R3Cert.{nm}" for nm, _, _ in names)
body = []
for i, (nm, a, b) in enumerate(names):
    if i < len(names) - 1:
        body.append(f"  rcases Nat.lt_or_ge n {b + 1} with h{i} | h{i}\n  · exact checkN_of_all chunk_{a}_{b} n (by omega) (by omega)")
    else:
        body.append(f"  exact checkN_of_all chunk_{a}_{b} n (by omega) (by omega)")
open(os.path.join(R3, 'BGSpiderTableAll.lean'), 'w').write(f'''/-
  R3Cert.BGSpiderTableAll -- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
  The spider-family optimum for every 4 <= n <= {N}: the table spider `tab n` has n vertices and
  maximizes F.  {len(names)} kernel-checked chunks.
-/
{imports}

namespace R3Cert
namespace BGSpiderTable

open BGSpiderOpt

theorem checkN_all (n : ℕ) (h4 : 4 ≤ n) (hN : n ≤ {N}) : checkN n = true := by
{chr(10).join(body)}

/-- **The spider-family optimum for every `4 ≤ n ≤ {N}`.** -/
theorem spider_opt_table (n : ℕ) (h4 : 4 ≤ n) (hN : n ≤ {N}) :
    nv (tab n) = n ∧ ∀ l : List Child, nv l = n → F l ≤ F (tab n) :=
  spider_opt_of_checkN n (by omega) (checkN_all n h4 hN)

end BGSpiderTable
end R3Cert
''')
print(f"wrote data, {len(names)} chunks, assembly; max blocks/n = {max(len(blocks(n)) for n in range(4, N + 1))}")
