"""Primality emitter — a Pratt/Lucas certificate discharged through Mathlib's
`lucas_primality`.

For a prime `p` with Lucas witness `a` (order p-1 mod p), the emitted proof is
NON-recursive: `lucas_primality`'s hypothesis `hd` supplies `Nat.Prime q` for
each prime divisor `q` of `p-1` for free, so we only certify

    a^(p-1) = 1   and   ∀ prime q | p-1,  a^((p-1)/q) ≠ 1

the second discharged by enumerating `Nat.primeFactors (p-1)` (`fin_cases`) and
a kernel `decide` per factor.  The witness comes from `pratt.find_pratt_certificate`;
`emit()` refuses to emit unless the exact `verify_pratt_certificate` self-check
passes first — the untrusted generator never hands Lean an unchecked claim.
"""
from __future__ import annotations

from .pratt import find_pratt_certificate, verify_pratt_certificate


def primality_theorem(n: int) -> str:
    """Emit a single `Nat.Prime n` theorem via lucas_primality, or raise if composite.

    Raises ValueError if `n` is composite or the exact self-check fails — a
    defective certificate is refused before it can reach Lean.
    """
    cert = find_pratt_certificate(n)
    if cert is None:
        raise ValueError(f"{n} is composite (no Pratt certificate)")
    if not verify_pratt_certificate(cert):
        raise ValueError(f"{n}: certificate failed the exact self-check")
    a = cert.witness
    # ALL divisors of n-1 as an explicit Finset literal.  We enumerate divisors
    # (not primeFactors): `Nat.divisors` is filter-based and kernel-`decide`-
    # computable, whereas `Nat.primeFactors` routes through `Nat.factorization`
    # (a Finsupp) which does NOT reduce under `decide` (round-2 CI: "decide failed"
    # on the primeFactors set-equality).  `fin_cases` then enumerates the concrete
    # divisors; `revert hq` discharges the non-prime divisors (1, n-1, …) via their
    # false `Nat.Prime` premise, and `decide` checks `a^((n-1)/q) ≠ 1` on the real
    # prime factors.  maxRecDepth is raised because kernel `decide` unfolds npow.
    divisors = [1]
    for q, e in cert.factorization:
        divisors = [d * q**k for d in divisors for k in range(e + 1)]
    divisors = sorted(set(divisors))
    finset = "{" + ", ".join(str(d) for d in divisors) + "}"
    return (
        f"set_option maxRecDepth 16000 in\n"
        f"theorem isPrime_{n} : Nat.Prime {n} := by\n"
        f"  refine lucas_primality {n} ({a} : ZMod {n}) ?_ ?_\n"
        f"  · decide\n"
        f"  · intro q hq hqd\n"
        f"    have hmem : q ∈ Nat.divisors ({n} - 1) :=\n"
        f"      Nat.mem_divisors.mpr ⟨hqd, by norm_num⟩\n"
        f"    have hset : Nat.divisors ({n} - 1) = ({finset} : Finset ℕ) := by decide\n"
        f"    rw [hset] at hmem\n"
        f"    fin_cases hmem <;> revert hq <;> decide\n"
    )


def primality_module(primes, namespace: str = "Primality") -> str:
    """Emit a complete, self-contained Lean file certifying each prime in `primes`."""
    header = (
        "/- Generated by telperion.emit_primality — Pratt/Lucas primality\n"
        "   certificates discharged through Mathlib's `lucas_primality`.\n"
        "   DO NOT EDIT BY HAND. -/\n\n"
        "import Mathlib\n\n"
        f"namespace {namespace}\n\n"
    )
    body = "\n".join(primality_theorem(int(p)) for p in primes)
    return header + body + f"\nend {namespace}\n"
