"""Equational-consequence emitter — an equation that FOLLOWS from polynomial
equation hypotheses.

Generalizes `NullstellensatzEmitter` (whose hypotheses are all `g_i = 0` and whose
target is `p = 0`) to arbitrary polynomial equations: prove

    a_1 = b_1, …, a_m = b_m   ⟹   lhs = rhs,

whenever `lhs − rhs` lies in the ideal generated by the hypothesis differences
`a_i − b_i`.  The finite witness is the cofactor tuple `(c_1, …, c_m)` with

    lhs − rhs ≡ Σ_i c_i · (a_i − b_i)      (exact identity),

which Telperion COMPUTES by Gröbner reduction; a target that does not reduce to
zero modulo the hypotheses is not an equational consequence and is REFUSED.

The emitted Lean is a single Mathlib `linear_combination` — exactly the tactic for
"this equation is a polynomial combination of those":

    theorem <name> : ∀ x y : ℝ, a_1 = b_1 → … → a_m = b_m → lhs = rhs := by
      intro x y h_1 … h_m
      linear_combination c_1*h_1 + … + c_m*h_m
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Sequence

import sympy as sp

from .certify import CertifiedInstance
from .expr import expr_lean
from .family import GridSpec, InequalityFamily
from .lean import LeanProfile
from .workflow import Emitter


def certify_consequence_point(family, pt, name):
    """Certify one equational-consequence instance: (CertifiedInstance, n_checks).

    Reads (lhs, rhs, hypotheses) = family.special[1](pt), where ``hypotheses`` is
    a list of ``(a_i, b_i, hyp_name)`` (the hypothesis ``a_i = b_i`` and its Lean
    binder name).  Reduces ``lhs − rhs`` by the differences ``a_i − b_i``; certifies
    the consequence iff the remainder is zero, storing the cofactors.  Raises
    ValueError (a refusal) when ``lhs = rhs`` is not an equational consequence."""
    lhs, rhs, hypotheses = family.special[1](pt)
    lhs, rhs = sp.expand(sp.sympify(lhs)), sp.expand(sp.sympify(rhs))
    diffs = [sp.expand(sp.sympify(a) - sp.sympify(b)) for a, b, _h in hypotheses]
    syms = tuple(family.symbols)
    if not hypotheses:
        raise ValueError(f"consequence instance '{name}' REFUSED: no hypotheses")

    target = sp.expand(lhs - rhs)
    try:
        cofactors, remainder = sp.reduced(target, diffs, *syms)
    except Exception as e:  # pragma: no cover
        raise ValueError(
            f"consequence instance '{name}' REFUSED: reduction failed ({e})") from e
    if sp.expand(remainder) != 0:
        raise ValueError(
            f"consequence instance '{name}' REFUSED: lhs − rhs does not reduce to "
            f"0 modulo the hypotheses (remainder {sp.expand(remainder)}) — "
            "'lhs = rhs' is not an equational consequence")
    checks = 1
    if sp.expand(target - sum(c * d for c, d in zip(cofactors, diffs))) != 0:
        raise ValueError(
            f"consequence instance '{name}' REFUSED: cofactors do not reproduce "
            "lhs − rhs")
    checks += 1

    inst = CertifiedInstance(
        point=dict(pt), lean_name=name, corners=(),
        payload=(lhs, rhs, list(hypotheses), [sp.expand(c) for c in cofactors]),
    )
    return inst, checks


@dataclass
class ConsequenceEmitter(Emitter):
    """Emit `∀x, (⋀ a_i = b_i) → lhs = rhs` from the cofactors of `lhs − rhs`
    modulo the hypothesis differences, via a single `linear_combination`.
    Deterministic order: grid order."""

    def __post_init__(self):
        self.kind = "consequence"

    def emit_body(self, fam, profile: LeanProfile) -> tuple[str, int]:
        syms = tuple(fam.family.symbols)
        binder = " ".join(str(s) for s in syms)
        lines: list[str] = []
        n = 0
        for inst in fam.instances:
            lhs, rhs, hypotheses, cofactors = inst.payload  # type: ignore[misc]
            lhs_s = expr_lean(sp.expand(lhs), syms)
            rhs_s = expr_lean(sp.expand(rhs), syms)
            hyp_names = [h for _a, _b, h in hypotheses]
            hyp_arrows = "".join(
                f" {expr_lean(sp.expand(sp.sympify(a)), syms)} = "
                f"{expr_lean(sp.expand(sp.sympify(b)), syms)} →"
                for a, b, _h in hypotheses)
            combo = " + ".join(
                f"({expr_lean(sp.expand(c), syms)}) * {hn}"
                for c, hn in zip(cofactors, hyp_names)
                if sp.expand(c) != 0) or "0"

            lines.append(
                f"-- {inst.lean_name}: equational consequence — lhs = rhs follows "
                f"from the hypotheses (lhs − rhs = Σ c_i·(a_i − b_i)).\n"
                f"theorem {inst.lean_name} : ∀ {binder} : ℝ,{hyp_arrows} "
                f"{lhs_s} = {rhs_s} := by\n"
                f"  intro {binder} {' '.join(hyp_names)}\n"
                f"  linear_combination {combo}\n"
            )
            n += 1
        return "\n".join(lines), n


def consequence_family(
    name: str,
    symbols: Sequence[sp.Symbol],
    grid: GridSpec,
    lean_name: Callable,
    spec: Callable,
    constants: dict | None = None,
) -> InequalityFamily:
    """Build an equational-consequence family (kind='consequence').

    spec: ``pt -> (lhs, rhs, hypotheses)`` where ``hypotheses`` is a list of
    ``(a_i, b_i, hyp_name)`` — the hypothesis ``a_i = b_i`` and its Lean binder
    name.  ``certify_consequence_point`` reduces ``lhs − rhs`` by the hypothesis
    differences and refuses if it is not a consequence.
    """
    if not tuple(symbols):
        raise ValueError("consequence families require at least one symbol")
    return InequalityFamily(
        name=name,
        symbols=tuple(symbols),
        grid=grid,
        lean_name=lean_name,
        special=("consequence", spec),
        constants=dict(constants or {}),
    )
