/- Generated by proof/verification/finite_cert/gen_mid_lean.py: credited rate cells, cap D = 14. -/
import R3Cert.BGSpiderMid

namespace R3Cert
namespace BGSCL

theorem mcell_14_1 (cs : List Branch) (hlen : cs.length = 1) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_oneK (D := 14) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (49/100 : ℝ)) (ℓ := (138043/11000000 : ℝ))
    (u := (939668600939/3752430000000 : ℝ)) (by norm_num)
    (by
      have e : (1 + (49/100 : ℝ) / ((1:ℝ) + 1)) = (249/200 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (249/200 : ℝ) ^ 11 * (64 / 621)) (c := (138043/1000000 : ℝ)) (a := (138043/1000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold Nb1K; simp only [max_le_iff]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_2 (cs : List Branch) (hlen : cs.length = 2) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 2) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (133/150 : ℝ))
    (ℓ := (261797/5000000 : ℝ)) (umax := (15238203047/192390000000 : ℝ)) (unc := (15238203047/192390000000 : ℝ)) (ρm := (27/2656 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (133/150 : ℝ) / ((((2:ℕ):ℝ)) + 1)) = (583/450 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (583/450 : ℝ) ^ 11 * (64 / 621)) (c := (2879767/5000000 : ℝ)) (a := (2879767/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len2_le (D := 14) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_3 (cs : List Branch) (hlen : cs.length = 3) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 3) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (107/100 : ℝ))
    (ℓ := (3350669/110000000 : ℝ)) (umax := (9898891823/167310000000 : ℝ)) (unc := (3040666921/55770000000 : ℝ)) (ρm := (3/4736 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (107/100 : ℝ) / ((((3:ℕ):ℝ)) + 1)) = (507/400 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (507/400 : ℝ) ^ 11 * (64 / 621)) (c := (3350669/10000000 : ℝ)) (a := (3350669/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len3_le (D := 14) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_4 (cs : List Branch) (hlen : cs.length = 4) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 4) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (7/5 : ℝ))
    (ℓ := (1107581/27500000 : ℝ)) (umax := (15015689/330000000 : ℝ)) (unc := (12581609/330000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (7/5 : ℝ) / ((((4:ℕ):ℝ)) + 1)) = (32/25 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (32/25 : ℝ) ^ 11 * (64 / 621)) (c := (1107581/2500000 : ℝ)) (a := (1107581/2500000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_5 (cs : List Branch) (hlen : cs.length = 5) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 5) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (26/15 : ℝ))
    (ℓ := (648977/13750000 : ℝ)) (umax := (116505827/3190000000 : ℝ)) (unc := (261741661/9570000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (26/15 : ℝ) / ((((5:ℕ):ℝ)) + 1)) = (58/45 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (58/45 : ℝ) ^ 11 * (64 / 621)) (c := (648977/1250000 : ℝ)) (a := (648977/1250000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_6 (cs : List Branch) (hlen : cs.length = 6) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 6) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (46/25 : ℝ))
    (ℓ := (1473489/55000000 : ℝ)) (umax := (2270029769/72930000000 : ℝ)) (unc := (2023261707/92378000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (46/25 : ℝ) / ((((6:ℕ):ℝ)) + 1)) = (221/175 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (221/175 : ℝ) ^ 11 * (64 / 621)) (c := (1473489/5000000 : ℝ)) (a := (1473489/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_7 (cs : List Branch) (hlen : cs.length = 7) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 7) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (161/75 : ℝ))
    (ℓ := (1711483/55000000 : ℝ)) (umax := (2199083943/83710000000 : ℝ)) (unc := (6235303887/318098000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (161/75 : ℝ) / ((((7:ℕ):ℝ)) + 1)) = (761/600 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (761/600 : ℝ) ^ 11 * (64 / 621)) (c := (1711483/5000000 : ℝ)) (a := (1711483/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_8 (cs : List Branch) (hlen : cs.length = 8) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 8) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (62/25 : ℝ))
    (ℓ := (80953/2200000 : ℝ)) (umax := (2126690243/94710000000 : ℝ)) (unc := (2134733529/119966000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (62/25 : ℝ) / ((((8:ℕ):ℝ)) + 1)) = (287/225 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (287/225 : ℝ) ^ 11 * (64 / 621)) (c := (80953/200000 : ℝ)) (a := (80953/200000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_9 (cs : List Branch) (hlen : cs.length = 9) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 9) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (279/100 : ℝ))
    (ℓ := (4344353/110000000 : ℝ)) (umax := (8222253731/422070000000 : ℝ)) (unc := (482179481/29417000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (279/100 : ℝ) / ((((9:ℕ):ℝ)) + 1)) = (1279/1000 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (1279/1000 : ℝ) ^ 11 * (64 / 621)) (c := (4344353/10000000 : ℝ)) (a := (4344353/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_10 (cs : List Branch) (hlen : cs.length = 10) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 10) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (47/15 : ℝ))
    (ℓ := (4846301/110000000 : ℝ)) (umax := (99131339/5830000000 : ℝ)) (unc := (18799267/1219000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (47/15 : ℝ) / ((((10:ℕ):ℝ)) + 1)) = (212/165 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (212/165 : ℝ) ^ 11 * (64 / 621)) (c := (4846301/10000000 : ℝ)) (a := (4846301/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_11 (cs : List Branch) (hlen : cs.length = 11) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 11) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (517/150 : ℝ))
    (ℓ := (2524741/55000000 : ℝ)) (umax := (3822637971/254870000000 : ℝ)) (unc := (780031163/53291000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (517/150 : ℝ) / ((((11:ℕ):ℝ)) + 1)) = (2317/1800 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (2317/1800 : ℝ) ^ 11 * (64 / 621)) (c := (2524741/5000000 : ℝ)) (a := (2524741/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_12 (cs : List Branch) (hlen : cs.length = 12) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 12) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (72/25 : ℝ))
    (ℓ := (-356129/55000000 : ℝ)) (umax := (1887791033/131010000000 : ℝ)) (unc := (131548283/9131000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (72/25 : ℝ) / ((((12:ℕ):ℝ)) + 1)) = (397/325 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (397/325 : ℝ) ^ 11 * (64 / 621)) (c := (-356129/5000000 : ℝ)) (a := (356129/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_14_13 (cs : List Branch) (hlen : cs.length = 13) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 14)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (563/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 14) (K := 13) (by norm_num) (by norm_num) (α := (563/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (39/20 : ℝ))
    (ℓ := (-8355063/110000000 : ℝ)) (umax := (105438041/7337000000 : ℝ)) (unc := (105438041/7337000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (39/20 : ℝ) / ((((13:ℕ):ℝ)) + 1)) = (319/280 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (319/280 : ℝ) ^ 11 * (64 / 621)) (c := (-8355063/10000000 : ℝ)) (a := (8355063/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 13 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem rateCellKap_14 : RateCellKap 14 (563/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) := by
  intro cs hlen hcap hna
  obtain ⟨K, hK⟩ : ∃ K, cs.length = K := ⟨_, rfl⟩
  have hK0 : 1 ≤ K := by
    rcases cs with _ | ⟨a, t⟩
    · exact absurd (Or.inr ⟨0, rfl⟩) hna
    · simp at hK; omega
  have hKD : K ≤ 13 := by omega
  interval_cases K
  · exact mcell_14_1 cs hK hcap hna
  · exact mcell_14_2 cs hK hcap hna
  · exact mcell_14_3 cs hK hcap hna
  · exact mcell_14_4 cs hK hcap hna
  · exact mcell_14_5 cs hK hcap hna
  · exact mcell_14_6 cs hK hcap hna
  · exact mcell_14_7 cs hK hcap hna
  · exact mcell_14_8 cs hK hcap hna
  · exact mcell_14_9 cs hK hcap hna
  · exact mcell_14_10 cs hK hcap hna
  · exact mcell_14_11 cs hK hcap hna
  · exact mcell_14_12 cs hK hcap hna
  · exact mcell_14_13 cs hK hcap hna

end BGSCL
end R3Cert
