/- Generated by proof/verification/finite_cert/gen_mid_lean.py: credited rate cells, cap D = 12. -/
import R3Cert.BGSpiderMid

namespace R3Cert
namespace BGSCL

theorem mcell_12_1 (cs : List Branch) (hlen : cs.length = 1) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_oneK (D := 12) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (49/100 : ℝ)) (ℓ := (138043/11000000 : ℝ))
    (u := (12563708536651/50205870000000 : ℝ)) (by norm_num)
    (by
      have e : (1 + (49/100 : ℝ) / ((1:ℝ) + 1)) = (249/200 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (249/200 : ℝ) ^ 11 * (64 / 621)) (c := (138043/1000000 : ℝ)) (a := (138043/1000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold Nb1K; simp only [max_le_iff]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_2 (cs : List Branch) (hlen : cs.length = 2) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 2) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (131/150 : ℝ))
    (ℓ := (5381527/110000000 : ℝ)) (umax := (5090001663/63910000000 : ℝ)) (unc := (717542621963/9011310000000 : ℝ)) (ρm := (23/2272 : ℝ))
    (km := (1/400 : ℝ)) (by norm_num)
    (by
      have e : (1 + (131/150 : ℝ) / ((((2:ℕ):ℝ)) + 1)) = (581/450 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (581/450 : ℝ) ^ 11 * (64 / 621)) (c := (5381527/10000000 : ℝ)) (a := (5381527/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len2_le (D := 12) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_3 (cs : List Branch) (hlen : cs.length = 3) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 3) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (107/100 : ℝ))
    (ℓ := (3350669/110000000 : ℝ)) (umax := (9926665283/167310000000 : ℝ)) (unc := (3040666921/55770000000 : ℝ)) (ρm := (23/36480 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (107/100 : ℝ) / ((((3:ℕ):ℝ)) + 1)) = (507/400 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (507/400 : ℝ) ^ 11 * (64 / 621)) (c := (3350669/10000000 : ℝ)) (a := (3350669/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len3_le (D := 12) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_4 (cs : List Branch) (hlen : cs.length = 4) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 4) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (7/5 : ℝ))
    (ℓ := (1107581/27500000 : ℝ)) (umax := (15070469/330000000 : ℝ)) (unc := (12581609/330000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (7/5 : ℝ) / ((((4:ℕ):ℝ)) + 1)) = (32/25 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (32/25 : ℝ) ^ 11 * (64 / 621)) (c := (1107581/2500000 : ℝ)) (a := (1107581/2500000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_5 (cs : List Branch) (hlen : cs.length = 5) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 5) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (33/20 : ℝ))
    (ℓ := (3999687/110000000 : ℝ)) (umax := (1876094257/50490000000 : ℝ)) (unc := (258299/8690400 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (33/20 : ℝ) / ((((5:ℕ):ℝ)) + 1)) = (51/40 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (51/40 : ℝ) ^ 11 * (64 / 621)) (c := (3999687/10000000 : ℝ)) (a := (3999687/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_6 (cs : List Branch) (hlen : cs.length = 6) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 6) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (2 : ℝ))
    (ℓ := (12301/275000 : ℝ)) (umax := (90946721/2970000000 : ℝ)) (unc := (11947/511200 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (2 : ℝ) / ((((6:ℕ):ℝ)) + 1)) = (9/7 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (9/7 : ℝ) ^ 11 * (64 / 621)) (c := (12301/25000 : ℝ)) (a := (12301/25000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_7 (cs : List Branch) (hlen : cs.length = 7) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 7) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (161/75 : ℝ))
    (ℓ := (1711483/55000000 : ℝ)) (umax := (2212979803/83710000000 : ℝ)) (unc := (6472923093/318098000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (161/75 : ℝ) / ((((7:ℕ):ℝ)) + 1)) = (761/600 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (761/600 : ℝ) ^ 11 * (64 / 621)) (c := (1711483/5000000 : ℝ)) (a := (1711483/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_8 (cs : List Branch) (hlen : cs.length = 8) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 8) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (62/25 : ℝ))
    (ℓ := (80953/2200000 : ℝ)) (umax := (2142412103/94710000000 : ℝ)) (unc := (2224348131/119966000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (62/25 : ℝ) / ((((8:ℕ):ℝ)) + 1)) = (287/225 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (287/225 : ℝ) ^ 11 * (64 / 621)) (c := (80953/200000 : ℝ)) (a := (80953/200000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_9 (cs : List Branch) (hlen : cs.length = 9) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 9) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (279/100 : ℝ))
    (ℓ := (4344353/110000000 : ℝ)) (umax := (8292317351/422070000000 : ℝ)) (unc := (254518601/14708500000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (279/100 : ℝ) / ((((9:ℕ):ℝ)) + 1)) = (1279/1000 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (1279/1000 : ℝ) ^ 11 * (64 / 621)) (c := (4344353/10000000 : ℝ)) (a := (4344353/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_10 (cs : List Branch) (hlen : cs.length = 10) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 10) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (47/15 : ℝ))
    (ℓ := (4846301/110000000 : ℝ)) (umax := (100099119/5830000000 : ℝ)) (unc := (9956107/609500000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (47/15 : ℝ) / ((((10:ℕ):ℝ)) + 1)) = (212/165 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (212/165 : ℝ) ^ 11 * (64 / 621)) (c := (4846301/10000000 : ℝ)) (a := (4846301/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_12_11 (cs : List Branch) (hlen : cs.length = 11) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 12)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (323/500000 : ℝ)
      + kapF (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 12) (K := 11) (by norm_num) (by norm_num) (α := (323/500000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (451/150 : ℝ))
    (ℓ := (187019/11000000 : ℝ)) (umax := (408949469/25886500000 : ℝ)) (unc := (408949469/25886500000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (451/150 : ℝ) / ((((11:ℕ):ℝ)) + 1)) = (2251/1800 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (2251/1800 : ℝ) ^ 11 * (64 / 621)) (c := (187019/1000000 : ℝ)) (a := (187019/1000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 11 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem rateCellKap_12 : RateCellKap 12 (323/500000 : ℝ) (0 : ℝ) (1/400 : ℝ) (1/200 : ℝ) (0 : ℝ) := by
  intro cs hlen hcap hna
  obtain ⟨K, hK⟩ : ∃ K, cs.length = K := ⟨_, rfl⟩
  have hK0 : 1 ≤ K := by
    rcases cs with _ | ⟨a, t⟩
    · exact absurd (Or.inr ⟨0, rfl⟩) hna
    · simp at hK; omega
  have hKD : K ≤ 11 := by omega
  interval_cases K
  · exact mcell_12_1 cs hK hcap hna
  · exact mcell_12_2 cs hK hcap hna
  · exact mcell_12_3 cs hK hcap hna
  · exact mcell_12_4 cs hK hcap hna
  · exact mcell_12_5 cs hK hcap hna
  · exact mcell_12_6 cs hK hcap hna
  · exact mcell_12_7 cs hK hcap hna
  · exact mcell_12_8 cs hK hcap hna
  · exact mcell_12_9 cs hK hcap hna
  · exact mcell_12_10 cs hK hcap hna
  · exact mcell_12_11 cs hK hcap hna

end BGSCL
end R3Cert
