/- Generated by proof/verification/finite_cert/gen_mid_lean.py: credited rate cells, cap D = 16. -/
import R3Cert.BGSpiderMid

namespace R3Cert
namespace BGSCL

theorem mcell_16_1 (cs : List Branch) (hlen : cs.length = 1) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_oneK (D := 16) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (37/75 : ℝ)) (ℓ := (1527587/110000000 : ℝ))
    (u := (4629227977841/18496170000000 : ℝ)) (by norm_num)
    (by
      have e : (1 + (37/75 : ℝ) / ((1:ℝ) + 1)) = (187/150 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (187/150 : ℝ) ^ 11 * (64 / 621)) (c := (1527587/10000000 : ℝ)) (a := (1527587/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold Nb1K; simp only [max_le_iff]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_2 (cs : List Branch) (hlen : cs.length = 2) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 2) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (9/10 : ℝ))
    (ℓ := (245463/4400000 : ℝ)) (umax := (1013960891/12870000000 : ℝ)) (unc := (21291962771/270270000000 : ℝ)) (ρm := (31/3040 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (9/10 : ℝ) / ((((2:ℕ):ℝ)) + 1)) = (13/10 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (13/10 : ℝ) ^ 11 * (64 / 621)) (c := (245463/400000 : ℝ)) (a := (245463/400000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len2_le (D := 16) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_3 (cs : List Branch) (hlen : cs.length = 3) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 3) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (107/100 : ℝ))
    (ℓ := (3350669/110000000 : ℝ)) (umax := (9881491583/167310000000 : ℝ)) (unc := (3040666921/55770000000 : ℝ)) (ρm := (31/48768 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (107/100 : ℝ) / ((((3:ℕ):ℝ)) + 1)) = (507/400 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (507/400 : ℝ) ^ 11 * (64 / 621)) (c := (3350669/10000000 : ℝ)) (a := (3350669/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len3_le (D := 16) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_4 (cs : List Branch) (hlen : cs.length = 4) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 4) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (7/5 : ℝ))
    (ℓ := (1107581/27500000 : ℝ)) (umax := (14981369/330000000 : ℝ)) (unc := (12581609/330000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (7/5 : ℝ) / ((((4:ℕ):ℝ)) + 1)) = (32/25 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (32/25 : ℝ) ^ 11 * (64 / 621)) (c := (1107581/2500000 : ℝ)) (a := (1107581/2500000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_5 (cs : List Branch) (hlen : cs.length = 5) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 5) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (26/15 : ℝ))
    (ℓ := (648977/13750000 : ℝ)) (umax := (116174067/3190000000 : ℝ)) (unc := (261741661/9570000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (26/15 : ℝ) / ((((5:ℕ):ℝ)) + 1)) = (58/45 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (58/45 : ℝ) ^ 11 * (64 / 621)) (c := (648977/1250000 : ℝ)) (a := (648977/1250000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_6 (cs : List Branch) (hlen : cs.length = 6) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 6) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (19/10 : ℝ))
    (ℓ := (1845551/55000000 : ℝ)) (umax := (903654341/29370000000 : ℝ)) (unc := (2364481/108508800 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (19/10 : ℝ) / ((((6:ℕ):ℝ)) + 1)) = (89/70 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (89/70 : ℝ) ^ 11 * (64 / 621)) (c := (1845551/5000000 : ℝ)) (a := (1845551/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_7 (cs : List Branch) (hlen : cs.length = 7) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 7) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (161/75 : ℝ))
    (ℓ := (1711483/55000000 : ℝ)) (umax := (2190378103/83710000000 : ℝ)) (unc := (6086434023/318098000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (161/75 : ℝ) / ((((7:ℕ):ℝ)) + 1)) = (761/600 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (761/600 : ℝ) ^ 11 * (64 / 621)) (c := (1711483/5000000 : ℝ)) (a := (1711483/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_8 (cs : List Branch) (hlen : cs.length = 8) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 8) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (62/25 : ℝ))
    (ℓ := (80953/2200000 : ℝ)) (umax := (2116840403/94710000000 : ℝ)) (unc := (2078589441/119966000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (62/25 : ℝ) / ((((8:ℕ):ℝ)) + 1)) = (287/225 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (287/225 : ℝ) ^ 11 * (64 / 621)) (c := (80953/200000 : ℝ)) (a := (80953/200000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_9 (cs : List Branch) (hlen : cs.length = 9) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 9) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (141/50 : ℝ))
    (ℓ := (920413/22000000 : ℝ)) (umax := (4085870029/211530000000 : ℝ)) (unc := (4257232863/267938000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (141/50 : ℝ) / ((((9:ℕ):ℝ)) + 1)) = (641/500 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (641/500 : ℝ) ^ 11 * (64 / 621)) (c := (920413/2000000 : ℝ)) (a := (920413/2000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_10 (cs : List Branch) (hlen : cs.length = 10) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 10) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (47/15 : ℝ))
    (ℓ := (4846301/110000000 : ℝ)) (umax := (98525019/5830000000 : ℝ)) (unc := (18101999/1219000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (47/15 : ℝ) / ((((10:ℕ):ℝ)) + 1)) = (212/165 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (212/165 : ℝ) ^ 11 * (64 / 621)) (c := (4846301/10000000 : ℝ)) (a := (4846301/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_11 (cs : List Branch) (hlen : cs.length = 11) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 11) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (517/150 : ℝ))
    (ℓ := (2524741/55000000 : ℝ)) (umax := (3796131491/254870000000 : ℝ)) (unc := (749548711/53291000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (517/150 : ℝ) / ((((11:ℕ):ℝ)) + 1)) = (2317/1800 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (2317/1800 : ℝ) ^ 11 * (64 / 621)) (c := (2524741/5000000 : ℝ)) (a := (2524741/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_12 (cs : List Branch) (hlen : cs.length = 12) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 12) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (87/25 : ℝ))
    (ℓ := (3367357/110000000 : ℝ)) (umax := (460268507/33990000000 : ℝ)) (unc := (32066149/2369000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (87/25 : ℝ) / ((((12:ℕ):ℝ)) + 1)) = (412/325 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (412/325 : ℝ) ^ 11 * (64 / 621)) (c := (3367357/10000000 : ℝ)) (a := (3367357/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_13 (cs : List Branch) (hlen : cs.length = 13) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 13) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (377/150 : ℝ))
    (ℓ := (-4561853/110000000 : ℝ)) (umax := (770233991/56971000000 : ℝ)) (unc := (770233991/56971000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (377/150 : ℝ) / ((((13:ℕ):ℝ)) + 1)) = (2477/2100 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (2477/2100 : ℝ) ^ 11 * (64 / 621)) (c := (-4561853/10000000 : ℝ)) (a := (4561853/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_14 (cs : List Branch) (hlen : cs.length = 14) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 14) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (161/75 : ℝ))
    (ℓ := (-31979/440000 : ℝ)) (umax := (195628969/14789000000 : ℝ)) (unc := (195628969/14789000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (161/75 : ℝ) / ((((14:ℕ):ℝ)) + 1)) = (1286/1125 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (1286/1125 : ℝ) ^ 11 * (64 / 621)) (c := (-31979/40000 : ℝ)) (a := (31979/40000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_16_15 (cs : List Branch) (hlen : cs.length = 15) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 16)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (511/1000000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 16) (K := 15) (by norm_num) (by norm_num) (α := (511/1000000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (23/10 : ℝ))
    (ℓ := (-90151/1250000 : ℝ)) (umax := (17886263/1403000000 : ℝ)) (unc := (17886263/1403000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (23/10 : ℝ) / ((((15:ℕ):ℝ)) + 1)) = (183/160 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (183/160 : ℝ) ^ 11 * (64 / 621)) (c := (-991661/1250000 : ℝ)) (a := (991661/1250000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 15 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem rateCellKap_16 : RateCellKap 16 (511/1000000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) := by
  intro cs hlen hcap hna
  obtain ⟨K, hK⟩ : ∃ K, cs.length = K := ⟨_, rfl⟩
  have hK0 : 1 ≤ K := by
    rcases cs with _ | ⟨a, t⟩
    · exact absurd (Or.inr ⟨0, rfl⟩) hna
    · simp at hK; omega
  have hKD : K ≤ 15 := by omega
  interval_cases K
  · exact mcell_16_1 cs hK hcap hna
  · exact mcell_16_2 cs hK hcap hna
  · exact mcell_16_3 cs hK hcap hna
  · exact mcell_16_4 cs hK hcap hna
  · exact mcell_16_5 cs hK hcap hna
  · exact mcell_16_6 cs hK hcap hna
  · exact mcell_16_7 cs hK hcap hna
  · exact mcell_16_8 cs hK hcap hna
  · exact mcell_16_9 cs hK hcap hna
  · exact mcell_16_10 cs hK hcap hna
  · exact mcell_16_11 cs hK hcap hna
  · exact mcell_16_12 cs hK hcap hna
  · exact mcell_16_13 cs hK hcap hna
  · exact mcell_16_14 cs hK hcap hna
  · exact mcell_16_15 cs hK hcap hna

end BGSCL
end R3Cert
