/- Generated by proof/verification/finite_cert/gen_mid_lean.py: credited rate cells, cap D = 3. -/
import R3Cert.BGSpiderMid

namespace R3Cert
namespace BGSCL

theorem mcell_3_1 (cs : List Branch) (hlen : cs.length = 1) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 3)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (609/250000 : ℝ)
      + kapF (1/250 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (609/250000 : ℝ) (1/250 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_oneK (D := 3) (by norm_num) (by norm_num) (α := (609/250000 : ℝ)) (k1 := (1/250 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (34/75 : ℝ)) (ℓ := (-22857/10000000 : ℝ))
    (u := (16744028063/68310000000 : ℝ)) (by norm_num)
    (by
      have e : (1 + (34/75 : ℝ) / ((1:ℝ) + 1)) = (92/75 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (92/75 : ℝ) ^ 11 * (64 / 621)) (c := (-251427/10000000 : ℝ)) (a := (251427/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by intro j h1 h2; have h3 : j ≤ 2 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold Nb1K; simp only [max_le_iff]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_3_2 (cs : List Branch) (hlen : cs.length = 2) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 3)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (609/250000 : ℝ)
      + kapF (1/250 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (609/250000 : ℝ) (1/250 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 3) (K := 2) (by norm_num) (by norm_num) (α := (609/250000 : ℝ)) (k1 := (1/250 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (59/75 : ℝ))
    (ℓ := (144583/5500000 : ℝ)) (umax := (665356733/7810000000 : ℝ)) (unc := (1828199239/23430000000 : ℝ)) (ρm := (5/544 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (59/75 : ℝ) / ((((2:ℕ):ℝ)) + 1)) = (284/225 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (284/225 : ℝ) ^ 11 * (64 / 621)) (c := (144583/500000 : ℝ)) (a := (144583/500000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 2 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len2_le (D := 3) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem rateCellKap_3 : RateCellKap 3 (609/250000 : ℝ) (1/250 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) := by
  intro cs hlen hcap hna
  obtain ⟨K, hK⟩ : ∃ K, cs.length = K := ⟨_, rfl⟩
  have hK0 : 1 ≤ K := by
    rcases cs with _ | ⟨a, t⟩
    · exact absurd (Or.inr ⟨0, rfl⟩) hna
    · simp at hK; omega
  have hKD : K ≤ 2 := by omega
  interval_cases K
  · exact mcell_3_1 cs hK hcap hna
  · exact mcell_3_2 cs hK hcap hna

end BGSCL
end R3Cert
