/- Generated by proof/verification/finite_cert/gen_mid_lean.py: root certificate, root degree k = 15. -/
import R3Cert.BGSpiderMidCellsD15
import R3Cert.BGSpiderMidSpiders

namespace R3Cert
namespace BGSCL

def WA_15 : ℕ → ℤ
  | 1 => -33602688594
  | 2 => -2769650592
  | 3 => 8879821081
  | 4 => 13076908987
  | 5 => 13611436673
  | 6 => 12075951106
  | 7 => 9256516359
  | 8 => 5585925918
  | 9 => 1322108808
  | 10 => -3371674253
  | 11 => -8387031570
  | 12 => -13649176687
  | 13 => -19104826482
  | 14 => -24714966751
  | _ => 0

def tys_15 : List (ℕ × ℤ) := [(3, 9282949130), (1, -148064908234), (2, 12716426044), (3, -33602688594), (5, -2769650592), (7, 8879821081), (9, 13076908987), (11, 13611436673), (13, 12075951106), (15, 9256516359), (17, 5585925918), (19, 1322108808), (21, -3371674253), (23, -8387031570), (25, -13649176687), (27, -19104826482), (29, -24714966751)]

theorem check_15 : (List.range' 149 342).all (fun N => decide
    ((9327317392 : ℤ) + 9282949130 + (dpRow tys_15 491 14).getD (N - 3) NEGI - 550000000 * (N : ℤ)
      < lowTabGet N)) = true := by decide +kernel

theorem midroot_15 (cs : List Branch) (hlen : cs.length = 15) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ∃ c ∈ cs, ¬ IsAtom c) (h1 : 149 ≤ bsizeList cs) (h2 : bsizeList cs ≤ 490) :
    phiRoot cs < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 := by
  have hσ : (1 / ((cs.length : ℝ) * (23/20 : ℝ))) = 1 / (((15:ℕ):ℝ) * (23/20 : ℝ)) := by rw [hlen]
  obtain ⟨ht, hn⟩ := htype_of (D := 15) (by norm_num) (by norm_num) rateCellKap_15
    (SC := 10 ^ 12) (σ := 1 / (((15:ℕ):ℝ) * (23/20 : ℝ))) (by norm_num) (by positivity)
    (tys := tys_15) (VNI := 9282949130) (WL := -148064908234) (WC := 12716426044) (WA := WA_15)
    (by unfold NbK; simp only [max_le_iff]; norm_num) (by norm_num) (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT, WA_15])
    (by simp [tys_15]) (by simp [tys_15]) (by simp [tys_15])
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> simp [tys_15, WA_15])
  have hb := phiRoot_le_dp (D := 15) (tys := tys_15) (SC := 10 ^ 12) (α := (11/20000 : ℝ)) (t := (23/20 : ℝ))
    (VNI := 9282949130) (by norm_num) (by norm_num) cs hcap (by rw [hσ]; exact ht) hna
    (by rw [hσ]; exact hn) 491 (by omega)
  rw [hlen] at hb
  have hlt := log_le_of_taylor (x := (23/20 : ℝ)) (c := (1397621/10000000 : ℝ)) (a := (1397621/10000000 : ℝ)) (by norm_num)
    (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
  have hc := check_15
  rw [List.all_eq_true] at hc
  have hN := hc (bsizeList cs) (List.mem_range'_1.mpr ⟨h1, by omega⟩)
  simp only [decide_eq_true_eq] at hN
  have hNR : (((9327317392 : ℤ) + 9282949130 + (dpRow tys_15 491 14).getD (bsizeList cs - 3) NEGI
      - 550000000 * (bsizeList cs : ℤ) : ℤ) : ℝ) < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) := by exact_mod_cast hN
  push_cast at hNR
  have hNn : (0:ℝ) ≤ (bsizeList cs : ℝ) := Nat.cast_nonneg _
  have hCI : Real.log (23/20 : ℝ) + 1 / (23/20 : ℝ) - 1 ≤ (9327317392 : ℝ) / 10 ^ 12 := by
    have : (1397621/10000000 : ℝ) + 1 / (23/20 : ℝ) - 1 ≤ (9327317392 : ℝ) / 10 ^ 12 := by norm_num
    linarith
  have hal : (550000000 : ℝ) / 10 ^ 12 ≤ (11/20000 : ℝ) := by norm_num
  have hmul : (11/20000 : ℝ) * (bsizeList cs : ℝ) ≥ (550000000 : ℝ) / 10 ^ 12 * (bsizeList cs : ℝ) :=
    mul_le_mul_of_nonneg_right hal hNn
  have hNR' : (((9327317392 : ℝ) + 9282949130 + (((dpRow tys_15 491 14).getD (bsizeList cs - 3) NEGI : ℤ) : ℝ)
      - 550000000 * (bsizeList cs : ℝ))) / 10 ^ 12 < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 :=
    div_lt_div_of_pos_right (by linarith) (by norm_num)
  linarith

end BGSCL
end R3Cert
