/- Generated by proof/verification/finite_cert/gen_mid_lean.py: credited rate cells, cap D = 7. -/
import R3Cert.BGSpiderMid

namespace R3Cert
namespace BGSCL

theorem mcell_7_1 (cs : List Branch) (hlen : cs.length = 1) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 7)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (69/100000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (69/100000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_oneK (D := 7) (by norm_num) (by norm_num) (α := (69/100000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (12/25 : ℝ)) (ℓ := (937773/110000000 : ℝ))
    (u := (1543083892037/6168690000000 : ℝ)) (by norm_num)
    (by
      have e : (1 + (12/25 : ℝ) / ((1:ℝ) + 1)) = (31/25 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (31/25 : ℝ) ^ 11 * (64 / 621)) (c := (937773/10000000 : ℝ)) (a := (937773/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by intro j h1 h2; have h3 : j ≤ 6 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold Nb1K; simp only [max_le_iff]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_7_2 (cs : List Branch) (hlen : cs.length = 2) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 7)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (69/100000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (69/100000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 7) (K := 2) (by norm_num) (by norm_num) (α := (69/100000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (43/50 : ℝ))
    (ℓ := (454727/10000000 : ℝ)) (umax := (5097017737/63690000000 : ℝ)) (unc := (45852129833/573210000000 : ℝ)) (ρm := (13/1312 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (43/50 : ℝ) / ((((2:ℕ):ℝ)) + 1)) = (193/150 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (193/150 : ℝ) ^ 11 * (64 / 621)) (c := (5001997/10000000 : ℝ)) (a := (5001997/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 6 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len2_le (D := 7) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_7_3 (cs : List Branch) (hlen : cs.length = 3) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 7)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (69/100000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (69/100000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 7) (K := 3) (by norm_num) (by norm_num) (α := (69/100000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (107/100 : ℝ))
    (ℓ := (3350669/110000000 : ℝ)) (umax := (9941388563/167310000000 : ℝ)) (unc := (3040666921/55770000000 : ℝ)) (ρm := (13/21120 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (107/100 : ℝ) / ((((3:ℕ):ℝ)) + 1)) = (507/400 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (507/400 : ℝ) ^ 11 * (64 / 621)) (c := (3350669/10000000 : ℝ)) (a := (3350669/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 6 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len3_le (D := 7) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_7_4 (cs : List Branch) (hlen : cs.length = 4) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 7)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (69/100000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (69/100000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 7) (K := 4) (by norm_num) (by norm_num) (α := (69/100000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (7/5 : ℝ))
    (ℓ := (1107581/27500000 : ℝ)) (umax := (15099509/330000000 : ℝ)) (unc := (12581609/330000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (7/5 : ℝ) / ((((4:ℕ):ℝ)) + 1)) = (32/25 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (32/25 : ℝ) ^ 11 * (64 / 621)) (c := (1107581/2500000 : ℝ)) (a := (1107581/2500000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 6 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_7_5 (cs : List Branch) (hlen : cs.length = 5) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 7)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (69/100000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (69/100000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 7) (K := 5) (by norm_num) (by norm_num) (α := (69/100000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (26/15 : ℝ))
    (ℓ := (648977/13750000 : ℝ)) (umax := (117316087/3190000000 : ℝ)) (unc := (261741661/9570000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (26/15 : ℝ) / ((((5:ℕ):ℝ)) + 1)) = (58/45 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (58/45 : ℝ) ^ 11 * (64 / 621)) (c := (648977/1250000 : ℝ)) (a := (648977/1250000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 6 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_7_6 (cs : List Branch) (hlen : cs.length = 6) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 7)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (69/100000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (69/100000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 7) (K := 6) (by norm_num) (by norm_num) (α := (69/100000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (91/50 : ℝ))
    (ℓ := (2697821/110000000 : ℝ)) (umax := (4579195969/145530000000 : ℝ)) (unc := (1418510927/61446000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (91/50 : ℝ) / ((((6:ℕ):ℝ)) + 1)) = (63/50 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (63/50 : ℝ) ^ 11 * (64 / 621)) (c := (2697821/10000000 : ℝ)) (a := (2697821/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 6 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem rateCellKap_7 : RateCellKap 7 (69/100000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (0 : ℝ) := by
  intro cs hlen hcap hna
  obtain ⟨K, hK⟩ : ∃ K, cs.length = K := ⟨_, rfl⟩
  have hK0 : 1 ≤ K := by
    rcases cs with _ | ⟨a, t⟩
    · exact absurd (Or.inr ⟨0, rfl⟩) hna
    · simp at hK; omega
  have hKD : K ≤ 6 := by omega
  interval_cases K
  · exact mcell_7_1 cs hK hcap hna
  · exact mcell_7_2 cs hK hcap hna
  · exact mcell_7_3 cs hK hcap hna
  · exact mcell_7_4 cs hK hcap hna
  · exact mcell_7_5 cs hK hcap hna
  · exact mcell_7_6 cs hK hcap hna

end BGSCL
end R3Cert
