/- Generated by proof/verification/finite_cert/gen_mid_lean.py: root certificate, root degree k = 22. -/
import R3Cert.BGSpiderMidCellsD22
import R3Cert.BGSpiderMidSpiders

namespace R3Cert
namespace BGSCL

def WA_22 : ℕ → ℤ
  | 1 => -42086826933
  | 2 => -8765193172
  | 3 => 3839756522
  | 4 => 8427489599
  | 5 => 9082525005
  | 6 => 7517470795
  | 7 => 4576485121
  | 8 => 723898250
  | 9 => -3763762176
  | 10 => -8711557238
  | 11 => -14003392599
  | 12 => -19559195675
  | 13 => -25321934998
  | 14 => -31249864520
  | 15 => -37311769659
  | 16 => -43483683818
  | 17 => -49746818532
  | 18 => -56085917786
  | 19 => -62490788002
  | 20 => -68950805995
  | 21 => -75451054204
  | _ => 0

def tys_22 : List (ℕ × ℤ) := [(3, 5760752252), (1, -166703231027), (2, 6181985112), (3, -42086826933), (5, -8765193172), (7, 3839756522), (9, 8427489599), (11, 9082525005), (13, 7517470795), (15, 4576485121), (17, 723898250), (19, -3763762176), (21, -8711557238), (23, -14003392599), (25, -19559195675), (27, -25321934998), (29, -31249864520), (31, -37311769659), (33, -43483683818), (35, -49746818532), (37, -56085917786), (39, -62490788002), (41, -68950805995), (43, -75451054204)]

theorem check_22 : (List.range' 149 342).all (fun N => decide
    ((9327317392 : ℤ) + 5760752252 + (dpRow tys_22 491 21).getD (N - 3) NEGI - 357000000 * (N : ℤ)
      < lowTabGet N)) = true := by decide +kernel

theorem midroot_22 (cs : List Branch) (hlen : cs.length = 22) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 22)
    (hna : ∃ c ∈ cs, ¬ IsAtom c) (h1 : 149 ≤ bsizeList cs) (h2 : bsizeList cs ≤ 490) :
    phiRoot cs < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 := by
  have hσ : (1 / ((cs.length : ℝ) * (23/20 : ℝ))) = 1 / (((22:ℕ):ℝ) * (23/20 : ℝ)) := by rw [hlen]
  obtain ⟨ht, hn⟩ := htype_of (D := 22) (by norm_num) (by norm_num) rateCellKap_22
    (SC := 10 ^ 12) (σ := 1 / (((22:ℕ):ℝ) * (23/20 : ℝ))) (by norm_num) (by positivity)
    (tys := tys_22) (VNI := 5760752252) (WL := -166703231027) (WC := 6181985112) (WA := WA_22)
    (by unfold NbK; simp only [max_le_iff]; norm_num) (by norm_num) (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 21 := (by omega); interval_cases j <;> norm_num [bjT, WA_22])
    (by simp [tys_22]) (by simp [tys_22]) (by simp [tys_22])
    (by intro j h1 h2; have h3 : j ≤ 21 := (by omega); interval_cases j <;> simp [tys_22, WA_22])
  have hb := phiRoot_le_dp (D := 22) (tys := tys_22) (SC := 10 ^ 12) (α := (357/1000000 : ℝ)) (t := (23/20 : ℝ))
    (VNI := 5760752252) (by norm_num) (by norm_num) cs hcap (by rw [hσ]; exact ht) hna
    (by rw [hσ]; exact hn) 491 (by omega)
  rw [hlen] at hb
  have hlt := log_le_of_taylor (x := (23/20 : ℝ)) (c := (1397621/10000000 : ℝ)) (a := (1397621/10000000 : ℝ)) (by norm_num)
    (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
  have hc := check_22
  rw [List.all_eq_true] at hc
  have hN := hc (bsizeList cs) (List.mem_range'_1.mpr ⟨h1, by omega⟩)
  simp only [decide_eq_true_eq] at hN
  have hNR : (((9327317392 : ℤ) + 5760752252 + (dpRow tys_22 491 21).getD (bsizeList cs - 3) NEGI
      - 357000000 * (bsizeList cs : ℤ) : ℤ) : ℝ) < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) := by exact_mod_cast hN
  push_cast at hNR
  have hNn : (0:ℝ) ≤ (bsizeList cs : ℝ) := Nat.cast_nonneg _
  have hCI : Real.log (23/20 : ℝ) + 1 / (23/20 : ℝ) - 1 ≤ (9327317392 : ℝ) / 10 ^ 12 := by
    have : (1397621/10000000 : ℝ) + 1 / (23/20 : ℝ) - 1 ≤ (9327317392 : ℝ) / 10 ^ 12 := by norm_num
    linarith
  have hal : (357000000 : ℝ) / 10 ^ 12 ≤ (357/1000000 : ℝ) := by norm_num
  have hmul : (357/1000000 : ℝ) * (bsizeList cs : ℝ) ≥ (357000000 : ℝ) / 10 ^ 12 * (bsizeList cs : ℝ) :=
    mul_le_mul_of_nonneg_right hal hNn
  have hNR' : (((9327317392 : ℝ) + 5760752252 + (((dpRow tys_22 491 21).getD (bsizeList cs - 3) NEGI : ℤ) : ℝ)
      - 357000000 * (bsizeList cs : ℝ))) / 10 ^ 12 < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 :=
    div_lt_div_of_pos_right (by linarith) (by norm_num)
  linarith

end BGSCL
end R3Cert
