/- Generated by proof/verification/finite_cert/gen_mid_lean.py: credited rate cells, cap D = 5. -/
import R3Cert.BGSpiderMid

namespace R3Cert
namespace BGSCL

theorem mcell_5_1 (cs : List Branch) (hlen : cs.length = 1) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 5)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (333/250000 : ℝ)
      + kapF (1/125 : ℝ) (3/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (333/250000 : ℝ) (1/125 : ℝ) (3/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_oneK (D := 5) (by norm_num) (by norm_num) (α := (333/250000 : ℝ)) (k1 := (1/125 : ℝ)) (k2 := (3/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (71/150 : ℝ)) (ℓ := (160419/27500000 : ℝ))
    (u := (26434394511527/109329990000000 : ℝ)) (by norm_num)
    (by
      have e : (1 + (71/150 : ℝ) / ((1:ℝ) + 1)) = (371/300 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (371/300 : ℝ) ^ 11 * (64 / 621)) (c := (160419/2500000 : ℝ)) (a := (160419/2500000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by intro j h1 h2; have h3 : j ≤ 4 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold Nb1K; simp only [max_le_iff]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_5_2 (cs : List Branch) (hlen : cs.length = 2) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 5)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (333/250000 : ℝ)
      + kapF (1/125 : ℝ) (3/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (333/250000 : ℝ) (1/125 : ℝ) (3/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 5) (K := 2) (by norm_num) (by norm_num) (α := (333/250000 : ℝ)) (k1 := (1/125 : ℝ)) (k2 := (3/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (121/150 : ℝ))
    (ℓ := (157779/5000000 : ℝ)) (umax := (5183233753/62810000000 : ℝ)) (unc := (263645391041/3580170000000 : ℝ)) (ρm := (9/928 : ℝ))
    (km := (3/400 : ℝ)) (by norm_num)
    (by
      have e : (1 + (121/150 : ℝ) / ((((2:ℕ):ℝ)) + 1)) = (571/450 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (571/450 : ℝ) ^ 11 * (64 / 621)) (c := (1735569/5000000 : ℝ)) (a := (1735569/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 4 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len2_le (D := 5) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_5_3 (cs : List Branch) (hlen : cs.length = 3) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 5)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (333/250000 : ℝ)
      + kapF (1/125 : ℝ) (3/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (333/250000 : ℝ) (1/125 : ℝ) (3/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 5) (K := 3) (by norm_num) (by norm_num) (α := (333/250000 : ℝ)) (k1 := (1/125 : ℝ)) (k2 := (3/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (107/100 : ℝ))
    (ℓ := (3350669/110000000 : ℝ)) (umax := (10156214603/167310000000 : ℝ)) (unc := (2594506921/55770000000 : ℝ)) (ρm := (1/1664 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (107/100 : ℝ) / ((((3:ℕ):ℝ)) + 1)) = (507/400 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (507/400 : ℝ) ^ 11 * (64 / 621)) (c := (3350669/10000000 : ℝ)) (a := (3350669/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 4 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len3_le (D := 5) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_5_4 (cs : List Branch) (hlen : cs.length = 4) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 5)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (333/250000 : ℝ)
      + kapF (1/125 : ℝ) (3/400 : ℝ) (1/200 : ℝ) (0 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (333/250000 : ℝ) (1/125 : ℝ) (3/400 : ℝ) (1/200 : ℝ) (0 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 5) (K := 4) (by norm_num) (by norm_num) (α := (333/250000 : ℝ)) (k1 := (1/125 : ℝ)) (k2 := (3/400 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (0 : ℝ)) (S0 := (29/25 : ℝ))
    (ℓ := (20527/10000000 : ℝ)) (umax := (113350103/2310000000 : ℝ)) (unc := (1946793/53200000 : ℝ)) (ρm := (0 : ℝ))
    (km := (0 : ℝ)) (by norm_num)
    (by
      have e : (1 + (29/25 : ℝ) / ((((4:ℕ):ℝ)) + 1)) = (154/125 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (154/125 : ℝ) ^ 11 * (64 / 621)) (c := (225797/10000000 : ℝ)) (a := (225797/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 4 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem rateCellKap_5 : RateCellKap 5 (333/250000 : ℝ) (1/125 : ℝ) (3/400 : ℝ) (1/200 : ℝ) (0 : ℝ) := by
  intro cs hlen hcap hna
  obtain ⟨K, hK⟩ : ∃ K, cs.length = K := ⟨_, rfl⟩
  have hK0 : 1 ≤ K := by
    rcases cs with _ | ⟨a, t⟩
    · exact absurd (Or.inr ⟨0, rfl⟩) hna
    · simp at hK; omega
  have hKD : K ≤ 4 := by omega
  interval_cases K
  · exact mcell_5_1 cs hK hcap hna
  · exact mcell_5_2 cs hK hcap hna
  · exact mcell_5_3 cs hK hcap hna
  · exact mcell_5_4 cs hK hcap hna

end BGSCL
end R3Cert
