/- Generated by proof/verification/finite_cert/gen_mid_lean.py: root certificate, root degree k = 18. -/
import R3Cert.BGSpiderMidCellsD18
import R3Cert.BGSpiderMidSpiders

namespace R3Cert
namespace BGSCL

def WA_18 : ℕ → ℤ
  | 1 => -38578846540
  | 2 => -6254660195
  | 3 => 5980814039
  | 4 => 10430429744
  | 5 => 11057997298
  | 6 => 9526947194
  | 7 => 6657641984
  | 8 => 2901494329
  | 9 => -1472586208
  | 10 => -6294444151
  | 11 => -11451140200
  | 12 => -16864766993
  | 13 => -22479828402
  | 14 => -28255697355
  | 15 => -34161994060
  | 16 => -40175387359
  | 17 => -46277581028
  | _ => 0

def tys_18 : List (ℕ × ℤ) := [(3, 7205778073), (1, -159057943442), (2, 8880414307), (3, -38578846540), (5, -6254660195), (7, 5980814039), (9, 10430429744), (11, 11057997298), (13, 9526947194), (15, 6657641984), (17, 2901494329), (19, -1472586208), (21, -6294444151), (23, -11451140200), (25, -16864766993), (27, -22479828402), (29, -28255697355), (31, -34161994060), (33, -40175387359), (35, -46277581028)]

theorem check_18 : (List.range' 149 342).all (fun N => decide
    ((12972227119 : ℤ) + 7205778073 + (dpRow tys_18 491 17).getD (N - 3) NEGI - 447000000 * (N : ℤ)
      < lowTabGet N)) = true := by decide +kernel

theorem midroot_18 (cs : List Branch) (hlen : cs.length = 18) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 18)
    (hna : ∃ c ∈ cs, ¬ IsAtom c) (h1 : 149 ≤ bsizeList cs) (h2 : bsizeList cs ≤ 490) :
    phiRoot cs < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 := by
  have hσ : (1 / ((cs.length : ℝ) * (59/50 : ℝ))) = 1 / (((18:ℕ):ℝ) * (59/50 : ℝ)) := by rw [hlen]
  obtain ⟨ht, hn⟩ := htype_of (D := 18) (by norm_num) (by norm_num) rateCellKap_18
    (SC := 10 ^ 12) (σ := 1 / (((18:ℕ):ℝ) * (59/50 : ℝ))) (by norm_num) (by positivity)
    (tys := tys_18) (VNI := 7205778073) (WL := -159057943442) (WC := 8880414307) (WA := WA_18)
    (by unfold NbK; simp only [max_le_iff]; norm_num) (by norm_num) (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 17 := (by omega); interval_cases j <;> norm_num [bjT, WA_18])
    (by simp [tys_18]) (by simp [tys_18]) (by simp [tys_18])
    (by intro j h1 h2; have h3 : j ≤ 17 := (by omega); interval_cases j <;> simp [tys_18, WA_18])
  have hb := phiRoot_le_dp (D := 18) (tys := tys_18) (SC := 10 ^ 12) (α := (447/1000000 : ℝ)) (t := (59/50 : ℝ))
    (VNI := 7205778073) (by norm_num) (by norm_num) cs hcap (by rw [hσ]; exact ht) hna
    (by rw [hσ]; exact hn) 491 (by omega)
  rw [hlen] at hb
  have hlt := log_le_of_taylor (x := (59/50 : ℝ)) (c := (827573/5000000 : ℝ)) (a := (827573/5000000 : ℝ)) (by norm_num)
    (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
  have hc := check_18
  rw [List.all_eq_true] at hc
  have hN := hc (bsizeList cs) (List.mem_range'_1.mpr ⟨h1, by omega⟩)
  simp only [decide_eq_true_eq] at hN
  have hNR : (((12972227119 : ℤ) + 7205778073 + (dpRow tys_18 491 17).getD (bsizeList cs - 3) NEGI
      - 447000000 * (bsizeList cs : ℤ) : ℤ) : ℝ) < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) := by exact_mod_cast hN
  push_cast at hNR
  have hNn : (0:ℝ) ≤ (bsizeList cs : ℝ) := Nat.cast_nonneg _
  have hCI : Real.log (59/50 : ℝ) + 1 / (59/50 : ℝ) - 1 ≤ (12972227119 : ℝ) / 10 ^ 12 := by
    have : (827573/5000000 : ℝ) + 1 / (59/50 : ℝ) - 1 ≤ (12972227119 : ℝ) / 10 ^ 12 := by norm_num
    linarith
  have hal : (447000000 : ℝ) / 10 ^ 12 ≤ (447/1000000 : ℝ) := by norm_num
  have hmul : (447/1000000 : ℝ) * (bsizeList cs : ℝ) ≥ (447000000 : ℝ) / 10 ^ 12 * (bsizeList cs : ℝ) :=
    mul_le_mul_of_nonneg_right hal hNn
  have hNR' : (((12972227119 : ℝ) + 7205778073 + (((dpRow tys_18 491 17).getD (bsizeList cs - 3) NEGI : ℤ) : ℝ)
      - 447000000 * (bsizeList cs : ℝ))) / 10 ^ 12 < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 :=
    div_lt_div_of_pos_right (by linarith) (by norm_num)
  linarith

end BGSCL
end R3Cert
