/- Generated by proof/verification/finite_cert/gen_mid_lean.py: root certificate, root degree k = 23. -/
import R3Cert.BGSpiderMidCellsD23
import R3Cert.BGSpiderMidSpiders

namespace R3Cert
namespace BGSCL

def WA_23 : ℕ → ℤ
  | 1 => -42615192903
  | 2 => -9107607880
  | 3 => 3581985736
  | 4 => 8217038979
  | 5 => 8901544058
  | 6 => 7356042581
  | 7 => 4428531515
  | 8 => 585425056
  | 9 => -3895520171
  | 10 => -8838593559
  | 11 => -14127191786
  | 12 => -19680892965
  | 13 => -25442417939
  | 14 => -31369840144
  | 15 => -37431810322
  | 16 => -43604259367
  | 17 => -49868319402
  | 18 => -56208671943
  | 19 => -62615073594
  | 20 => -69076860956
  | 21 => -75579083650
  | 22 => -82124700852
  | _ => 0

def tys_23 : List (ℕ × ℤ) := [(3, 5527544541), (1, -167924084956), (2, 5771700469), (3, -42615192903), (5, -9107607880), (7, 3581985736), (9, 8217038979), (11, 8901544058), (13, 7356042581), (15, 4428531515), (17, 585425056), (19, -3895520171), (21, -8838593559), (23, -14127191786), (25, -19680892965), (27, -25442417939), (29, -31369840144), (31, -37431810322), (33, -43604259367), (35, -49868319402), (37, -56208671943), (39, -62615073594), (41, -69076860956), (43, -75579083650), (45, -82124700852)]

theorem check_23 : (List.range' 149 342).all (fun N => decide
    ((7690068723 : ℤ) + 5527544541 + (dpRow tys_23 491 22).getD (N - 3) NEGI - 355000000 * (N : ℤ)
      < lowTabGet N)) = true := by decide +kernel

theorem midroot_23 (cs : List Branch) (hlen : cs.length = 23) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 23)
    (hna : ∃ c ∈ cs, ¬ IsAtom c) (h1 : 149 ≤ bsizeList cs) (h2 : bsizeList cs ≤ 490) :
    phiRoot cs < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 := by
  have hσ : (1 / ((cs.length : ℝ) * (227/200 : ℝ))) = 1 / (((23:ℕ):ℝ) * (227/200 : ℝ)) := by rw [hlen]
  obtain ⟨ht, hn⟩ := htype_of (D := 23) (by norm_num) (by norm_num) rateCellKap_23
    (SC := 10 ^ 12) (σ := 1 / (((23:ℕ):ℝ) * (227/200 : ℝ))) (by norm_num) (by positivity)
    (tys := tys_23) (VNI := 5527544541) (WL := -167924084956) (WC := 5771700469) (WA := WA_23)
    (by unfold NbK; simp only [max_le_iff]; norm_num) (by norm_num) (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 22 := (by omega); interval_cases j <;> norm_num [bjT, WA_23])
    (by simp [tys_23]) (by simp [tys_23]) (by simp [tys_23])
    (by intro j h1 h2; have h3 : j ≤ 22 := (by omega); interval_cases j <;> simp [tys_23, WA_23])
  have hb := phiRoot_le_dp (D := 23) (tys := tys_23) (SC := 10 ^ 12) (α := (71/200000 : ℝ)) (t := (227/200 : ℝ))
    (VNI := 5527544541) (by norm_num) (by norm_num) cs hcap (by rw [hσ]; exact ht) hna
    (by rw [hσ]; exact hn) 491 (by omega)
  rw [hlen] at hb
  have hlt := log_le_of_taylor (x := (227/200 : ℝ)) (c := (158291/1250000 : ℝ)) (a := (158291/1250000 : ℝ)) (by norm_num)
    (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
  have hc := check_23
  rw [List.all_eq_true] at hc
  have hN := hc (bsizeList cs) (List.mem_range'_1.mpr ⟨h1, by omega⟩)
  simp only [decide_eq_true_eq] at hN
  have hNR : (((7690068723 : ℤ) + 5527544541 + (dpRow tys_23 491 22).getD (bsizeList cs - 3) NEGI
      - 355000000 * (bsizeList cs : ℤ) : ℤ) : ℝ) < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) := by exact_mod_cast hN
  push_cast at hNR
  have hNn : (0:ℝ) ≤ (bsizeList cs : ℝ) := Nat.cast_nonneg _
  have hCI : Real.log (227/200 : ℝ) + 1 / (227/200 : ℝ) - 1 ≤ (7690068723 : ℝ) / 10 ^ 12 := by
    have : (158291/1250000 : ℝ) + 1 / (227/200 : ℝ) - 1 ≤ (7690068723 : ℝ) / 10 ^ 12 := by norm_num
    linarith
  have hal : (355000000 : ℝ) / 10 ^ 12 ≤ (71/200000 : ℝ) := by norm_num
  have hmul : (71/200000 : ℝ) * (bsizeList cs : ℝ) ≥ (355000000 : ℝ) / 10 ^ 12 * (bsizeList cs : ℝ) :=
    mul_le_mul_of_nonneg_right hal hNn
  have hNR' : (((7690068723 : ℝ) + 5527544541 + (((dpRow tys_23 491 22).getD (bsizeList cs - 3) NEGI : ℤ) : ℝ)
      - 355000000 * (bsizeList cs : ℝ))) / 10 ^ 12 < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 :=
    div_lt_div_of_pos_right (by linarith) (by norm_num)
  linarith

end BGSCL
end R3Cert
