-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 343 <= n <= 349, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 343. -/
def T343 : ℕ × ℕ := (61923786598800056612328054656926974310151950403315059214713359461549353667961659654514920547603025426987172089723934165484, 11355752827853285520127651596677948970493608029094732030292361598984205009505814891724800000)
theorem tabV_343 : tabV 343 = T343 := by decide +kernel
theorem bal_343_0 : (List.range' 0 39).all (balRow 343 T343) = true := by decide +kernel
theorem bal_343_1 : (List.range' 39 57).all (balRow 343 T343) = true := by decide +kernel
theorem bal_343_2 : (List.range' 96 76).all (balRow 343 T343) = true := by decide +kernel
theorem small_343 : checkSmallFast 343 T343 = true := by decide +kernel
theorem checkN_343 : checkN 343 = true := by
  have h : (List.range' 0 39).all (balRow 343 T343) = true := bal_343_0
  have h : (List.range' 0 96).all (balRow 343 T343) = true := all_range'_append (by decide) (by decide) h bal_343_1
  have h : (List.range' 0 172).all (balRow 343 T343) = true := all_range'_append (by decide) (by decide) h bal_343_2
  exact checkN_of_parts tabV_343 (by decide +kernel) (by decide) h small_343

/-- The table value at n = 344. -/
def T344 : ℕ × ℕ := (33782757595020351367243352464645131634817897871917055395141815730126622952337052258439540836929686043340532808956960665750, 5042528019920266094836641653426736228741881641955320544752391742956093594578956842572972032)
theorem tabV_344 : tabV 344 = T344 := by decide +kernel
theorem bal_344_0 : (List.range' 0 39).all (balRow 344 T344) = true := by decide +kernel
theorem bal_344_1 : (List.range' 39 57).all (balRow 344 T344) = true := by decide +kernel
theorem bal_344_2 : (List.range' 96 76).all (balRow 344 T344) = true := by decide +kernel
theorem small_344 : checkSmallFast 344 T344 = true := by decide +kernel
theorem checkN_344 : checkN 344 = true := by
  have h : (List.range' 0 39).all (balRow 344 T344) = true := bal_344_0
  have h : (List.range' 0 96).all (balRow 344 T344) = true := all_range'_append (by decide) (by decide) h bal_344_1
  have h : (List.range' 0 172).all (balRow 344 T344) = true := all_range'_append (by decide) (by decide) h bal_344_2
  exact checkN_of_parts tabV_344 (by decide +kernel) (by decide) h small_344

/-- The table value at n = 345. -/
def T345 : ℕ × ℕ := (224711055886821491573607527862020064285825439700066625133290955998635227705494027066247900554551219968527501377057189938128, 27253806786847885248306363832027077529184659269827356872701667837562092022813955740139520000)
theorem tabV_345 : tabV 345 = T345 := by decide +kernel
theorem bal_345_0 : (List.range' 0 39).all (balRow 345 T345) = true := by decide +kernel
theorem bal_345_1 : (List.range' 39 56).all (balRow 345 T345) = true := by decide +kernel
theorem bal_345_2 : (List.range' 95 78).all (balRow 345 T345) = true := by decide +kernel
theorem small_345 : checkSmallFast 345 T345 = true := by decide +kernel
theorem checkN_345 : checkN 345 = true := by
  have h : (List.range' 0 39).all (balRow 345 T345) = true := bal_345_0
  have h : (List.range' 0 95).all (balRow 345 T345) = true := all_range'_append (by decide) (by decide) h bal_345_1
  have h : (List.range' 0 173).all (balRow 345 T345) = true := all_range'_append (by decide) (by decide) h bal_345_2
  exact checkN_of_parts tabV_345 (by decide +kernel) (by decide) h small_345

/-- The table value at n = 346. -/
def T346 : ℕ × ℕ := (2057766274061479786793034154353142758037461384090771895514577815760897092143021321568304864864325847009938708975386931211370, 203309376800758692580410428976981508260790508333401777886093713523480232917584576512000000000)
theorem tabV_346 : tabV 346 = T346 := by decide +kernel
theorem bal_346_0 : (List.range' 0 38).all (balRow 346 T346) = true := by decide +kernel
theorem bal_346_1 : (List.range' 38 55).all (balRow 346 T346) = true := by decide +kernel
theorem bal_346_2 : (List.range' 93 80).all (balRow 346 T346) = true := by decide +kernel
theorem small_346 : checkSmallFast 346 T346 = true := by decide +kernel
theorem checkN_346 : checkN 346 = true := by
  have h : (List.range' 0 38).all (balRow 346 T346) = true := bal_346_0
  have h : (List.range' 0 93).all (balRow 346 T346) = true := all_range'_append (by decide) (by decide) h bal_346_1
  have h : (List.range' 0 173).all (balRow 346 T346) = true := all_range'_append (by decide) (by decide) h bal_346_2
  exact checkN_of_parts tabV_346 (by decide +kernel) (by decide) h small_346

/-- The table value at n = 347. -/
def T347 : ℕ × ℕ := (815438339441437344528268891503011866667038412807179208249968371833753723630581377707912627498324916065355075599635184088372, 65409136288434924595935273196864986070043182247585656494484002810149020854753493776334848000)
theorem tabV_347 : tabV 347 = T347 := by decide +kernel
theorem bal_347_0 : (List.range' 0 38).all (balRow 347 T347) = true := by decide +kernel
theorem bal_347_1 : (List.range' 38 55).all (balRow 347 T347) = true := by decide +kernel
theorem bal_347_2 : (List.range' 93 81).all (balRow 347 T347) = true := by decide +kernel
theorem small_347 : checkSmallFast 347 T347 = true := by decide +kernel
theorem checkN_347 : checkN 347 = true := by
  have h : (List.range' 0 38).all (balRow 347 T347) = true := bal_347_0
  have h : (List.range' 0 93).all (balRow 347 T347) = true := all_range'_append (by decide) (by decide) h bal_347_1
  have h : (List.range' 0 174).all (balRow 347 T347) = true := all_range'_append (by decide) (by decide) h bal_347_2
  exact checkN_of_parts tabV_347 (by decide +kernel) (by decide) h small_347

/-- The table value at n = 348. -/
def T348 : ℕ × ℕ := (7467476006229032497913403285393103086354861068559328235166988179789140593573646334213147820677763403282848300249235857347186, 487942504321820862192985029544755619825897220000164266926624912456352559002202983628800000000)
theorem tabV_348 : tabV 348 = T348 := by decide +kernel
theorem bal_348_0 : (List.range' 0 38).all (balRow 348 T348) = true := by decide +kernel
theorem bal_348_1 : (List.range' 38 55).all (balRow 348 T348) = true := by decide +kernel
theorem bal_348_2 : (List.range' 93 81).all (balRow 348 T348) = true := by decide +kernel
theorem small_348 : checkSmallFast 348 T348 = true := by decide +kernel
theorem checkN_348 : checkN 348 = true := by
  have h : (List.range' 0 38).all (balRow 348 T348) = true := bal_348_0
  have h : (List.range' 0 93).all (balRow 348 T348) = true := all_range'_append (by decide) (by decide) h bal_348_1
  have h : (List.range' 0 174).all (balRow 348 T348) = true := all_range'_append (by decide) (by decide) h bal_348_2
  exact checkN_of_parts tabV_348 (by decide +kernel) (by decide) h small_348

/-- The table value at n = 349. -/
def T349 : ℕ × ℕ := (2959085841934325750612674773877616588188808310161791362248805621713573252779854042902328683546785517044879706831230391646216, 156981927092243819030244655672475966568103637394205575586761606744357650051408385063203635200)
theorem tabV_349 : tabV 349 = T349 := by decide +kernel
theorem bal_349_0 : (List.range' 0 38).all (balRow 349 T349) = true := by decide +kernel
theorem bal_349_1 : (List.range' 38 54).all (balRow 349 T349) = true := by decide +kernel
theorem bal_349_2 : (List.range' 92 83).all (balRow 349 T349) = true := by decide +kernel
theorem small_349 : checkSmallFast 349 T349 = true := by decide +kernel
theorem checkN_349 : checkN 349 = true := by
  have h : (List.range' 0 38).all (balRow 349 T349) = true := bal_349_0
  have h : (List.range' 0 92).all (balRow 349 T349) = true := all_range'_append (by decide) (by decide) h bal_349_1
  have h : (List.range' 0 175).all (balRow 349 T349) = true := all_range'_append (by decide) (by decide) h bal_349_2
  exact checkN_of_parts tabV_349 (by decide +kernel) (by decide) h small_349

end Sweep

theorem chunk_343_349 : (List.range' 343 7).all checkN = true := by
  have h : (List.range' 343 1).all checkN = true := all_range'_one Sweep.checkN_343
  have h : (List.range' 343 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_344
  have h : (List.range' 343 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_345
  have h : (List.range' 343 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_346
  have h : (List.range' 343 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_347
  have h : (List.range' 343 6).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_348
  have h : (List.range' 343 7).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_349
  exact h

end BGSpiderTable
end R3Cert
