-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 302 <= n <= 310, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 302. -/
def T302 : ℕ × ℕ := (1854973571683967170921039712692481870973798222866405932921002651127166241717259093044382752697042778471068818, 1623123379786630367990772171222326585415061043149766454608186284500320256000000000)
theorem tabV_302 : tabV 302 = T302 := by decide +kernel
theorem bal_302_0 : (List.range' 0 46).all (balRow 302 T302) = true := by decide +kernel
theorem bal_302_1 : (List.range' 46 105).all (balRow 302 T302) = true := by decide +kernel
theorem small_302 : checkSmallFast 302 T302 = true := by decide +kernel
theorem checkN_302 : checkN 302 = true := by
  have h : (List.range' 0 46).all (balRow 302 T302) = true := bal_302_0
  have h : (List.range' 0 151).all (balRow 302 T302) = true := all_range'_append (by decide) (by decide) h bal_302_1
  exact checkN_of_parts tabV_302 (by decide +kernel) (by decide) h small_302

/-- The table value at n = 303. -/
def T303 : ℕ × ℕ := (731482074005406423416656135946089339480801826039888468729373156293884041408356196825633759669868323606255324, 519943955470982557074971723469822120885333937733020469890841281253054865211392000)
theorem tabV_303 : tabV 303 = T303 := by decide +kernel
theorem bal_303_0 : (List.range' 0 46).all (balRow 303 T303) = true := by decide +kernel
theorem bal_303_1 : (List.range' 46 106).all (balRow 303 T303) = true := by decide +kernel
theorem small_303 : checkSmallFast 303 T303 = true := by decide +kernel
theorem checkN_303 : checkN 303 = true := by
  have h : (List.range' 0 46).all (balRow 303 T303) = true := bal_303_0
  have h : (List.range' 0 152).all (balRow 303 T303) = true := all_range'_append (by decide) (by decide) h bal_303_1
  exact checkN_of_parts tabV_303 (by decide +kernel) (by decide) h small_303

/-- The table value at n = 304. -/
def T304 : ℕ × ℕ := (6730882458475259596102051431251931384522305302328464732964135543214352866131850361179889865662127490014705994, 3895496111487912883177853210933583804996146503559439491059647082800768614400000000)
theorem tabV_304 : tabV 304 = T304 := by decide +kernel
theorem bal_304_0 : (List.range' 0 46).all (balRow 304 T304) = true := by decide +kernel
theorem bal_304_1 : (List.range' 46 106).all (balRow 304 T304) = true := by decide +kernel
theorem small_304 : checkSmallFast 304 T304 = true := by decide +kernel
theorem checkN_304 : checkN 304 = true := by
  have h : (List.range' 0 46).all (balRow 304 T304) = true := bal_304_0
  have h : (List.range' 0 152).all (balRow 304 T304) = true := all_range'_append (by decide) (by decide) h bal_304_1
  exact checkN_of_parts tabV_304 (by decide +kernel) (by decide) h small_304

/-- The table value at n = 305. -/
def T305 : ℕ × ℕ := (2654136283461755525015643480474405136631750933656429527147994691675481427007418285799579170544126534924365408, 1247865493130358136979932136327573090124801450559249127738019075007331676507340800)
theorem tabV_305 : tabV 305 = T305 := by decide +kernel
theorem bal_305_0 : (List.range' 0 46).all (balRow 305 T305) = true := by decide +kernel
theorem bal_305_1 : (List.range' 46 107).all (balRow 305 T305) = true := by decide +kernel
theorem small_305 : checkSmallFast 305 T305 = true := by decide +kernel
theorem checkN_305 : checkN 305 = true := by
  have h : (List.range' 0 46).all (balRow 305 T305) = true := bal_305_0
  have h : (List.range' 0 153).all (balRow 305 T305) = true := all_range'_append (by decide) (by decide) h bal_305_1
  exact checkN_of_parts tabV_305 (by decide +kernel) (by decide) h small_305

/-- The table value at n = 306. -/
def T306 : ℕ × ℕ := (24423392330567210416134373353500437403078202669358104939598531225184472958952468434984390421538719142708588570, 9349190667570990919626847706240601131990751608542654778543152998721844674560000000)
theorem tabV_306 : tabV 306 = T306 := by decide +kernel
theorem bal_306_0 : (List.range' 0 45).all (balRow 306 T306) = true := by decide +kernel
theorem bal_306_1 : (List.range' 45 108).all (balRow 306 T306) = true := by decide +kernel
theorem small_306 : checkSmallFast 306 T306 = true := by decide +kernel
theorem checkN_306 : checkN 306 = true := by
  have h : (List.range' 0 45).all (balRow 306 T306) = true := bal_306_0
  have h : (List.range' 0 153).all (balRow 306 T306) = true := all_range'_append (by decide) (by decide) h bal_306_1
  exact checkN_of_parts tabV_306 (by decide +kernel) (by decide) h small_306

/-- The table value at n = 307. -/
def T307 : ℕ × ℕ := (9630357841819897519956557735635897293574386299920357951693896078830832078859465075566909294677165334854029092, 2994877183512859528751837127186175416299523481342197906571245780017596023617617920)
theorem tabV_307 : tabV 307 = T307 := by decide +kernel
theorem bal_307_0 : (List.range' 0 45).all (balRow 307 T307) = true := by decide +kernel
theorem bal_307_1 : (List.range' 45 109).all (balRow 307 T307) = true := by decide +kernel
theorem small_307 : checkSmallFast 307 T307 = true := by decide +kernel
theorem checkN_307 : checkN 307 = true := by
  have h : (List.range' 0 45).all (balRow 307 T307) = true := bal_307_0
  have h : (List.range' 0 154).all (balRow 307 T307) = true := all_range'_append (by decide) (by decide) h bal_307_1
  exact checkN_of_parts tabV_307 (by decide +kernel) (by decide) h small_307

/-- The table value at n = 308. -/
def T308 : ℕ × ℕ := (88621615805946024304882160855090586008754437270557148360069527842632005824708123731167911453897874272082836546, 22438057602170378207104434494977442716777803860502371468503567196932427218944000000)
theorem tabV_308 : tabV 308 = T308 := by decide +kernel
theorem bal_308_0 : (List.range' 0 45).all (balRow 308 T308) = true := by decide +kernel
theorem bal_308_1 : (List.range' 45 109).all (balRow 308 T308) = true := by decide +kernel
theorem small_308 : checkSmallFast 308 T308 = true := by decide +kernel
theorem checkN_308 : checkN 308 = true := by
  have h : (List.range' 0 45).all (balRow 308 T308) = true := bal_308_0
  have h : (List.range' 0 154).all (balRow 308 T308) = true := all_range'_append (by decide) (by decide) h bal_308_1
  exact checkN_of_parts tabV_308 (by decide +kernel) (by decide) h small_308

/-- The table value at n = 309. -/
def T309 : ℕ × ℕ := (49655969707484988708794084538863443053317308127690446771530019736687828428816791394518920100807611755464898008, 10214107446928068287532581360087587735589953767946022333990354028691590648969560064)
theorem tabV_309 : tabV 309 = T309 := by decide +kernel
theorem bal_309_0 : (List.range' 0 45).all (balRow 309 T309) = true := by decide +kernel
theorem bal_309_1 : (List.range' 45 100).all (balRow 309 T309) = true := by decide +kernel
theorem bal_309_2 : (List.range' 145 10).all (balRow 309 T309) = true := by decide +kernel
theorem small_309 : checkSmallFast 309 T309 = true := by decide +kernel
theorem checkN_309 : checkN 309 = true := by
  have h : (List.range' 0 45).all (balRow 309 T309) = true := bal_309_0
  have h : (List.range' 0 145).all (balRow 309 T309) = true := all_range'_append (by decide) (by decide) h bal_309_1
  have h : (List.range' 0 155).all (balRow 309 T309) = true := all_range'_append (by decide) (by decide) h bal_309_2
  exact checkN_of_parts tabV_309 (by decide +kernel) (by decide) h small_309

/-- The table value at n = 310. -/
def T310 : ℕ × ℕ := (321568159992686944421565856581805911465093660982235194965855110360880452949617723557234296496327934911262069922, 53851338245208907697050642787945862520266729265205691524408561272637825325465600000)
theorem tabV_310 : tabV 310 = T310 := by decide +kernel
theorem bal_310_0 : (List.range' 0 45).all (balRow 310 T310) = true := by decide +kernel
theorem bal_310_1 : (List.range' 45 96).all (balRow 310 T310) = true := by decide +kernel
theorem bal_310_2 : (List.range' 141 14).all (balRow 310 T310) = true := by decide +kernel
theorem small_310 : checkSmallFast 310 T310 = true := by decide +kernel
theorem checkN_310 : checkN 310 = true := by
  have h : (List.range' 0 45).all (balRow 310 T310) = true := bal_310_0
  have h : (List.range' 0 141).all (balRow 310 T310) = true := all_range'_append (by decide) (by decide) h bal_310_1
  have h : (List.range' 0 155).all (balRow 310 T310) = true := all_range'_append (by decide) (by decide) h bal_310_2
  exact checkN_of_parts tabV_310 (by decide +kernel) (by decide) h small_310

end Sweep

theorem chunk_302_310 : (List.range' 302 9).all checkN = true := by
  have h : (List.range' 302 1).all checkN = true := all_range'_one Sweep.checkN_302
  have h : (List.range' 302 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_303
  have h : (List.range' 302 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_304
  have h : (List.range' 302 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_305
  have h : (List.range' 302 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_306
  have h : (List.range' 302 6).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_307
  have h : (List.range' 302 7).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_308
  have h : (List.range' 302 8).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_309
  have h : (List.range' 302 9).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_310
  exact h

end BGSpiderTable
end R3Cert
