/-
  R3Cert.BGSpiderTableAll -- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
  The spider-family optimum for every 4 <= n <= 491: the table spider `tab n` has n vertices and
  maximizes F.  89 kernel-checked chunks.
-/
import R3Cert.BGSpiderTableChunk_4_105
import R3Cert.BGSpiderTableChunk_106_133
import R3Cert.BGSpiderTableChunk_134_152
import R3Cert.BGSpiderTableChunk_153_168
import R3Cert.BGSpiderTableChunk_169_181
import R3Cert.BGSpiderTableChunk_182_193
import R3Cert.BGSpiderTableChunk_194_203
import R3Cert.BGSpiderTableChunk_204_212
import R3Cert.BGSpiderTableChunk_213_221
import R3Cert.BGSpiderTableChunk_222_229
import R3Cert.BGSpiderTableChunk_230_237
import R3Cert.BGSpiderTableChunk_238_244
import R3Cert.BGSpiderTableChunk_245_251
import R3Cert.BGSpiderTableChunk_252_257
import R3Cert.BGSpiderTableChunk_258_263
import R3Cert.BGSpiderTableChunk_264_269
import R3Cert.BGSpiderTableChunk_270_275
import R3Cert.BGSpiderTableChunk_276_280
import R3Cert.BGSpiderTableChunk_281_285
import R3Cert.BGSpiderTableChunk_286_290
import R3Cert.BGSpiderTableChunk_291_295
import R3Cert.BGSpiderTableChunk_296_300
import R3Cert.BGSpiderTableChunk_301_305
import R3Cert.BGSpiderTableChunk_306_310
import R3Cert.BGSpiderTableChunk_311_314
import R3Cert.BGSpiderTableChunk_315_318
import R3Cert.BGSpiderTableChunk_319_322
import R3Cert.BGSpiderTableChunk_323_326
import R3Cert.BGSpiderTableChunk_327_330
import R3Cert.BGSpiderTableChunk_331_334
import R3Cert.BGSpiderTableChunk_335_338
import R3Cert.BGSpiderTableChunk_339_342
import R3Cert.BGSpiderTableChunk_343_346
import R3Cert.BGSpiderTableChunk_347_350
import R3Cert.BGSpiderTableChunk_351_354
import R3Cert.BGSpiderTableChunk_355_358
import R3Cert.BGSpiderTableChunk_359_361
import R3Cert.BGSpiderTableChunk_362_364
import R3Cert.BGSpiderTableChunk_365_367
import R3Cert.BGSpiderTableChunk_368_370
import R3Cert.BGSpiderTableChunk_371_373
import R3Cert.BGSpiderTableChunk_374_376
import R3Cert.BGSpiderTableChunk_377_379
import R3Cert.BGSpiderTableChunk_380_382
import R3Cert.BGSpiderTableChunk_383_385
import R3Cert.BGSpiderTableChunk_386_388
import R3Cert.BGSpiderTableChunk_389_391
import R3Cert.BGSpiderTableChunk_392_394
import R3Cert.BGSpiderTableChunk_395_397
import R3Cert.BGSpiderTableChunk_398_400
import R3Cert.BGSpiderTableChunk_401_403
import R3Cert.BGSpiderTableChunk_404_406
import R3Cert.BGSpiderTableChunk_407_409
import R3Cert.BGSpiderTableChunk_410_412
import R3Cert.BGSpiderTableChunk_413_415
import R3Cert.BGSpiderTableChunk_416_418
import R3Cert.BGSpiderTableChunk_419_421
import R3Cert.BGSpiderTableChunk_422_424
import R3Cert.BGSpiderTableChunk_425_427
import R3Cert.BGSpiderTableChunk_428_430
import R3Cert.BGSpiderTableChunk_431_433
import R3Cert.BGSpiderTableChunk_434_436
import R3Cert.BGSpiderTableChunk_437_439
import R3Cert.BGSpiderTableChunk_440_441
import R3Cert.BGSpiderTableChunk_442_443
import R3Cert.BGSpiderTableChunk_444_445
import R3Cert.BGSpiderTableChunk_446_447
import R3Cert.BGSpiderTableChunk_448_449
import R3Cert.BGSpiderTableChunk_450_451
import R3Cert.BGSpiderTableChunk_452_453
import R3Cert.BGSpiderTableChunk_454_455
import R3Cert.BGSpiderTableChunk_456_457
import R3Cert.BGSpiderTableChunk_458_459
import R3Cert.BGSpiderTableChunk_460_461
import R3Cert.BGSpiderTableChunk_462_463
import R3Cert.BGSpiderTableChunk_464_465
import R3Cert.BGSpiderTableChunk_466_467
import R3Cert.BGSpiderTableChunk_468_469
import R3Cert.BGSpiderTableChunk_470_471
import R3Cert.BGSpiderTableChunk_472_473
import R3Cert.BGSpiderTableChunk_474_475
import R3Cert.BGSpiderTableChunk_476_477
import R3Cert.BGSpiderTableChunk_478_479
import R3Cert.BGSpiderTableChunk_480_481
import R3Cert.BGSpiderTableChunk_482_483
import R3Cert.BGSpiderTableChunk_484_485
import R3Cert.BGSpiderTableChunk_486_487
import R3Cert.BGSpiderTableChunk_488_489
import R3Cert.BGSpiderTableChunk_490_491

namespace R3Cert
namespace BGSpiderTable

open BGSpiderOpt

theorem checkN_all (n : ℕ) (h4 : 4 ≤ n) (hN : n ≤ 491) : checkN n = true := by
  rcases Nat.lt_or_ge n 106 with h0 | h0
  · exact checkN_of_all chunk_4_105 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 134 with h1 | h1
  · exact checkN_of_all chunk_106_133 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 153 with h2 | h2
  · exact checkN_of_all chunk_134_152 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 169 with h3 | h3
  · exact checkN_of_all chunk_153_168 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 182 with h4 | h4
  · exact checkN_of_all chunk_169_181 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 194 with h5 | h5
  · exact checkN_of_all chunk_182_193 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 204 with h6 | h6
  · exact checkN_of_all chunk_194_203 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 213 with h7 | h7
  · exact checkN_of_all chunk_204_212 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 222 with h8 | h8
  · exact checkN_of_all chunk_213_221 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 230 with h9 | h9
  · exact checkN_of_all chunk_222_229 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 238 with h10 | h10
  · exact checkN_of_all chunk_230_237 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 245 with h11 | h11
  · exact checkN_of_all chunk_238_244 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 252 with h12 | h12
  · exact checkN_of_all chunk_245_251 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 258 with h13 | h13
  · exact checkN_of_all chunk_252_257 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 264 with h14 | h14
  · exact checkN_of_all chunk_258_263 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 270 with h15 | h15
  · exact checkN_of_all chunk_264_269 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 276 with h16 | h16
  · exact checkN_of_all chunk_270_275 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 281 with h17 | h17
  · exact checkN_of_all chunk_276_280 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 286 with h18 | h18
  · exact checkN_of_all chunk_281_285 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 291 with h19 | h19
  · exact checkN_of_all chunk_286_290 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 296 with h20 | h20
  · exact checkN_of_all chunk_291_295 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 301 with h21 | h21
  · exact checkN_of_all chunk_296_300 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 306 with h22 | h22
  · exact checkN_of_all chunk_301_305 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 311 with h23 | h23
  · exact checkN_of_all chunk_306_310 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 315 with h24 | h24
  · exact checkN_of_all chunk_311_314 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 319 with h25 | h25
  · exact checkN_of_all chunk_315_318 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 323 with h26 | h26
  · exact checkN_of_all chunk_319_322 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 327 with h27 | h27
  · exact checkN_of_all chunk_323_326 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 331 with h28 | h28
  · exact checkN_of_all chunk_327_330 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 335 with h29 | h29
  · exact checkN_of_all chunk_331_334 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 339 with h30 | h30
  · exact checkN_of_all chunk_335_338 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 343 with h31 | h31
  · exact checkN_of_all chunk_339_342 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 347 with h32 | h32
  · exact checkN_of_all chunk_343_346 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 351 with h33 | h33
  · exact checkN_of_all chunk_347_350 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 355 with h34 | h34
  · exact checkN_of_all chunk_351_354 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 359 with h35 | h35
  · exact checkN_of_all chunk_355_358 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 362 with h36 | h36
  · exact checkN_of_all chunk_359_361 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 365 with h37 | h37
  · exact checkN_of_all chunk_362_364 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 368 with h38 | h38
  · exact checkN_of_all chunk_365_367 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 371 with h39 | h39
  · exact checkN_of_all chunk_368_370 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 374 with h40 | h40
  · exact checkN_of_all chunk_371_373 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 377 with h41 | h41
  · exact checkN_of_all chunk_374_376 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 380 with h42 | h42
  · exact checkN_of_all chunk_377_379 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 383 with h43 | h43
  · exact checkN_of_all chunk_380_382 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 386 with h44 | h44
  · exact checkN_of_all chunk_383_385 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 389 with h45 | h45
  · exact checkN_of_all chunk_386_388 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 392 with h46 | h46
  · exact checkN_of_all chunk_389_391 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 395 with h47 | h47
  · exact checkN_of_all chunk_392_394 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 398 with h48 | h48
  · exact checkN_of_all chunk_395_397 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 401 with h49 | h49
  · exact checkN_of_all chunk_398_400 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 404 with h50 | h50
  · exact checkN_of_all chunk_401_403 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 407 with h51 | h51
  · exact checkN_of_all chunk_404_406 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 410 with h52 | h52
  · exact checkN_of_all chunk_407_409 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 413 with h53 | h53
  · exact checkN_of_all chunk_410_412 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 416 with h54 | h54
  · exact checkN_of_all chunk_413_415 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 419 with h55 | h55
  · exact checkN_of_all chunk_416_418 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 422 with h56 | h56
  · exact checkN_of_all chunk_419_421 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 425 with h57 | h57
  · exact checkN_of_all chunk_422_424 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 428 with h58 | h58
  · exact checkN_of_all chunk_425_427 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 431 with h59 | h59
  · exact checkN_of_all chunk_428_430 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 434 with h60 | h60
  · exact checkN_of_all chunk_431_433 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 437 with h61 | h61
  · exact checkN_of_all chunk_434_436 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 440 with h62 | h62
  · exact checkN_of_all chunk_437_439 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 442 with h63 | h63
  · exact checkN_of_all chunk_440_441 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 444 with h64 | h64
  · exact checkN_of_all chunk_442_443 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 446 with h65 | h65
  · exact checkN_of_all chunk_444_445 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 448 with h66 | h66
  · exact checkN_of_all chunk_446_447 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 450 with h67 | h67
  · exact checkN_of_all chunk_448_449 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 452 with h68 | h68
  · exact checkN_of_all chunk_450_451 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 454 with h69 | h69
  · exact checkN_of_all chunk_452_453 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 456 with h70 | h70
  · exact checkN_of_all chunk_454_455 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 458 with h71 | h71
  · exact checkN_of_all chunk_456_457 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 460 with h72 | h72
  · exact checkN_of_all chunk_458_459 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 462 with h73 | h73
  · exact checkN_of_all chunk_460_461 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 464 with h74 | h74
  · exact checkN_of_all chunk_462_463 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 466 with h75 | h75
  · exact checkN_of_all chunk_464_465 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 468 with h76 | h76
  · exact checkN_of_all chunk_466_467 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 470 with h77 | h77
  · exact checkN_of_all chunk_468_469 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 472 with h78 | h78
  · exact checkN_of_all chunk_470_471 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 474 with h79 | h79
  · exact checkN_of_all chunk_472_473 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 476 with h80 | h80
  · exact checkN_of_all chunk_474_475 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 478 with h81 | h81
  · exact checkN_of_all chunk_476_477 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 480 with h82 | h82
  · exact checkN_of_all chunk_478_479 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 482 with h83 | h83
  · exact checkN_of_all chunk_480_481 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 484 with h84 | h84
  · exact checkN_of_all chunk_482_483 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 486 with h85 | h85
  · exact checkN_of_all chunk_484_485 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 488 with h86 | h86
  · exact checkN_of_all chunk_486_487 n (by omega) (by omega)
  rcases Nat.lt_or_ge n 490 with h87 | h87
  · exact checkN_of_all chunk_488_489 n (by omega) (by omega)
  exact checkN_of_all chunk_490_491 n (by omega) (by omega)

/-- **The spider-family optimum for every `4 ≤ n ≤ 491`.** -/
theorem spider_opt_table (n : ℕ) (h4 : 4 ≤ n) (hN : n ≤ 491) :
    nv (tab n) = n ∧ ∀ l : List Child, nv l = n → F l ≤ F (tab n) :=
  spider_opt_of_checkN n (by omega) (checkN_all n h4 hN)

end BGSpiderTable
end R3Cert
