-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 292 <= n <= 301, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 292. -/
def T292 : ℕ × ℕ := (126216770541390941273896347993282042100707465592921233480876805121013504082060266000399878735812787519838, 870441889739368120103189269201711139875001011829833375933328037812033814528000)
theorem tabV_292 : tabV 292 = T292 := by decide +kernel
theorem bal_292_0 : (List.range' 0 49).all (balRow 292 T292) = true := by decide +kernel
theorem bal_292_1 : (List.range' 49 97).all (balRow 292 T292) = true := by decide +kernel
theorem small_292 : checkSmallFast 292 T292 = true := by decide +kernel
theorem checkN_292 : checkN 292 = true := by
  have h : (List.range' 0 49).all (balRow 292 T292) = true := bal_292_0
  have h : (List.range' 0 146).all (balRow 292 T292) = true := all_range'_append (by decide) (by decide) h bal_292_1
  exact checkN_of_parts tabV_292 (by decide +kernel) (by decide) h small_292

/-- The table value at n = 293. -/
def T293 : ℕ × ℕ := (1163057440022726948698228359920749150731980544460411988125094363099038477693586655862730567283082324958904, 6529806700291041710307704137101313849370935231062278840377760914656460800000000)
theorem tabV_293 : tabV 293 = T293 := by decide +kernel
theorem bal_293_0 : (List.range' 0 48).all (balRow 293 T293) = true := by decide +kernel
theorem bal_293_1 : (List.range' 48 99).all (balRow 293 T293) = true := by decide +kernel
theorem small_293 : checkSmallFast 293 T293 = true := by decide +kernel
theorem checkN_293 : checkN 293 = true := by
  have h : (List.range' 0 48).all (balRow 293 T293) = true := bal_293_0
  have h : (List.range' 0 147).all (balRow 293 T293) = true := all_range'_append (by decide) (by decide) h bal_293_1
  exact checkN_of_parts tabV_293 (by decide +kernel) (by decide) h small_293

/-- The table value at n = 294. -/
def T294 : ℕ × ℕ := (457954891542153814761652251934823225787372465476731493952255495863386887623943393412657235158111977725694, 2089060535374483488247654246084106735700002428391600102239987290748881154867200)
theorem tabV_294 : tabV 294 = T294 := by decide +kernel
theorem bal_294_0 : (List.range' 0 48).all (balRow 294 T294) = true := by decide +kernel
theorem bal_294_1 : (List.range' 48 99).all (balRow 294 T294) = true := by decide +kernel
theorem small_294 : checkSmallFast 294 T294 = true := by decide +kernel
theorem checkN_294 : checkN 294 = true := by
  have h : (List.range' 0 48).all (balRow 294 T294) = true := bal_294_0
  have h : (List.range' 0 147).all (balRow 294 T294) = true := all_range'_append (by decide) (by decide) h bal_294_1
  exact checkN_of_parts tabV_294 (by decide +kernel) (by decide) h small_294

/-- The table value at n = 295. -/
def T295 : ℕ × ℕ := (4220095854392448785663992503209524991419974329306604766791877429128560198446494306455822960290081247750988, 15671536080698500104738489929043153238490244554549469216906626195175505920000000)
theorem tabV_295 : tabV 295 = T295 := by decide +kernel
theorem bal_295_0 : (List.range' 0 48).all (balRow 295 T295) = true := by decide +kernel
theorem bal_295_1 : (List.range' 48 100).all (balRow 295 T295) = true := by decide +kernel
theorem small_295 : checkSmallFast 295 T295 = true := by decide +kernel
theorem checkN_295 : checkN 295 = true := by
  have h : (List.range' 0 48).all (balRow 295 T295) = true := bal_295_0
  have h : (List.range' 0 148).all (balRow 295 T295) = true := all_range'_append (by decide) (by decide) h bal_295_1
  exact checkN_of_parts tabV_295 (by decide +kernel) (by decide) h small_295

/-- The table value at n = 296. -/
def T296 : ℕ × ℕ := (1661605764753365736565184741764794170562388811058426549973294850339764893117148618005771323887437463198950, 5013745284898760371794370190601856165680005828139840245375969497797314771681280)
theorem tabV_296 : tabV 296 = T296 := by decide +kernel
theorem bal_296_0 : (List.range' 0 48).all (balRow 296 T296) = true := by decide +kernel
theorem bal_296_1 : (List.range' 48 100).all (balRow 296 T296) = true := by decide +kernel
theorem small_296 : checkSmallFast 296 T296 = true := by decide +kernel
theorem checkN_296 : checkN 296 = true := by
  have h : (List.range' 0 48).all (balRow 296 T296) = true := bal_296_0
  have h : (List.range' 0 148).all (balRow 296 T296) = true := all_range'_append (by decide) (by decide) h bal_296_1
  exact checkN_of_parts tabV_296 (by decide +kernel) (by decide) h small_296

/-- The table value at n = 297. -/
def T297 : ℕ × ℕ := (15312395729276447959165438010616863769718042435639601725941075779669148609494576185497804905944149812946672, 37611686593676400251372375829703567772376586930918726120575902868421214208000000)
theorem tabV_297 : tabV 297 = T297 := by decide +kernel
theorem bal_297_0 : (List.range' 0 48).all (balRow 297 T297) = true := by decide +kernel
theorem bal_297_1 : (List.range' 48 101).all (balRow 297 T297) = true := by decide +kernel
theorem small_297 : checkSmallFast 297 T297 = true := by decide +kernel
theorem checkN_297 : checkN 297 = true := by
  have h : (List.range' 0 48).all (balRow 297 T297) = true := bal_297_0
  have h : (List.range' 0 149).all (balRow 297 T297) = true := all_range'_append (by decide) (by decide) h bal_297_1
  exact checkN_of_parts tabV_297 (by decide +kernel) (by decide) h small_297

/-- The table value at n = 298. -/
def T298 : ℕ × ℕ := (8567282558227223724774686773440897697259714997876198545812632804811564601245133090841773654383645920542598, 17099510234812614320646062544789488396634967245445349889492780181961368273944576)
theorem tabV_298 : tabV 298 = T298 := by decide +kernel
theorem bal_298_0 : (List.range' 0 47).all (balRow 298 T298) = true := by decide +kernel
theorem bal_298_1 : (List.range' 47 102).all (balRow 298 T298) = true := by decide +kernel
theorem small_298 : checkSmallFast 298 T298 = true := by decide +kernel
theorem checkN_298 : checkN 298 = true := by
  have h : (List.range' 0 47).all (balRow 298 T298) = true := bal_298_0
  have h : (List.range' 0 149).all (balRow 298 T298) = true := all_range'_append (by decide) (by decide) h bal_298_1
  exact checkN_of_parts tabV_298 (by decide +kernel) (by decide) h small_298

/-- The table value at n = 299. -/
def T299 : ℕ × ℕ := (55560180718560658948436316221764178171884236798942632772081363585073220358146868048030668558017961188375956, 90268047824823360603293701991288562653703808634204942689382166884210914099200000)
theorem tabV_299 : tabV 299 = T299 := by decide +kernel
theorem bal_299_0 : (List.range' 0 47).all (balRow 299 T299) = true := by decide +kernel
theorem bal_299_1 : (List.range' 47 103).all (balRow 299 T299) = true := by decide +kernel
theorem small_299 : checkSmallFast 299 T299 = true := by decide +kernel
theorem checkN_299 : checkN 299 = true := by
  have h : (List.range' 0 47).all (balRow 299 T299) = true := bal_299_0
  have h : (List.range' 0 150).all (balRow 299 T299) = true := all_range'_append (by decide) (by decide) h bal_299_1
  exact checkN_of_parts tabV_299 (by decide +kernel) (by decide) h small_299

/-- The table value at n = 300. -/
def T300 : ℕ × ℕ := (26824625445845352916032423829092725268627996531811801144866334622472676628969804179017405259736828679989502, 35465650857389125998377018611415235193020672805368133104133173710734689753366528)
theorem tabV_300 : tabV 300 = T300 := by decide +kernel
theorem bal_300_0 : (List.range' 0 47).all (balRow 300 T300) = true := by decide +kernel
theorem bal_300_1 : (List.range' 47 103).all (balRow 300 T300) = true := by decide +kernel
theorem small_300 : checkSmallFast 300 T300 = true := by decide +kernel
theorem checkN_300 : checkN 300 = true := by
  have h : (List.range' 0 47).all (balRow 300 T300) = true := bal_300_0
  have h : (List.range' 0 150).all (balRow 300 T300) = true := all_range'_append (by decide) (by decide) h bal_300_1
  exact checkN_of_parts tabV_300 (by decide +kernel) (by decide) h small_300

/-- The table value at n = 301. -/
def T301 : ℕ × ℕ := (201596891348977504236048118462378910689897143630879333271999649676058635039494212750086880337736833729868840, 216643314779576065447904884779092550368889140722091862454517200522106193838080000)
theorem tabV_301 : tabV 301 = T301 := by decide +kernel
theorem bal_301_0 : (List.range' 0 47).all (balRow 301 T301) = true := by decide +kernel
theorem bal_301_1 : (List.range' 47 104).all (balRow 301 T301) = true := by decide +kernel
theorem small_301 : checkSmallFast 301 T301 = true := by decide +kernel
theorem checkN_301 : checkN 301 = true := by
  have h : (List.range' 0 47).all (balRow 301 T301) = true := bal_301_0
  have h : (List.range' 0 151).all (balRow 301 T301) = true := all_range'_append (by decide) (by decide) h bal_301_1
  exact checkN_of_parts tabV_301 (by decide +kernel) (by decide) h small_301

end Sweep

theorem chunk_292_301 : (List.range' 292 10).all checkN = true := by
  have h : (List.range' 292 1).all checkN = true := all_range'_one Sweep.checkN_292
  have h : (List.range' 292 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_293
  have h : (List.range' 292 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_294
  have h : (List.range' 292 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_295
  have h : (List.range' 292 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_296
  have h : (List.range' 292 6).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_297
  have h : (List.range' 292 7).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_298
  have h : (List.range' 292 8).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_299
  have h : (List.range' 292 9).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_300
  have h : (List.range' 292 10).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_301
  exact h

end BGSpiderTable
end R3Cert
