-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 328 <= n <= 335, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 328. -/
def T328 : ℕ × ℕ := (815219462823609800242695799629176769434968313363331402637959757974494301137765469783757030625542551597073214350976166, 3315756881746380192546676819384694210903043854343147682275307827876624169005219840000000)
theorem tabV_328 : tabV 328 = T328 := by decide +kernel
theorem bal_328_0 : (List.range' 0 41).all (balRow 328 T328) = true := by decide +kernel
theorem bal_328_1 : (List.range' 41 66).all (balRow 328 T328) = true := by decide +kernel
theorem bal_328_2 : (List.range' 107 57).all (balRow 328 T328) = true := by decide +kernel
theorem small_328 : checkSmallFast 328 T328 = true := by decide +kernel
theorem checkN_328 : checkN 328 = true := by
  have h : (List.range' 0 41).all (balRow 328 T328) = true := bal_328_0
  have h : (List.range' 0 107).all (balRow 328 T328) = true := all_range'_append (by decide) (by decide) h bal_328_1
  have h : (List.range' 0 164).all (balRow 328 T328) = true := all_range'_append (by decide) (by decide) h bal_328_2
  exact checkN_of_parts tabV_328 (by decide +kernel) (by decide) h small_328

/-- The table value at n = 329. -/
def T329 : ℕ × ℕ := (322291439500575041548307953133010803468687243991315373720754478466215701136957136525856536047154697118466757572002096, 1064601827611245517511967337188557715983775752727631127839908899904769219641170146099200)
theorem tabV_329 : tabV 329 = T329 := by decide +kernel
theorem bal_329_0 : (List.range' 0 41).all (balRow 329 T329) = true := by decide +kernel
theorem bal_329_1 : (List.range' 41 65).all (balRow 329 T329) = true := by decide +kernel
theorem bal_329_2 : (List.range' 106 59).all (balRow 329 T329) = true := by decide +kernel
theorem small_329 : checkSmallFast 329 T329 = true := by decide +kernel
theorem checkN_329 : checkN 329 = true := by
  have h : (List.range' 0 41).all (balRow 329 T329) = true := bal_329_0
  have h : (List.range' 0 106).all (balRow 329 T329) = true := all_range'_append (by decide) (by decide) h bal_329_1
  have h : (List.range' 0 165).all (balRow 329 T329) = true := all_range'_append (by decide) (by decide) h bal_329_2
  exact checkN_of_parts tabV_329 (by decide +kernel) (by decide) h small_329

/-- The table value at n = 330. -/
def T330 : ℕ × ℕ := (2958226629552984210768500736744763333728656320332671263896704868361216709258517875692704833338291511618758501939022262, 7957816516191312462112024366523266106167305250423554437460738786903898005612527616000000)
theorem tabV_330 : tabV 330 = T330 := by decide +kernel
theorem bal_330_0 : (List.range' 0 41).all (balRow 330 T330) = true := by decide +kernel
theorem bal_330_1 : (List.range' 41 65).all (balRow 330 T330) = true := by decide +kernel
theorem bal_330_2 : (List.range' 106 59).all (balRow 330 T330) = true := by decide +kernel
theorem small_330 : checkSmallFast 330 T330 = true := by decide +kernel
theorem checkN_330 : checkN 330 = true := by
  have h : (List.range' 0 41).all (balRow 330 T330) = true := bal_330_0
  have h : (List.range' 0 106).all (balRow 330 T330) = true := all_range'_append (by decide) (by decide) h bal_330_1
  have h : (List.range' 0 165).all (balRow 330 T330) = true := all_range'_append (by decide) (by decide) h bal_330_2
  exact checkN_of_parts tabV_330 (by decide +kernel) (by decide) h small_330

/-- The table value at n = 331. -/
def T331 : ℕ × ℕ := (1661892431711894679624099454294070143333362366339990426703916009617884105313397395997215007350970790647280361445307180, 3630852548905721554461867549990449473460456251407920899159268248096265549091990814064640)
theorem tabV_331 : tabV 331 = T331 := by decide +kernel
theorem bal_331_0 : (List.range' 0 41).all (balRow 331 T331) = true := by decide +kernel
theorem bal_331_1 : (List.range' 41 64).all (balRow 331 T331) = true := by decide +kernel
theorem bal_331_2 : (List.range' 105 61).all (balRow 331 T331) = true := by decide +kernel
theorem small_331 : checkSmallFast 331 T331 = true := by decide +kernel
theorem checkN_331 : checkN 331 = true := by
  have h : (List.range' 0 41).all (balRow 331 T331) = true := bal_331_0
  have h : (List.range' 0 105).all (balRow 331 T331) = true := all_range'_append (by decide) (by decide) h bal_331_1
  have h : (List.range' 0 166).all (balRow 331 T331) = true := all_range'_append (by decide) (by decide) h bal_331_2
  exact checkN_of_parts tabV_331 (by decide +kernel) (by decide) h small_331

/-- The table value at n = 332. -/
def T332 : ℕ × ℕ := (10734654737353790420164914763740329256943636376702058853124193233037514803210339247716910942395546413603100328418611758, 19098759638859149909068858479655838654801532601016530649905773088569355213470066278400000)
theorem tabV_332 : tabV 332 = T332 := by decide +kernel
theorem bal_332_0 : (List.range' 0 41).all (balRow 332 T332) = true := by decide +kernel
theorem bal_332_1 : (List.range' 41 64).all (balRow 332 T332) = true := by decide +kernel
theorem bal_332_2 : (List.range' 105 61).all (balRow 332 T332) = true := by decide +kernel
theorem small_332 : checkSmallFast 332 T332 = true := by decide +kernel
theorem checkN_332 : checkN 332 = true := by
  have h : (List.range' 0 41).all (balRow 332 T332) = true := bal_332_0
  have h : (List.range' 0 105).all (balRow 332 T332) = true := all_range'_append (by decide) (by decide) h bal_332_1
  have h : (List.range' 0 166).all (balRow 332 T332) = true := all_range'_append (by decide) (by decide) h bal_332_2
  exact checkN_of_parts tabV_332 (by decide +kernel) (by decide) h small_332

/-- The table value at n = 333. -/
def T333 : ℕ × ℕ := (5181695376824779308776679324157921267418893942229303484287081712039351466823310855211829356253283285710494665429470592, 7503761934405157879221192936646928911818276252909703191595821046065615468123447682400256)
theorem tabV_333 : tabV 333 = T333 := by decide +kernel
theorem bal_333_0 : (List.range' 0 40).all (balRow 333 T333) = true := by decide +kernel
theorem bal_333_1 : (List.range' 40 62).all (balRow 333 T333) = true := by decide +kernel
theorem bal_333_2 : (List.range' 102 65).all (balRow 333 T333) = true := by decide +kernel
theorem small_333 : checkSmallFast 333 T333 = true := by decide +kernel
theorem checkN_333 : checkN 333 = true := by
  have h : (List.range' 0 40).all (balRow 333 T333) = true := bal_333_0
  have h : (List.range' 0 102).all (balRow 333 T333) = true := all_range'_append (by decide) (by decide) h bal_333_1
  have h : (List.range' 0 167).all (balRow 333 T333) = true := all_range'_append (by decide) (by decide) h bal_333_2
  exact checkN_of_parts tabV_333 (by decide +kernel) (by decide) h small_333

/-- The table value at n = 334. -/
def T334 : ℕ × ℕ := (38953317833905486576741203609100623489817401214983242175843276395447676069910542662993830413954340192937451061999764654, 45837023133261959781765260351174012771523678242439673559773855412566452512328159068160000)
theorem tabV_334 : tabV 334 = T334 := by decide +kernel
theorem bal_334_0 : (List.range' 0 40).all (balRow 334 T334) = true := by decide +kernel
theorem bal_334_1 : (List.range' 40 62).all (balRow 334 T334) = true := by decide +kernel
theorem bal_334_2 : (List.range' 102 65).all (balRow 334 T334) = true := by decide +kernel
theorem small_334 : checkSmallFast 334 T334 = true := by decide +kernel
theorem checkN_334 : checkN 334 = true := by
  have h : (List.range' 0 40).all (balRow 334 T334) = true := bal_334_0
  have h : (List.range' 0 102).all (balRow 334 T334) = true := all_range'_append (by decide) (by decide) h bal_334_1
  have h : (List.range' 0 167).all (balRow 334 T334) = true := all_range'_append (by decide) (by decide) h bal_334_2
  exact checkN_of_parts tabV_334 (by decide +kernel) (by decide) h small_334

/-- The table value at n = 335. -/
def T335 : ℕ × ℕ := (357097890639438466573072134278349492947420718018174743317732048486579945421960100241313002080462200888968531837449250908, 342271678115755374714495671678420047577088397867679760750999517716296688413442048000000000)
theorem tabV_335 : tabV 335 = T335 := by decide +kernel
theorem bal_335_0 : (List.range' 0 40).all (balRow 335 T335) = true := by decide +kernel
theorem bal_335_1 : (List.range' 40 61).all (balRow 335 T335) = true := by decide +kernel
theorem bal_335_2 : (List.range' 101 67).all (balRow 335 T335) = true := by decide +kernel
theorem small_335 : checkSmallFast 335 T335 = true := by decide +kernel
theorem checkN_335 : checkN 335 = true := by
  have h : (List.range' 0 40).all (balRow 335 T335) = true := bal_335_0
  have h : (List.range' 0 101).all (balRow 335 T335) = true := all_range'_append (by decide) (by decide) h bal_335_1
  have h : (List.range' 0 168).all (balRow 335 T335) = true := all_range'_append (by decide) (by decide) h bal_335_2
  exact checkN_of_parts tabV_335 (by decide +kernel) (by decide) h small_335

end Sweep

theorem chunk_328_335 : (List.range' 328 8).all checkN = true := by
  have h : (List.range' 328 1).all checkN = true := all_range'_one Sweep.checkN_328
  have h : (List.range' 328 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_329
  have h : (List.range' 328 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_330
  have h : (List.range' 328 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_331
  have h : (List.range' 328 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_332
  have h : (List.range' 328 6).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_333
  have h : (List.range' 328 7).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_334
  have h : (List.range' 328 8).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_335
  exact h

end BGSpiderTable
end R3Cert
