-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 282 <= n <= 291, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 282. -/
def T282 : ℕ × ℕ := (200716760979700343591698592058487538588062927957913024471847569339714987835294691114201441794732801558, 10931596038433663577524058265236574524616521034144440022953840816947200000000)
theorem tabV_282 : tabV 282 = T282 := by decide +kernel
theorem bal_282_0 : (List.range' 0 51).all (balRow 282 T282) = true := by decide +kernel
theorem bal_282_1 : (List.range' 51 90).all (balRow 282 T282) = true := by decide +kernel
theorem small_282 : checkSmallFast 282 T282 = true := by decide +kernel
theorem checkN_282 : checkN 282 = true := by
  have h : (List.range' 0 51).all (balRow 282 T282) = true := bal_282_0
  have h : (List.range' 0 141).all (balRow 282 T282) = true := all_range'_append (by decide) (by decide) h bal_282_1
  exact checkN_of_parts tabV_282 (by decide +kernel) (by decide) h small_282

/-- The table value at n = 283. -/
def T283 : ℕ × ℕ := (78909297564777265223742935216087682944791469218188153443494550602008988109071984584111327875537065644, 3492513755127094309056006327043902721720683072156738854053476694924827033600)
theorem tabV_283 : tabV 283 = T283 := by decide +kernel
theorem bal_283_0 : (List.range' 0 51).all (balRow 283 T283) = true := by decide +kernel
theorem bal_283_1 : (List.range' 51 91).all (balRow 283 T283) = true := by decide +kernel
theorem small_283 : checkSmallFast 283 T283 = true := by decide +kernel
theorem checkN_283 : checkN 283 = true := by
  have h : (List.range' 0 51).all (balRow 283 T283) = true := bal_283_0
  have h : (List.range' 0 142).all (balRow 283 T283) = true := all_range'_append (by decide) (by decide) h bal_283_1
  exact checkN_of_parts tabV_283 (by decide +kernel) (by decide) h small_283

/-- The table value at n = 284. -/
def T284 : ℕ × ℕ := (728267652558700715413588133330286712669736891918096637744836460597847429946198760197229382133527470414, 26235830492240792586057739836567778859079650481946656055089217960673280000000)
theorem tabV_284 : tabV 284 = T284 := by decide +kernel
theorem bal_284_0 : (List.range' 0 51).all (balRow 284 T284) = true := by decide +kernel
theorem bal_284_1 : (List.range' 51 91).all (balRow 284 T284) = true := by decide +kernel
theorem small_284 : checkSmallFast 284 T284 = true := by decide +kernel
theorem checkN_284 : checkN 284 = true := by
  have h : (List.range' 0 51).all (balRow 284 T284) = true := bal_284_0
  have h : (List.range' 0 142).all (balRow 284 T284) = true := all_range'_append (by decide) (by decide) h bal_284_1
  exact checkN_of_parts tabV_284 (by decide +kernel) (by decide) h small_284

/-- The table value at n = 285. -/
def T285 : ℕ × ℕ := (286298108465723132038816415606742160822188455452787232900054194146313585017038720829802737719783925848, 8382033012305026341734415184905366532129639373176173249728344067819584880640)
theorem tabV_285 : tabV 285 = T285 := by decide +kernel
theorem bal_285_0 : (List.range' 0 51).all (balRow 285 T285) = true := by decide +kernel
theorem bal_285_1 : (List.range' 51 92).all (balRow 285 T285) = true := by decide +kernel
theorem small_285 : checkSmallFast 285 T285 = true := by decide +kernel
theorem checkN_285 : checkN 285 = true := by
  have h : (List.range' 0 51).all (balRow 285 T285) = true := bal_285_0
  have h : (List.range' 0 143).all (balRow 285 T285) = true := all_range'_append (by decide) (by decide) h bal_285_1
  exact checkN_of_parts tabV_285 (by decide +kernel) (by decide) h small_285

/-- The table value at n = 286. -/
def T286 : ℕ × ℕ := (2642396914084653573336152600558317422166987619395084417331010864435382006191399237790643699638188806670, 62965993181377902206538575607762669261791161156671974532214123105615872000000)
theorem tabV_286 : tabV 286 = T286 := by decide +kernel
theorem bal_286_0 : (List.range' 0 50).all (balRow 286 T286) = true := by decide +kernel
theorem bal_286_1 : (List.range' 50 93).all (balRow 286 T286) = true := by decide +kernel
theorem small_286 : checkSmallFast 286 T286 = true := by decide +kernel
theorem checkN_286 : checkN 286 = true := by
  have h : (List.range' 0 50).all (balRow 286 T286) = true := bal_286_0
  have h : (List.range' 0 143).all (balRow 286 T286) = true := all_range'_append (by decide) (by decide) h bal_286_1
  exact checkN_of_parts tabV_286 (by decide +kernel) (by decide) h small_286

/-- The table value at n = 287. -/
def T287 : ℕ × ℕ := (1476109464450062734631795631030949286155693325810495233303038726367936221495751975519944036990482587716, 28587144168282405628652110735887776383263191125358738241178773452353110540288)
theorem tabV_287 : tabV 287 = T287 := by decide +kernel
theorem bal_287_0 : (List.range' 0 50).all (balRow 287 T287) = true := by decide +kernel
theorem bal_287_1 : (List.range' 50 94).all (balRow 287 T287) = true := by decide +kernel
theorem small_287 : checkSmallFast 287 T287 = true := by decide +kernel
theorem checkN_287 : checkN 287 = true := by
  have h : (List.range' 0 50).all (balRow 287 T287) = true := bal_287_0
  have h : (List.range' 0 144).all (balRow 287 T287) = true := all_range'_append (by decide) (by decide) h bal_287_1
  exact checkN_of_parts tabV_287 (by decide +kernel) (by decide) h small_287

/-- The table value at n = 288. -/
def T288 : ℕ × ℕ := (9587485913844840895299997273901421722718072564077155817004831295410581734792234083623431280093093530326, 151118383635306965295692581458630406228298786776012738877313895453478092800000)
theorem tabV_288 : tabV 288 = T288 := by decide +kernel
theorem bal_288_0 : (List.range' 0 50).all (balRow 288 T288) = true := by decide +kernel
theorem bal_288_1 : (List.range' 50 94).all (balRow 288 T288) = true := by decide +kernel
theorem small_288 : checkSmallFast 288 T288 = true := by decide +kernel
theorem checkN_288 : checkN 288 = true := by
  have h : (List.range' 0 50).all (balRow 288 T288) = true := bal_288_0
  have h : (List.range' 0 144).all (balRow 288 T288) = true := all_range'_append (by decide) (by decide) h bal_288_1
  exact checkN_of_parts tabV_288 (by decide +kernel) (by decide) h small_288

/-- The table value at n = 289. -/
def T289 : ℕ × ℕ := (4629219030523865380797938961221320246523771968518121145861600739497078091081352349263729820147667286920, 59373299426432688613354383836074612488315858491129687116294375631810306506752)
theorem tabV_289 : tabV 289 = T289 := by decide +kernel
theorem bal_289_0 : (List.range' 0 50).all (balRow 289 T289) = true := by decide +kernel
theorem bal_289_1 : (List.range' 50 95).all (balRow 289 T289) = true := by decide +kernel
theorem small_289 : checkSmallFast 289 T289 = true := by decide +kernel
theorem checkN_289 : checkN 289 = true := by
  have h : (List.range' 0 50).all (balRow 289 T289) = true := bal_289_0
  have h : (List.range' 0 145).all (balRow 289 T289) = true := all_range'_append (by decide) (by decide) h bal_289_1
  exact checkN_of_parts tabV_289 (by decide +kernel) (by decide) h small_289

/-- The table value at n = 290. -/
def T290 : ℕ × ℕ := (34786527307878496301449225265682488947450853759197522552004778202187511294038742371577235906999097861382, 362684120724736716709662195500712974947917088262430573305553349088347422720000)
theorem tabV_290 : tabV 290 = T290 := by decide +kernel
theorem bal_290_0 : (List.range' 0 49).all (balRow 290 T290) = true := by decide +kernel
theorem bal_290_1 : (List.range' 49 96).all (balRow 290 T290) = true := by decide +kernel
theorem small_290 : checkSmallFast 290 T290 = true := by decide +kernel
theorem checkN_290 : checkN 290 = true := by
  have h : (List.range' 0 49).all (balRow 290 T290) = true := bal_290_0
  have h : (List.range' 0 145).all (balRow 290 T290) = true := all_range'_append (by decide) (by decide) h bal_290_1
  exact checkN_of_parts tabV_290 (by decide +kernel) (by decide) h small_290

/-- The table value at n = 291. -/
def T291 : ℕ × ℕ := (320538123147220341915995266971973482738215134361587043069130365076720994932451116790911039435312439740420, 2720752791787934045961543390458880770571223012942616183490733714440192000000000)
theorem tabV_291 : tabV 291 = T291 := by decide +kernel
theorem bal_291_0 : (List.range' 0 49).all (balRow 291 T291) = true := by decide +kernel
theorem bal_291_1 : (List.range' 49 97).all (balRow 291 T291) = true := by decide +kernel
theorem small_291 : checkSmallFast 291 T291 = true := by decide +kernel
theorem checkN_291 : checkN 291 = true := by
  have h : (List.range' 0 49).all (balRow 291 T291) = true := bal_291_0
  have h : (List.range' 0 146).all (balRow 291 T291) = true := all_range'_append (by decide) (by decide) h bal_291_1
  exact checkN_of_parts tabV_291 (by decide +kernel) (by decide) h small_291

end Sweep

theorem chunk_282_291 : (List.range' 282 10).all checkN = true := by
  have h : (List.range' 282 1).all checkN = true := all_range'_one Sweep.checkN_282
  have h : (List.range' 282 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_283
  have h : (List.range' 282 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_284
  have h : (List.range' 282 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_285
  have h : (List.range' 282 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_286
  have h : (List.range' 282 6).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_287
  have h : (List.range' 282 7).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_288
  have h : (List.range' 282 8).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_289
  have h : (List.range' 282 9).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_290
  have h : (List.range' 282 10).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_291
  exact h

end BGSpiderTable
end R3Cert
