-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 382 <= n <= 387, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 382. -/
def T382 : ℕ × ℕ := (564964975414191711995114296686395425586115332632777787979740280233689890215783388055841879203689815686786501751932660321692256477198158, 32812186581062459740624424054646573358982466012062967898900253868706082333177323068519553041432576000)
theorem tabV_382 : tabV 382 = T382 := by decide +kernel
theorem bal_382_0 : (List.range' 0 34).all (balRow 382 T382) = true := by decide +kernel
theorem bal_382_1 : (List.range' 34 44).all (balRow 382 T382) = true := by decide +kernel
theorem bal_382_2 : (List.range' 78 83).all (balRow 382 T382) = true := by decide +kernel
theorem bal_382_3 : (List.range' 161 30).all (balRow 382 T382) = true := by decide +kernel
theorem small_382 : checkSmallFast 382 T382 = true := by decide +kernel
theorem checkN_382 : checkN 382 = true := by
  have h : (List.range' 0 34).all (balRow 382 T382) = true := bal_382_0
  have h : (List.range' 0 78).all (balRow 382 T382) = true := all_range'_append (by decide) (by decide) h bal_382_1
  have h : (List.range' 0 161).all (balRow 382 T382) = true := all_range'_append (by decide) (by decide) h bal_382_2
  have h : (List.range' 0 191).all (balRow 382 T382) = true := all_range'_append (by decide) (by decide) h bal_382_3
  exact checkN_of_parts tabV_382 (by decide +kernel) (by decide) h small_382

/-- The table value at n = 383. -/
def T383 : ℕ × ℕ := (5158895326885690483324074062761149151782541770932167692171953555242695441974125061663022098662352731310829398812938478192013185226530044, 244138293013857587355836488501834623206714776875468511152531650808825017359950320450294293463040000000)
theorem tabV_383 : tabV 383 = T383 := by decide +kernel
theorem bal_383_0 : (List.range' 0 34).all (balRow 383 T383) = true := by decide +kernel
theorem bal_383_1 : (List.range' 34 44).all (balRow 383 T383) = true := by decide +kernel
theorem bal_383_2 : (List.range' 78 82).all (balRow 383 T383) = true := by decide +kernel
theorem bal_383_3 : (List.range' 160 32).all (balRow 383 T383) = true := by decide +kernel
theorem small_383 : checkSmallFast 383 T383 = true := by decide +kernel
theorem checkN_383 : checkN 383 = true := by
  have h : (List.range' 0 34).all (balRow 383 T383) = true := bal_383_0
  have h : (List.range' 0 78).all (balRow 383 T383) = true := all_range'_append (by decide) (by decide) h bal_383_1
  have h : (List.range' 0 160).all (balRow 383 T383) = true := all_range'_append (by decide) (by decide) h bal_383_2
  have h : (List.range' 0 192).all (balRow 383 T383) = true := all_range'_append (by decide) (by decide) h bal_383_3
  exact checkN_of_parts tabV_383 (by decide +kernel) (by decide) h small_383

/-- The table value at n = 384. -/
def T384 : ℕ × ℕ := (2050292906618093678571108448069079911270091001743797744588064349123094396245905073563256255615396856148908469806982433847657326557228694, 78749247794549903377498617731151776061557918428951122957360609284894597599625575364446927299438182400)
theorem tabV_384 : tabV 384 = T384 := by decide +kernel
theorem bal_384_0 : (List.range' 0 34).all (balRow 384 T384) = true := by decide +kernel
theorem bal_384_1 : (List.range' 34 43).all (balRow 384 T384) = true := by decide +kernel
theorem bal_384_2 : (List.range' 77 78).all (balRow 384 T384) = true := by decide +kernel
theorem bal_384_3 : (List.range' 155 37).all (balRow 384 T384) = true := by decide +kernel
theorem small_384 : checkSmallFast 384 T384 = true := by decide +kernel
theorem checkN_384 : checkN 384 = true := by
  have h : (List.range' 0 34).all (balRow 384 T384) = true := bal_384_0
  have h : (List.range' 0 77).all (balRow 384 T384) = true := all_range'_append (by decide) (by decide) h bal_384_1
  have h : (List.range' 0 155).all (balRow 384 T384) = true := all_range'_append (by decide) (by decide) h bal_384_2
  have h : (List.range' 0 192).all (balRow 384 T384) = true := all_range'_append (by decide) (by decide) h bal_384_3
  exact checkN_of_parts tabV_384 (by decide +kernel) (by decide) h small_384

/-- The table value at n = 385. -/
def T385 : ℕ × ℕ := (18722353434025224039583236088219317299205299519463699455327800905725425980642867637448863769886574515893587219784455107028043468013795648, 585931903233258209654007572404403095696115464501124426766075961941180041663880769080706304311296000000)
theorem tabV_385 : tabV 385 = T385 := by decide +kernel
theorem bal_385_0 : (List.range' 0 34).all (balRow 385 T385) = true := by decide +kernel
theorem bal_385_1 : (List.range' 34 43).all (balRow 385 T385) = true := by decide +kernel
theorem bal_385_2 : (List.range' 77 77).all (balRow 385 T385) = true := by decide +kernel
theorem bal_385_3 : (List.range' 154 39).all (balRow 385 T385) = true := by decide +kernel
theorem small_385 : checkSmallFast 385 T385 = true := by decide +kernel
theorem checkN_385 : checkN 385 = true := by
  have h : (List.range' 0 34).all (balRow 385 T385) = true := bal_385_0
  have h : (List.range' 0 77).all (balRow 385 T385) = true := all_range'_append (by decide) (by decide) h bal_385_1
  have h : (List.range' 0 154).all (balRow 385 T385) = true := all_range'_append (by decide) (by decide) h bal_385_2
  have h : (List.range' 0 193).all (balRow 385 T385) = true := all_range'_append (by decide) (by decide) h bal_385_3
  exact checkN_of_parts tabV_385 (by decide +kernel) (by decide) h small_385

/-- The table value at n = 386. -/
def T386 : ℕ × ℕ := (10573535987250797766281833208405944083049490408733741247840174038288410901044510364983650286344903090409167775303954911129680461133992790, 268576381951938617834837390998875530988892269168212250928261446403219469708196699137692678368610222080)
theorem tabV_386 : tabV 386 = T386 := by decide +kernel
theorem bal_386_0 : (List.range' 0 33).all (balRow 386 T386) = true := by decide +kernel
theorem bal_386_1 : (List.range' 33 43).all (balRow 386 T386) = true := by decide +kernel
theorem bal_386_2 : (List.range' 76 75).all (balRow 386 T386) = true := by decide +kernel
theorem bal_386_3 : (List.range' 151 42).all (balRow 386 T386) = true := by decide +kernel
theorem small_386 : checkSmallFast 386 T386 = true := by decide +kernel
theorem checkN_386 : checkN 386 = true := by
  have h : (List.range' 0 33).all (balRow 386 T386) = true := bal_386_0
  have h : (List.range' 0 76).all (balRow 386 T386) = true := all_range'_append (by decide) (by decide) h bal_386_1
  have h : (List.range' 0 151).all (balRow 386 T386) = true := all_range'_append (by decide) (by decide) h bal_386_2
  have h : (List.range' 0 193).all (balRow 386 T386) = true := all_range'_append (by decide) (by decide) h bal_386_3
  exact checkN_of_parts tabV_386 (by decide +kernel) (by decide) h small_386

/-- The table value at n = 387. -/
def T387 : ℕ × ℕ := (67946011226347271580834704738241603453960149497578309112018900549311894520794430822197431005294008384770434688438895279654723540910422852, 1406236567759819703169618173770567429670677114802698624238582308658832099993313845793695130347110400000)
theorem tabV_387 : tabV 387 = T387 := by decide +kernel
theorem bal_387_0 : (List.range' 0 33).all (balRow 387 T387) = true := by decide +kernel
theorem bal_387_1 : (List.range' 33 43).all (balRow 387 T387) = true := by decide +kernel
theorem bal_387_2 : (List.range' 76 74).all (balRow 387 T387) = true := by decide +kernel
theorem bal_387_3 : (List.range' 150 44).all (balRow 387 T387) = true := by decide +kernel
theorem small_387 : checkSmallFast 387 T387 = true := by decide +kernel
theorem checkN_387 : checkN 387 = true := by
  have h : (List.range' 0 33).all (balRow 387 T387) = true := bal_387_0
  have h : (List.range' 0 76).all (balRow 387 T387) = true := all_range'_append (by decide) (by decide) h bal_387_1
  have h : (List.range' 0 150).all (balRow 387 T387) = true := all_range'_append (by decide) (by decide) h bal_387_2
  have h : (List.range' 0 194).all (balRow 387 T387) = true := all_range'_append (by decide) (by decide) h bal_387_3
  exact checkN_of_parts tabV_387 (by decide +kernel) (by decide) h small_387

end Sweep

theorem chunk_382_387 : (List.range' 382 6).all checkN = true := by
  have h : (List.range' 382 1).all checkN = true := all_range'_one Sweep.checkN_382
  have h : (List.range' 382 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_383
  have h : (List.range' 382 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_384
  have h : (List.range' 382 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_385
  have h : (List.range' 382 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_386
  have h : (List.range' 382 6).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_387
  exact h

end BGSpiderTable
end R3Cert
