-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 405 <= n <= 409, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 405. -/
def T405 : ℕ × ℕ := (170058585004444362267299857102901777266876008098586958201864261352223303273449625251441100494636206845537297744499630790614163828476359395891208, 85499183319797037952712784965250499723977168580004076353705804366456991679593481824256663925104312320000000)
theorem tabV_405 : tabV 405 = T405 := by decide +kernel
theorem bal_405_0 : (List.range' 0 32).all (balRow 405 T405) = true := by decide +kernel
theorem bal_405_1 : (List.range' 32 39).all (balRow 405 T405) = true := by decide +kernel
theorem bal_405_2 : (List.range' 71 58).all (balRow 405 T405) = true := by decide +kernel
theorem bal_405_3 : (List.range' 129 74).all (balRow 405 T405) = true := by decide +kernel
theorem small_405 : checkSmallFast 405 T405 = true := by decide +kernel
theorem checkN_405 : checkN 405 = true := by
  have h : (List.range' 0 32).all (balRow 405 T405) = true := bal_405_0
  have h : (List.range' 0 71).all (balRow 405 T405) = true := all_range'_append (by decide) (by decide) h bal_405_1
  have h : (List.range' 0 129).all (balRow 405 T405) = true := all_range'_append (by decide) (by decide) h bal_405_2
  have h : (List.range' 0 203).all (balRow 405 T405) = true := all_range'_append (by decide) (by decide) h bal_405_3
  exact checkN_of_parts tabV_405 (by decide +kernel) (by decide) h small_405

/-- The table value at n = 406. -/
def T406 : ℕ × ℕ := (67702004323533341953219755849813801997488966904376109465413576045851286050709782111227469418314720346725959610903380090496312126302323277221730, 27620088175500850956857151761877503749147979370094184214318489135025486585396996314521300537509739684167680)
theorem tabV_406 : tabV 406 = T406 := by decide +kernel
theorem bal_406_0 : (List.range' 0 32).all (balRow 406 T406) = true := by decide +kernel
theorem bal_406_1 : (List.range' 32 39).all (balRow 406 T406) = true := by decide +kernel
theorem bal_406_2 : (List.range' 71 57).all (balRow 406 T406) = true := by decide +kernel
theorem bal_406_3 : (List.range' 128 75).all (balRow 406 T406) = true := by decide +kernel
theorem small_406 : checkSmallFast 406 T406 = true := by decide +kernel
theorem checkN_406 : checkN 406 = true := by
  have h : (List.range' 0 32).all (balRow 406 T406) = true := bal_406_0
  have h : (List.range' 0 71).all (balRow 406 T406) = true := all_range'_append (by decide) (by decide) h bal_406_1
  have h : (List.range' 0 128).all (balRow 406 T406) = true := all_range'_append (by decide) (by decide) h bal_406_2
  have h : (List.range' 0 203).all (balRow 406 T406) = true := all_range'_append (by decide) (by decide) h bal_406_3
  exact checkN_of_parts tabV_406 (by decide +kernel) (by decide) h small_406

/-- The table value at n = 407. -/
def T407 : ℕ × ℕ := (617188147097779067439053036308556246975341628704179912535334780283727695093721520829424030164191219447150799047956875211198998279712133051258292, 205198039967512891086510683916601199337545204592009783248893930479496780031024356378215993420250349568000000)
theorem tabV_407 : tabV 407 = T407 := by decide +kernel
theorem bal_407_0 : (List.range' 0 31).all (balRow 407 T407) = true := by decide +kernel
theorem bal_407_1 : (List.range' 31 39).all (balRow 407 T407) = true := by decide +kernel
theorem bal_407_2 : (List.range' 70 56).all (balRow 407 T407) = true := by decide +kernel
theorem bal_407_3 : (List.range' 126 78).all (balRow 407 T407) = true := by decide +kernel
theorem small_407 : checkSmallFast 407 T407 = true := by decide +kernel
theorem checkN_407 : checkN 407 = true := by
  have h : (List.range' 0 31).all (balRow 407 T407) = true := bal_407_0
  have h : (List.range' 0 70).all (balRow 407 T407) = true := all_range'_append (by decide) (by decide) h bal_407_1
  have h : (List.range' 0 126).all (balRow 407 T407) = true := all_range'_append (by decide) (by decide) h bal_407_2
  have h : (List.range' 0 204).all (balRow 407 T407) = true := all_range'_append (by decide) (by decide) h bal_407_3
  exact checkN_of_parts tabV_407 (by decide +kernel) (by decide) h small_407

/-- The table value at n = 408. -/
def T408 : ℕ × ℕ := (349158120228662187127311921247076040467070620758609218844266362035138413190407112769228333159679294678496576128510555720606697852239594806988138, 94199037566971323263386496535245381207620477009584375636202005049981659512301334798998961833191112186003456)
theorem tabV_408 : tabV 408 = T408 := by decide +kernel
theorem bal_408_0 : (List.range' 0 31).all (balRow 408 T408) = true := by decide +kernel
theorem bal_408_1 : (List.range' 31 38).all (balRow 408 T408) = true := by decide +kernel
theorem bal_408_2 : (List.range' 69 55).all (balRow 408 T408) = true := by decide +kernel
theorem bal_408_3 : (List.range' 124 80).all (balRow 408 T408) = true := by decide +kernel
theorem small_408 : checkSmallFast 408 T408 = true := by decide +kernel
theorem checkN_408 : checkN 408 = true := by
  have h : (List.range' 0 31).all (balRow 408 T408) = true := bal_408_0
  have h : (List.range' 0 69).all (balRow 408 T408) = true := all_range'_append (by decide) (by decide) h bal_408_1
  have h : (List.range' 0 124).all (balRow 408 T408) = true := all_range'_append (by decide) (by decide) h bal_408_2
  have h : (List.range' 0 204).all (balRow 408 T408) = true := all_range'_append (by decide) (by decide) h bal_408_3
  exact checkN_of_parts tabV_408 (by decide +kernel) (by decide) h small_408

/-- The table value at n = 409. -/
def T409 : ℕ × ℕ := (2239940162006141568062555239706701157899581927714646046173329766221603517038349478649968774613701929636638007042050372879916175905898243148368976, 492475295922030938607625641399842878410108491020823479797345433150792272074458455307718384208600838963200000)
theorem tabV_409 : tabV 409 = T409 := by decide +kernel
theorem bal_409_0 : (List.range' 0 31).all (balRow 409 T409) = true := by decide +kernel
theorem bal_409_1 : (List.range' 31 38).all (balRow 409 T409) = true := by decide +kernel
theorem bal_409_2 : (List.range' 69 55).all (balRow 409 T409) = true := by decide +kernel
theorem bal_409_3 : (List.range' 124 81).all (balRow 409 T409) = true := by decide +kernel
theorem small_409 : checkSmallFast 409 T409 = true := by decide +kernel
theorem checkN_409 : checkN 409 = true := by
  have h : (List.range' 0 31).all (balRow 409 T409) = true := bal_409_0
  have h : (List.range' 0 69).all (balRow 409 T409) = true := all_range'_append (by decide) (by decide) h bal_409_1
  have h : (List.range' 0 124).all (balRow 409 T409) = true := all_range'_append (by decide) (by decide) h bal_409_2
  have h : (List.range' 0 205).all (balRow 409 T409) = true := all_range'_append (by decide) (by decide) h bal_409_3
  exact checkN_of_parts tabV_409 (by decide +kernel) (by decide) h small_409

end Sweep

theorem chunk_405_409 : (List.range' 405 5).all checkN = true := by
  have h : (List.range' 405 1).all checkN = true := all_range'_one Sweep.checkN_405
  have h : (List.range' 405 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_406
  have h : (List.range' 405 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_407
  have h : (List.range' 405 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_408
  have h : (List.range' 405 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_409
  exact h

end BGSpiderTable
end R3Cert
