-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 415 <= n <= 419, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 415. -/
def T415 : ℕ × ℕ := (107075935372063379887798459220165185466848071905819109407044012710535055715990601331978671507503790121237675757617548147977627267101195338568462628, 6807978490826155695311816866711427951141339779871863784718503267876552369157313686173898943299697997827276800)
theorem tabV_415 : tabV 415 = T415 := by decide +kernel
theorem bal_415_0 : (List.range' 0 31).all (balRow 415 T415) = true := by decide +kernel
theorem bal_415_1 : (List.range' 31 37).all (balRow 415 T415) = true := by decide +kernel
theorem bal_415_2 : (List.range' 68 52).all (balRow 415 T415) = true := by decide +kernel
theorem bal_415_3 : (List.range' 120 88).all (balRow 415 T415) = true := by decide +kernel
theorem small_415 : checkSmallFast 415 T415 = true := by decide +kernel
theorem checkN_415 : checkN 415 = true := by
  have h : (List.range' 0 31).all (balRow 415 T415) = true := bal_415_0
  have h : (List.range' 0 68).all (balRow 415 T415) = true := all_range'_append (by decide) (by decide) h bal_415_1
  have h : (List.range' 0 120).all (balRow 415 T415) = true := all_range'_append (by decide) (by decide) h bal_415_2
  have h : (List.range' 0 208).all (balRow 415 T415) = true := all_range'_append (by decide) (by decide) h bal_415_3
  exact checkN_of_parts tabV_415 (by decide +kernel) (by decide) h small_415

/-- The table value at n = 416. -/
def T416 : ℕ × ℕ := (975358045251558926218499031665575092349778833222268697321846868482079784291962645285924289953250745500389741714523931165526546864807335120988324950, 50543517213050543699203684248931242784195345131084515031832820770739206870799683571055307852987980840960000000)
theorem tabV_416 : tabV 416 = T416 := by decide +kernel
theorem bal_416_0 : (List.range' 0 31).all (balRow 416 T416) = true := by decide +kernel
theorem bal_416_1 : (List.range' 31 37).all (balRow 416 T416) = true := by decide +kernel
theorem bal_416_2 : (List.range' 68 52).all (balRow 416 T416) = true := by decide +kernel
theorem bal_416_3 : (List.range' 120 88).all (balRow 416 T416) = true := by decide +kernel
theorem small_416 : checkSmallFast 416 T416 = true := by decide +kernel
theorem checkN_416 : checkN 416 = true := by
  have h : (List.range' 0 31).all (balRow 416 T416) = true := bal_416_0
  have h : (List.range' 0 68).all (balRow 416 T416) = true := all_range'_append (by decide) (by decide) h bal_416_1
  have h : (List.range' 0 120).all (balRow 416 T416) = true := all_range'_append (by decide) (by decide) h bal_416_2
  have h : (List.range' 0 208).all (balRow 416 T416) = true := all_range'_append (by decide) (by decide) h bal_416_3
  exact checkN_of_parts tabV_416 (by decide +kernel) (by decide) h small_416

/-- The table value at n = 417. -/
def T417 : ℕ × ℕ := (388606454710380311653812210328679159683583065279411421315935408144156213453233483115030712654959152453981436696343773267551916954281400503850847712, 16339148377982773668748360480107427082739215471692473083324407842903725685977552846817357463919275194785464320)
theorem tabV_417 : tabV 417 = T417 := by decide +kernel
theorem bal_417_0 : (List.range' 0 31).all (balRow 417 T417) = true := by decide +kernel
theorem bal_417_1 : (List.range' 31 37).all (balRow 417 T417) = true := by decide +kernel
theorem bal_417_2 : (List.range' 68 52).all (balRow 417 T417) = true := by decide +kernel
theorem bal_417_3 : (List.range' 120 89).all (balRow 417 T417) = true := by decide +kernel
theorem small_417 : checkSmallFast 417 T417 = true := by decide +kernel
theorem checkN_417 : checkN 417 = true := by
  have h : (List.range' 0 31).all (balRow 417 T417) = true := bal_417_0
  have h : (List.range' 0 68).all (balRow 417 T417) = true := all_range'_append (by decide) (by decide) h bal_417_1
  have h : (List.range' 0 120).all (balRow 417 T417) = true := all_range'_append (by decide) (by decide) h bal_417_2
  have h : (List.range' 0 209).all (balRow 417 T417) = true := all_range'_append (by decide) (by decide) h bal_417_3
  exact checkN_of_parts tabV_417 (by decide +kernel) (by decide) h small_417

/-- The table value at n = 418. -/
def T418 : ℕ × ℕ := (3539893098479941818440691051081391237248311144574470318911685998223162415166653558501849776741469988406285981079850403592133042474482396337025387526, 121304441311321304878088842197434982682068828314602836076398769849774096489919240570532738847171154018304000000)
theorem tabV_418 : tabV 418 = T418 := by decide +kernel
theorem bal_418_0 : (List.range' 0 30).all (balRow 418 T418) = true := by decide +kernel
theorem bal_418_1 : (List.range' 30 37).all (balRow 418 T418) = true := by decide +kernel
theorem bal_418_2 : (List.range' 67 51).all (balRow 418 T418) = true := by decide +kernel
theorem bal_418_3 : (List.range' 118 91).all (balRow 418 T418) = true := by decide +kernel
theorem small_418 : checkSmallFast 418 T418 = true := by decide +kernel
theorem checkN_418 : checkN 418 = true := by
  have h : (List.range' 0 30).all (balRow 418 T418) = true := bal_418_0
  have h : (List.range' 0 67).all (balRow 418 T418) = true := all_range'_append (by decide) (by decide) h bal_418_1
  have h : (List.range' 0 118).all (balRow 418 T418) = true := all_range'_append (by decide) (by decide) h bal_418_2
  have h : (List.range' 0 209).all (balRow 418 T418) = true := all_range'_append (by decide) (by decide) h bal_418_3
  exact checkN_of_parts tabV_418 (by decide +kernel) (by decide) h small_418

/-- The table value at n = 419. -/
def T419 : ℕ × ℕ := (2004186483524425206120885417791797395310199799404187651799539959506669364059595768220385185219432647632661076522306185001456532520387827683723100668, 55725095520699143880783882058471646050605324345561697673653769906324285497439232867040250719051001716952530944)
theorem tabV_419 : tabV 419 = T419 := by decide +kernel
theorem bal_419_0 : (List.range' 0 30).all (balRow 419 T419) = true := by decide +kernel
theorem bal_419_1 : (List.range' 30 37).all (balRow 419 T419) = true := by decide +kernel
theorem bal_419_2 : (List.range' 67 51).all (balRow 419 T419) = true := by decide +kernel
theorem bal_419_3 : (List.range' 118 92).all (balRow 419 T419) = true := by decide +kernel
theorem small_419 : checkSmallFast 419 T419 = true := by decide +kernel
theorem checkN_419 : checkN 419 = true := by
  have h : (List.range' 0 30).all (balRow 419 T419) = true := bal_419_0
  have h : (List.range' 0 67).all (balRow 419 T419) = true := all_range'_append (by decide) (by decide) h bal_419_1
  have h : (List.range' 0 118).all (balRow 419 T419) = true := all_range'_append (by decide) (by decide) h bal_419_2
  have h : (List.range' 0 210).all (balRow 419 T419) = true := all_range'_append (by decide) (by decide) h bal_419_3
  exact checkN_of_parts tabV_419 (by decide +kernel) (by decide) h small_419

end Sweep

theorem chunk_415_419 : (List.range' 415 5).all checkN = true := by
  have h : (List.range' 415 1).all checkN = true := all_range'_one Sweep.checkN_415
  have h : (List.range' 415 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_416
  have h : (List.range' 415 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_417
  have h : (List.range' 415 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_418
  have h : (List.range' 415 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_419
  exact h

end BGSpiderTable
end R3Cert
