"""Tests for telperion.missions.judge: Comparator challenges from registered statements.

Pins, on a synthetic island and on the live registry:

  * the bridge module's TYPE is the registered statement (binders and conclusion verbatim,
    binders lifted into a `forall`), its PROOF is the artifact's fully qualified theorem, it
    imports the artifact and the island's AxiomGuard libs, and it keeps the statement's own
    `open` lines;
  * the signature splitter finds the top-level colon past binders that contain colons, and
    the last top-level `:=`;
  * a statement that declares anything besides its theorem is refused, per node, and reported
    as not consumable without sinking the island;
  * the config is self-check over the bridge theorem with the three standard axioms, nanoda on;
  * the Comparator tag follows the island toolchain (not the BG bridge's v4.32.0);
  * `--check` reports a stale, missing or extra file; `--shard I/N` partitions the nodes;
  * an out-of-tree island (bg: proof/formalization) path-requires its own directory and, with
    no AxiomGuard lib, imports the vocabulary mirror's home modules instead;
  * the live dbn, rvm_bridge, zeta_reflection and bg bundles are committed and in sync with
    the registry, and li_positivity renders (it is not yet in the CI matrix).

conjecture1_proved = False.
"""
from __future__ import annotations

import json
import sys
import textwrap
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from telperion.missions import judge  # noqa: E402

TELPERION = Path(__file__).resolve().parents[1]

HEADER = "-- DO NOT EDIT BY HAND — generated by telperion mission; node {slug}; sha256 0123456789abcdef\n"
LAKEFILE = ('name = "Isl"\ndefaultTargets = ["Art", "AxiomGuardIsl"]\n\n[[lean_lib]]\nname = "Art"\n\n'
            '[[lean_lib]]\nname = "Vocab"\n\n[[lean_lib]]\nname = "AxiomGuardIsl"\n')


def _island(tmp_path: Path, *, artifact: str, statement: str, slug="X_node", campaign="x",
            status="proved", artifact_name="Art.lean", extra_nodes=()) -> Path:
    """A minimal telperion/ tree: one island with one artifact, one campaign with one node."""
    tel = tmp_path / "telperion"
    lean = tel / "examples" / "isl" / "lean"
    lean.mkdir(parents=True)
    (lean / "lakefile.toml").write_text(LAKEFILE)
    (lean / "lean-toolchain").write_text("leanprover/lean4:v4.34.0-rc1\n")
    (lean / artifact_name).parent.mkdir(parents=True, exist_ok=True)
    (lean / artifact_name).write_text(artifact)
    camp = tel / "missions" / campaign
    (camp / "nodes").mkdir(parents=True)
    (camp / "lean" / "Statements").mkdir(parents=True)
    (camp / "mission.toml").write_text(
        f'name = "{campaign}.goal"\ntitle = "t"\ndescription = "d"\ngoal_node = "{slug}"\n'
        'environment_toolchain = "leanprover/lean4:v4.34.0-rc1"\nenvironment_mathlib_rev = "x"\n')
    for sl, st, art_text, art_name in ((slug, statement, artifact, artifact_name), *extra_nodes):
        if art_name != artifact_name:
            (lean / art_name).write_text(art_text)
        (camp / "nodes" / f"{sl}.toml").write_text(textwrap.dedent(f"""\
            name = "{sl.replace('_', '.', 1)}"
            title = "node"
            kind = "lemma"
            status = "{status}"
            statement_module = "Statements.{sl}"
            depends_on = []

            [proof]
            artifact = "../../examples/isl/lean/{art_name}"
            artifact_kind = "lean_module"
            via = "direct"
            closure_clean = true
            """))
        (camp / "lean" / "Statements" / f"{sl}.lean").write_text(HEADER.format(slug=sl) + st)
    return tel


ARTIFACT_NS = textwrap.dedent("""\
    import Mathlib
    import Vocab
    open Real

    namespace Isl.Deep
    /-- the node theorem -/
    theorem node_thm {x : ℝ} (hx : 0 < x) [inst : Nonempty ℕ] : 0 < x ^ 2 := by
      positivity
    end Isl.Deep
    """)
STATEMENT_NS = ("import Statements.Defs\nopen Real\n\n"
                "theorem node_thm {x : ℝ} (hx : 0 < x) [inst : Nonempty ℕ] : 0 < x ^ 2 := by sorry\n")


def test_bridge_module_has_registered_type_and_artifact_proof(tmp_path):
    tel = _island(tmp_path, artifact=ARTIFACT_NS, statement=STATEMENT_NS)
    b = judge.build_bundle(tel, "isl")
    assert b.toolchain == "leanprover/lean4:v4.34.0-rc1" and b.comparator_tag == "v4.34.0-rc1"
    assert b.package == "Isl" and b.skipped == ()
    [c] = b.challenges
    assert c.theorem == "Isl.Deep.node_thm" and c.solution_module == "Art"
    assert c.challenge_module == "MissionChallenges.X_node"
    assert c.bridge_theorem == "MissionJudge.X_node"
    text = c.challenge_text
    # imports: the artifact, then the island's AxiomGuard libs; never the campaign mirror
    assert "import Art\nimport AxiomGuardIsl\n" in text and "Statements.Defs" not in text
    # the ARTIFACT's open lines and namespace, not the statement file's
    assert "\nopen Real\n" in text
    assert "\nnamespace Isl.Deep\n" in text and text.rstrip().endswith("end Isl.Deep")
    # the registered signature, binders lifted into a forall, conclusion verbatim
    assert "theorem _root_.MissionJudge.X_node :\n" in text
    assert "∀ {x : ℝ} (hx : 0 < x) [inst : Nonempty ℕ], 0 < x ^ 2 :=" in text
    # proved by the artifact's fully qualified constant, nothing else
    assert ":=\n  Isl.Deep.node_thm\n" in text
    assert "sorry" not in text.split("-/", 1)[1]
    assert "DO NOT EDIT BY HAND" in text
    # config: self-check over the bridge theorem
    assert c.config["challenge_module"] == c.config["solution_module"] == "MissionChallenges.X_node"
    assert c.config["theorem_names"] == ["MissionJudge.X_node"]
    assert set(c.config["permitted_axioms"]) == {"propext", "Quot.sound", "Classical.choice"}
    assert c.config["enable_nanoda"] is True


def test_binderless_statement_has_no_forall(tmp_path):
    art = "import Mathlib\n\ntheorem plain : (1 : ℕ) = 1 := rfl\n"
    stmt = "import Statements.Defs\n\ntheorem plain : (1 : ℕ) = 1 := by sorry\n"
    tel = _island(tmp_path, artifact=art, statement=stmt)
    [c] = judge.build_bundle(tel, "isl").challenges
    assert c.theorem == "plain"
    assert "theorem MissionJudge.X_node :\n    (1 : ℕ) = 1 :=\n  plain\n" in c.challenge_text
    body_part = c.challenge_text.split("-/", 1)[1]
    assert "∀" not in body_part and "namespace" not in body_part


def test_artifact_in_subdirectory_gets_dotted_solution_module(tmp_path):
    art = "import Mathlib\n\ntheorem sub : (1 : ℕ) = 1 := rfl\n"
    stmt = "import Statements.Defs\n\ntheorem sub : (1 : ℕ) = 1 := by sorry\n"
    tel = _island(tmp_path, artifact=art, statement=stmt, artifact_name="Probes/Deep.lean")
    [c] = judge.build_bundle(tel, "isl").challenges
    assert c.solution_module == "Probes.Deep" and "import Probes.Deep\n" in c.challenge_text


def test_split_signature_handles_colons_in_binders_and_ascriptions():
    body = ("theorem t (f : ℕ → ℕ) {s : Set ℕ} [h : DecidableEq ℕ] ⦃k : ℕ⦄ :\n"
            "    (⟨1, by decide⟩ : Fin 2) = ⟨1, by decide⟩ ∧ ∀ x : ℕ, f x = (x : ℕ) := by sorry")
    short, binders, concl = judge.split_signature(body)
    assert short == "t"
    assert binders == "(f : ℕ → ℕ) {s : Set ℕ} [h : DecidableEq ℕ] ⦃k : ℕ⦄"
    assert concl == "(⟨1, by decide⟩ : Fin 2) = ⟨1, by decide⟩ ∧ ∀ x : ℕ, f x = (x : ℕ)"


def test_split_signature_keeps_let_assignments_inside_the_conclusion():
    body = "theorem t : (let y := 2; y = 2) := by sorry"
    assert judge.split_signature(body)[2] == "(let y := 2; y = 2)"


def test_split_signature_refuses_extra_declarations():
    with pytest.raises(judge.JudgeError, match="declares `def`"):
        judge.split_signature("def helper : ℕ := 1\n\ntheorem t : helper = 1 := by sorry")
    with pytest.raises(judge.JudgeError, match="declares `namespace`"):
        judge.split_signature("namespace N\ntheorem t : True := by sorry\nend N")
    with pytest.raises(judge.JudgeError, match="expected exactly one"):
        judge.split_signature("theorem a : True := by sorry\ntheorem b : True := by sorry")


def test_unconsumable_node_is_reported_not_fatal(tmp_path):
    art_ok = "import Mathlib\n\ntheorem fine : (1 : ℕ) = 1 := rfl\n"
    stmt_ok = "import Statements.Defs\n\ntheorem fine : (1 : ℕ) = 1 := by sorry\n"
    art_bad = "import Mathlib\n\ndef k : ℕ := 1\ntheorem bad : k = 1 := rfl\n"
    stmt_bad = "import Statements.Defs\n\ndef k : ℕ := 1\ntheorem bad : k = 1 := by sorry\n"
    tel = _island(tmp_path, artifact=art_ok, statement=stmt_ok,
                  extra_nodes=[("Y_bad", stmt_bad, art_bad, "Bad.lean")])
    b = judge.build_bundle(tel, "isl")
    assert [c.slug for c in b.challenges] == ["X_node"]
    assert len(b.skipped) == 1 and b.skipped[0].startswith("x/Y_bad: statement declares `def`")
    man = json.loads(b.files()["MANIFEST.json"])
    assert man["not_consumable"] == list(b.skipped)


_IDENT = __import__("re").compile(r"^[A-Za-z_][\w'.]*$")


def test_configs_stdout_is_machine_readable_even_with_skipped_nodes(tmp_path, capsys):
    """CI builds lake targets from `--configs` stdout; diagnostics must never land there.

    Regression: a `::warning:: not consumable` line on stdout became the target
    `MissionChallenges.::warning::zeta_reflection:` and lake died with "too many ':'"."""
    art_ok = "import Mathlib\n\ntheorem fine : (1 : ℕ) = 1 := rfl\n"
    stmt_ok = "import Statements.Defs\n\ntheorem fine : (1 : ℕ) = 1 := by sorry\n"
    art_bad = "import Mathlib\n\ndef k : ℕ := 1\ntheorem bad : k = 1 := rfl\n"
    stmt_bad = "import Statements.Defs\n\ndef k : ℕ := 1\ntheorem bad : k = 1 := by sorry\n"
    tel = _island(tmp_path, artifact=art_ok, statement=stmt_ok,
                  extra_nodes=[("Y_bad", stmt_bad, art_bad, "Bad.lean")])
    rc = judge.main(["--island", "isl", "--telperion", str(tel), "--configs", "--shard", "0/1"])
    out, err = capsys.readouterr()
    assert rc == 0
    assert "::warning::" in err and "Y_bad" in err
    assert "::" not in out
    for line in out.splitlines():
        # Columns 7-8 name a compositional part and its statement exports; an ordinary node
        # leaves them empty (the per-PR workflow reads only the first six).
        slug, cfg, sol, thm, bridge, kernel, part, exports = line.split("\t")
        assert _IDENT.match(slug) and _IDENT.match(sol) and _IDENT.match(thm) and _IDENT.match(bridge), line
        assert kernel in ("nanoda", "lean-kernel-only")
        assert part == "" and exports == "", line
        assert cfg == f"{slug}.comparator.json"
    # the other diagnostic paths are stderr too
    assert judge.main(["--island", "nope", "--telperion", str(tel), "--configs"]) == 2
    out, err = capsys.readouterr()
    assert out == "" and "::error::" in err


def test_statement_name_not_suffix_of_theorem_is_refused(tmp_path):
    art = "import Mathlib\n\nnamespace A\ntheorem other : True := trivial\nend A\n"
    stmt = "import Statements.Defs\n\ntheorem other : True := by sorry\n"
    tel = _island(tmp_path, artifact=art, statement=stmt)
    [c] = judge.build_bundle(tel, "isl").challenges
    assert c.theorem == "A.other"           # resolved by guard_anchors from the artifact
    with pytest.raises(judge.JudgeError, match="does not end with"):
        judge.render_challenge(slug="s", campaign="c", theorem="A.different", solution_module="Art",
                               guard_modules=[], statement_text=HEADER.format(slug="s") + stmt,
                               artifact_text=art)


def test_artifact_context_collects_namespace_and_opens():
    art = textwrap.dedent("""\
        import Mathlib
        open Filter  Topology
        section
        open scoped BigOperators
        end
        namespace A.B
        open Real in
        theorem thm : True := trivial
        end A.B
        """)
    stmt = HEADER.format(slug="s") + "import X\nopen Quasicrystal\n\ntheorem thm : True := by sorry\n"
    ns, opens = judge.artifact_context(art, stmt)
    assert ns == "A.B"
    assert opens == ["open Filter Topology", "open scoped BigOperators", "open Real"]
    text = judge.render_challenge(slug="s", campaign="c", theorem="A.B.thm", solution_module="Art",
                                  guard_modules=["AxiomGuardIsl"], statement_text=stmt, artifact_text=art)
    assert "open Quasicrystal" not in text
    assert "namespace A.B\n\nopen Filter Topology\nopen scoped BigOperators\nopen Real\n" in text
    with pytest.raises(judge.JudgeError, match="does not declare"):
        judge.artifact_context("import Mathlib\ntheorem other : True := trivial\n", stmt)


def test_heavy_certificates_turns_nanoda_off_for_that_node_only(tmp_path, capsys):
    """`heavy_certificates = true` in a node toml -> enable_nanoda false in ITS config and a
    `lean-kernel-only` column in --configs; other nodes keep nanoda."""
    art_a = "import Mathlib\n\ntheorem a : (1 : ℕ) = 1 := rfl\n"
    stmt_a = "import Statements.Defs\n\ntheorem a : (1 : ℕ) = 1 := by sorry\n"
    art_b = "import Mathlib\n\ntheorem b : (2 : ℕ) = 2 := rfl\n"
    stmt_b = "import Statements.Defs\n\ntheorem b : (2 : ℕ) = 2 := by sorry\n"
    tel = _island(tmp_path, artifact=art_a, statement=stmt_a,
                  extra_nodes=[("Y_heavy", stmt_b, art_b, "Heavy.lean")])
    toml = tel / "missions" / "x" / "nodes" / "Y_heavy.toml"
    toml.write_text("heavy_certificates = true\n" + toml.read_text())   # top-level, not under [proof]
    b = judge.build_bundle(tel, "isl")
    by = {c.slug: c for c in b.challenges}
    assert by["X_node"].nanoda is True and by["X_node"].config["enable_nanoda"] is True
    assert by["Y_heavy"].nanoda is False and by["Y_heavy"].config["enable_nanoda"] is False
    man = json.loads(b.files()["MANIFEST.json"])
    assert {n["slug"]: n["nanoda"] for n in man["nodes"]} == {"X_node": True, "Y_heavy": False}
    assert judge.main(["--island", "isl", "--telperion", str(tel), "--configs"]) == 0
    cols = {ln.split("\t")[0]: ln.split("\t")[5] for ln in capsys.readouterr().out.splitlines()}
    assert cols == {"X_node": "nanoda", "Y_heavy": "lean-kernel-only"}


def test_a_heavy_node_does_not_poison_the_nodes_after_it(tmp_path):
    """The bug this pins: `heavy` is `build_bundle`'s PARAMETER (the heavy-judge mode), and the
    per-node `heavy_certificates` read used to reassign it.  The first node carrying the flag
    then flipped the mode for every node SORTED AFTER it, so the next ordinary node hit the heavy
    path's "judge_via is not heavy" refusal and the whole bundle failed to build.

    It was invisible on main, where no node carries the flag, and invisible to the test above,
    whose heavy node sorts last.  It was fatal on exactly the branches that use the flag."""
    art_a = "import Mathlib\n\ntheorem a : (1 : ℕ) = 1 := rfl\n"
    stmt_a = "import Statements.Defs\n\ntheorem a : (1 : ℕ) = 1 := by sorry\n"
    art_b = "import Mathlib\n\ntheorem b : (2 : ℕ) = 2 := rfl\n"
    stmt_b = "import Statements.Defs\n\ntheorem b : (2 : ℕ) = 2 := by sorry\n"
    art_c = "import Mathlib\n\ntheorem c : (3 : ℕ) = 3 := rfl\n"
    stmt_c = "import Statements.Defs\n\ntheorem c : (3 : ℕ) = 3 := by sorry\n"
    tel = _island(tmp_path, artifact=art_a, statement=stmt_a,
                  extra_nodes=[("Y_heavy", stmt_b, art_b, "Heavy.lean"),
                               ("Z_after", stmt_c, art_c, "After.lean")])
    toml = tel / "missions" / "x" / "nodes" / "Y_heavy.toml"
    toml.write_text("heavy_certificates = true\n" + toml.read_text())
    b = judge.build_bundle(tel, "isl")          # must not raise
    by = {c.slug: c for c in b.challenges}
    assert set(by) == {"X_node", "Y_heavy", "Z_after"}
    assert by["Y_heavy"].nanoda is False, "the flagged node keeps nanoda off"
    assert by["Z_after"].nanoda is True, "a node sorted after it must be unaffected"
    assert b.excluded == (), "nothing is excluded by rule here"


def test_unknown_toolchain_is_refused():
    with pytest.raises(judge.JudgeError, match="no known Comparator tag"):
        judge.comparator_tag("leanprover/lean4:v4.99.0")


def test_only_proved_nodes_are_judged(tmp_path):
    tel = _island(tmp_path, artifact=ARTIFACT_NS, statement=STATEMENT_NS, status="open")
    with pytest.raises(judge.JudgeError, match="no proved registry node"):
        judge.build_bundle(tel, "isl")


def test_nanoda_off_when_requested(tmp_path):
    tel = _island(tmp_path, artifact=ARTIFACT_NS, statement=STATEMENT_NS)
    [c] = judge.build_bundle(tel, "isl", enable_nanoda=False).challenges
    assert c.config["enable_nanoda"] is False


def test_shard_partitions_slug_order():
    def ch(slug):
        return judge.Challenge(slug, "c", "t", "s", "m", "b", True, "", {}, "a", "s")
    cs = [ch("c"), ch("a"), ch("b"), ch("d"), ch("e")]
    assert [c.slug for c in judge.shard(cs, None)] == ["a", "b", "c", "d", "e"]
    parts = [[c.slug for c in judge.shard(cs, f"{i}/3")] for i in range(3)]
    assert parts == [["a", "d"], ["b", "e"], ["c"]]
    with pytest.raises(judge.JudgeError):
        judge.shard(cs, "3/3")
    with pytest.raises(judge.JudgeError):
        judge.shard(cs, "x")


def test_bundle_files_and_check(tmp_path):
    tel = _island(tmp_path, artifact=ARTIFACT_NS, statement=STATEMENT_NS)
    b = judge.build_bundle(tel, "isl")
    out = tmp_path / "bundle"
    judge.write_bundle(b, out)
    assert sorted(p.name for p in out.iterdir()) == sorted(
        ["MANIFEST.json", "MissionChallenges", "MissionChallenges.lean", "X_node.comparator.json",
         "lakefile.toml", "lean-toolchain"])
    assert (out / "lean-toolchain").read_text().strip() == "leanprover/lean4:v4.34.0-rc1"
    lakefile = (out / "lakefile.toml").read_text()
    assert 'name = "Isl"' in lakefile and 'path = "../../../examples/isl/lean"' in lakefile
    assert (out / "MissionChallenges.lean").read_text() == "import MissionChallenges.X_node\n"
    man = json.loads((out / "MANIFEST.json").read_text())
    assert man["comparator_tag"] == "v4.34.0-rc1"
    assert man["nodes"][0]["theorem"] == "Isl.Deep.node_thm"
    assert man["nodes"][0]["bridge_theorem"] == "MissionJudge.X_node"
    assert judge.check_bundle(b, out) == []
    # a lake-generated manifest and .lake are tolerated
    (out / "lake-manifest.json").write_text("{}")
    (out / ".lake").mkdir()
    (out / ".lake" / "x").write_text("x")
    assert judge.check_bundle(b, out) == []
    # drift in any of: challenge text, an extra file, a missing file
    (out / "MissionChallenges" / "X_node.lean").write_text("tampered\n")
    assert any(p.startswith("stale: MissionChallenges/X_node.lean") for p in judge.check_bundle(b, out))
    (out / "stray.lean").write_text("")
    assert any("unexpected file in bundle: stray.lean" == p for p in judge.check_bundle(b, out))
    (out / "X_node.comparator.json").unlink()
    assert any("missing: X_node.comparator.json" == p for p in judge.check_bundle(b, out))


def test_cli_list_configs_check_and_write(tmp_path, capsys):
    tel = _island(tmp_path, artifact=ARTIFACT_NS, statement=STATEMENT_NS)
    out = tmp_path / "b"
    common = ["--island", "isl", "--telperion", str(tel), "--out", str(out)]
    assert judge.main([*common, "--list"]) == 0
    assert "Isl.Deep.node_thm" in capsys.readouterr().out
    assert judge.main([*common, "--configs", "--shard", "0/1"]) == 0
    line = capsys.readouterr().out.strip().split("\t")
    assert line == ["X_node", "X_node.comparator.json", "Art", "Isl.Deep.node_thm", "MissionJudge.X_node", "nanoda"]
    assert judge.main([*common, "--check"]) == 1
    assert judge.main(common) == 0
    assert judge.main([*common, "--check"]) == 0
    assert judge.main(["--island", "nope", "--telperion", str(tel)]) == 2


# ---------------------------------------------------------------------------
# out-of-tree islands (bg: proof/formalization) and the vocabulary-home shadowing guard
# ---------------------------------------------------------------------------

MIRROR = textwrap.dedent("""\
    /- vocabulary mirror -/
    import Mathlib
    namespace Pkg
    -- ===== Alpha.lean:3 =====
    def a : ℕ := 1
    -- ===== Beta.lean:4 / Sub/Gamma.lean:5-6 (context) =====
    def b : ℕ := 2
    -- ===== PROVISIONAL (registry-only; no island counterpart) =====
    end Pkg
    """)


def _oot_island(tmp_path: Path, monkeypatch) -> Path:
    """telperion/ + ../proof/pkg (an island outside telperion/examples, no AxiomGuard lib)."""
    tel = tmp_path / "telperion"
    pkg = tmp_path / "proof" / "pkg"
    (pkg / "Pkg" / "Sub").mkdir(parents=True)
    (pkg / "lakefile.toml").write_text('name = "Pkg"\n\n[[lean_lib]]\nname = "Pkg"\nglobs = ["Pkg.+"]\n')
    (pkg / "lean-toolchain").write_text("leanprover/lean4:v4.32.0\n")
    for m in ("Alpha", "Beta", "Sub/Gamma"):
        (pkg / "Pkg" / f"{m}.lean").write_text("import Mathlib\n")
    (pkg / "Pkg" / "Art.lean").write_text(
        "import Pkg.Alpha\n\nnamespace Pkg\ntheorem oot_thm : (1 : ℕ) = 1 := rfl\nend Pkg\n")
    camp = tel / "missions" / "oc"
    (camp / "nodes").mkdir(parents=True)
    (camp / "lean" / "Statements").mkdir(parents=True)
    (camp / "lean" / "Statements" / "OcDefs.lean").write_text(MIRROR)
    (camp / "lean" / "Statements" / "OC_node.lean").write_text(
        HEADER.format(slug="OC_node") + "import Statements.OcDefs\nopen Pkg\n\n"
        "theorem oot_thm : (1 : ℕ) = 1 := by sorry\n")
    (camp / "nodes" / "OC_node.toml").write_text(textwrap.dedent("""\
        name = "OC.node"
        title = "node"
        kind = "lemma"
        status = "proved"
        statement_module = "Statements.OC_node"
        depends_on = []

        [proof]
        artifact = "../../../proof/pkg/Pkg/Art.lean"
        artifact_kind = "lean_module"
        """))
    monkeypatch.setitem(judge.OUT_OF_TREE_ISLANDS, "oot", judge.OutOfTreeIsland(
        lean_dir="../proof/pkg", vocab_mirror="missions/oc/lean/Statements/OcDefs.lean"))
    return tel


def test_vocabulary_home_modules_from_mirror_headers(tmp_path, monkeypatch):
    _oot_island(tmp_path, monkeypatch)
    lean = tmp_path / "proof" / "pkg"
    assert judge.vocabulary_home_modules(lean, MIRROR) == ["Pkg.Alpha", "Pkg.Beta", "Pkg.Sub.Gamma"]
    # a header naming no island file is an error, not a silently thinner guard
    with pytest.raises(judge.JudgeError, match="Delta.lean; 0 match"):
        judge.vocabulary_home_modules(lean, MIRROR + "-- ===== Delta.lean:1 =====\n")


def test_out_of_tree_island_bundle(tmp_path, monkeypatch):
    tel = _oot_island(tmp_path, monkeypatch)
    b = judge.build_bundle(tel, "oot")
    assert b.package == "Pkg" and b.comparator_tag == "v4.32.0"
    assert b.require_path == "../../../../proof/pkg"
    assert 'path = "../../../../proof/pkg"' in b.files()["lakefile.toml"]
    [c] = b.challenges
    assert c.theorem == "Pkg.oot_thm" and c.solution_module == "Pkg.Art"
    # the artifact first, then the mirror's home modules; the comment says which guard it is
    assert "import Pkg.Art\nimport Pkg.Alpha\nimport Pkg.Beta\nimport Pkg.Sub.Gamma\n" in c.challenge_text
    assert "vocabulary mirror copies" in c.challenge_text
    assert "AxiomGuard imports" not in c.challenge_text
    assert ":=\n  Pkg.oot_thm\n" in c.challenge_text


def test_in_tree_island_keeps_examples_require_path(tmp_path):
    tel = _island(tmp_path, artifact=ARTIFACT_NS, statement=STATEMENT_NS)
    b = judge.build_bundle(tel, "isl")
    assert 'path = "../../../examples/isl/lean"' in b.files()["lakefile.toml"]
    assert "AxiomGuard imports load the whole island" in b.challenges[0].challenge_text


# ---------------------------------------------------------------------------
# live registry
# ---------------------------------------------------------------------------

def _live() -> bool:
    return (TELPERION / "missions" / "rh" / "mission.toml").exists()


@pytest.mark.parametrize("island", ["dbn", "rvm_bridge", "zeta_reflection", "bg"])
def test_live_committed_bundle_is_in_sync(island):
    """The committed challenges ARE the registry statements; CI runs the same check."""
    if not _live():
        pytest.skip("live registry not present")
    b = judge.build_bundle(TELPERION, island)
    # zeta_reflection: AND_g2_reflected_band declares a namespace in its statement (reported)
    assert len(b.skipped) == (1 if island == "zeta_reflection" else 0)
    assert judge.check_bundle(b, judge.default_out(TELPERION, island)) == []


@pytest.mark.parametrize("island,expected", [("dbn", 3), ("rvm_bridge", 52), ("zeta_reflection", 5), ("li_positivity", 24),
                                             ("bg", 9)])
def test_live_islands_render(island, expected):
    if not _live():
        pytest.skip("live registry not present")
    b = judge.build_bundle(TELPERION, island)
    assert len(b.challenges) >= expected
    for c in b.challenges:
        assert f":=\n  {c.theorem}\n" in c.challenge_text
        assert c.config["theorem_names"] == [c.bridge_theorem]
