"""Regenerate the emitter table in telperion/README.md from the emitter modules' own docstrings.

    python3 scripts/gen_emitter_list.py

Writes between the markers <!-- EMITTERS:BEGIN --> and <!-- EMITTERS:END -->.
"""
import ast, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "telperion"
SRC = ROOT / "src" / "telperion"


def first_sentence(doc: str) -> str:
    para = " ".join(doc.strip().split("\n\n")[0].split())
    m = re.match(r"(.+?[.!?])(\s|$)", para)
    s = m.group(1) if m and len(m.group(1)) >= 30 else para
    s = s.replace("``", "`").replace("|", "\\|")
    return s if len(s) <= 240 else s[:237].rstrip() + "…"


def kinds(src: str) -> list[str]:
    ks = re.findall(r"""\bkind\s*(?::\s*str\s*)?=\s*["']([a-z0-9_]+)["']""", src)
    return sorted(set(ks))


rows = []
for f in sorted(p for p in SRC.glob("emit*.py") if p.name != "emitter_sensitivity.py"):
    src = f.read_text()
    doc = ast.get_docstring(ast.parse(src)) or ""
    ks = ", ".join(f"`{k}`" for k in kinds(src)) or "—"
    rows.append(f"| `{f.name}` | {ks} | {first_sentence(doc)} |")

table = "\n".join([
    f"All {len(rows)} emitter modules in `src/telperion/`, in alphabetical order. The *kind* is the name an",
    "emitter registers under (a module may register several); the summary is the first sentence of the",
    "module's own docstring, so it uses the development repository's vocabulary. Generated by",
    "`scripts/gen_emitter_list.py`.",
    "",
    "| module | kind | summary |",
    "|---|---|---|",
    *rows,
])
readme = ROOT / "README.md"
text = readme.read_text()
begin, end = "<!-- EMITTERS:BEGIN -->", "<!-- EMITTERS:END -->"
new = f"{begin}\n{table}\n{end}"
if begin in text:
    text = re.sub(re.escape(begin) + r".*?" + re.escape(end), lambda _: new, text, flags=re.S)
else:
    raise SystemExit("markers not found in telperion/README.md")
readme.write_text(text)
print(f"wrote {len(rows)} emitters")
