-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 440 <= n <= 444, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 440. -/
def T440 : ℕ × ℕ := (116224779657703456633265104316547084171248776475310924178900376988113460221195012280136731549455965145910720501848672966523356044259045882401239148875680442, 42309794747197498131706280822172916445829968484593140826292677151098068618426084213863894064464649451760254976000000)
theorem tabV_440 : tabV 440 = T440 := by decide +kernel
theorem bal_440_0 : (List.range' 0 29).all (balRow 440 T440) = true := by decide +kernel
theorem bal_440_1 : (List.range' 29 34).all (balRow 440 T440) = true := by decide +kernel
theorem bal_440_2 : (List.range' 63 44).all (balRow 440 T440) = true := by decide +kernel
theorem bal_440_3 : (List.range' 107 83).all (balRow 440 T440) = true := by decide +kernel
theorem bal_440_4 : (List.range' 190 30).all (balRow 440 T440) = true := by decide +kernel
theorem small_440 : checkSmallFast 440 T440 = true := by decide +kernel
theorem checkN_440 : checkN 440 = true := by
  have h : (List.range' 0 29).all (balRow 440 T440) = true := bal_440_0
  have h : (List.range' 0 63).all (balRow 440 T440) = true := all_range'_append (by decide) (by decide) h bal_440_1
  have h : (List.range' 0 107).all (balRow 440 T440) = true := all_range'_append (by decide) (by decide) h bal_440_2
  have h : (List.range' 0 190).all (balRow 440 T440) = true := all_range'_append (by decide) (by decide) h bal_440_3
  have h : (List.range' 0 220).all (balRow 440 T440) = true := all_range'_append (by decide) (by decide) h bal_440_4
  exact checkN_of_parts tabV_440 (by decide +kernel) (by decide) h small_440

/-- The table value at n = 441. -/
def T441 : ℕ × ℕ := (65899594584337128141059804469067757563484717503373112366776565843634768313947191898773139600283984504128706386423403198633560622392932066019022612043540240, 19461315043658399115990477109296304042195402200076924007762266488884890679156209393363311813225121205940676743659520)
theorem tabV_441 : tabV 441 = T441 := by decide +kernel
theorem bal_441_0 : (List.range' 0 29).all (balRow 441 T441) = true := by decide +kernel
theorem bal_441_1 : (List.range' 29 34).all (balRow 441 T441) = true := by decide +kernel
theorem bal_441_2 : (List.range' 63 44).all (balRow 441 T441) = true := by decide +kernel
theorem bal_441_3 : (List.range' 107 82).all (balRow 441 T441) = true := by decide +kernel
theorem bal_441_4 : (List.range' 189 32).all (balRow 441 T441) = true := by decide +kernel
theorem small_441 : checkSmallFast 441 T441 = true := by decide +kernel
theorem checkN_441 : checkN 441 = true := by
  have h : (List.range' 0 29).all (balRow 441 T441) = true := bal_441_0
  have h : (List.range' 0 63).all (balRow 441 T441) = true := all_range'_append (by decide) (by decide) h bal_441_1
  have h : (List.range' 0 107).all (balRow 441 T441) = true := all_range'_append (by decide) (by decide) h bal_441_2
  have h : (List.range' 0 189).all (balRow 441 T441) = true := all_range'_append (by decide) (by decide) h bal_441_3
  have h : (List.range' 0 221).all (balRow 441 T441) = true := all_range'_append (by decide) (by decide) h bal_441_4
  exact checkN_of_parts tabV_441 (by decide +kernel) (by decide) h small_441

/-- The table value at n = 442. -/
def T442 : ℕ × ℕ := (421830277020602529416102181046202906523606238126545626939161602229503931532860500377142399840494012962935975087505818428807610613143652686996212455004426538, 101543507393273995516095073973214999469991924363023537983102425162635364684222602113273345754715158684224611942400000)
theorem tabV_442 : tabV 442 = T442 := by decide +kernel
theorem bal_442_0 : (List.range' 0 28).all (balRow 442 T442) = true := by decide +kernel
theorem bal_442_1 : (List.range' 28 33).all (balRow 442 T442) = true := by decide +kernel
theorem bal_442_2 : (List.range' 61 43).all (balRow 442 T442) = true := by decide +kernel
theorem bal_442_3 : (List.range' 104 75).all (balRow 442 T442) = true := by decide +kernel
theorem bal_442_4 : (List.range' 179 42).all (balRow 442 T442) = true := by decide +kernel
theorem small_442 : checkSmallFast 442 T442 = true := by decide +kernel
theorem checkN_442 : checkN 442 = true := by
  have h : (List.range' 0 28).all (balRow 442 T442) = true := bal_442_0
  have h : (List.range' 0 61).all (balRow 442 T442) = true := all_range'_append (by decide) (by decide) h bal_442_1
  have h : (List.range' 0 104).all (balRow 442 T442) = true := all_range'_append (by decide) (by decide) h bal_442_2
  have h : (List.range' 0 179).all (balRow 442 T442) = true := all_range'_append (by decide) (by decide) h bal_442_3
  have h : (List.range' 0 221).all (balRow 442 T442) = true := all_range'_append (by decide) (by decide) h bal_442_4
  exact checkN_of_parts tabV_442 (by decide +kernel) (by decide) h small_442

/-- The table value at n = 443. -/
def T443 : ℕ × ℕ := (231982000935598810116630425397716616131925884308278827497159446082668145113194370679109257813641832407426989655618572029169746598995587445111445653198756788, 45409735101869597937311113255024709431789271800179489351445288474064744918031155251181060897525282813861579068538880)
theorem tabV_443 : tabV 443 = T443 := by decide +kernel
theorem bal_443_0 : (List.range' 0 28).all (balRow 443 T443) = true := by decide +kernel
theorem bal_443_1 : (List.range' 28 33).all (balRow 443 T443) = true := by decide +kernel
theorem bal_443_2 : (List.range' 61 43).all (balRow 443 T443) = true := by decide +kernel
theorem bal_443_3 : (List.range' 104 74).all (balRow 443 T443) = true := by decide +kernel
theorem bal_443_4 : (List.range' 178 44).all (balRow 443 T443) = true := by decide +kernel
theorem small_443 : checkSmallFast 443 T443 = true := by decide +kernel
theorem checkN_443 : checkN 443 = true := by
  have h : (List.range' 0 28).all (balRow 443 T443) = true := bal_443_0
  have h : (List.range' 0 61).all (balRow 443 T443) = true := all_range'_append (by decide) (by decide) h bal_443_1
  have h : (List.range' 0 104).all (balRow 443 T443) = true := all_range'_append (by decide) (by decide) h bal_443_2
  have h : (List.range' 0 178).all (balRow 443 T443) = true := all_range'_append (by decide) (by decide) h bal_443_3
  have h : (List.range' 0 222).all (balRow 443 T443) = true := all_range'_append (by decide) (by decide) h bal_443_4
  exact checkN_of_parts tabV_443 (by decide +kernel) (by decide) h small_443

/-- The table value at n = 444. -/
def T444 : ℕ × ℕ := (1531005014952060041822838662194081310707978203791820841603149657078534970543076948817552336495333661853565613213680675697273841830873517726292990219458426034, 243704417743857589238628177535715998727980618471256491159445820390324875242134245071856029811316380842139068661760000)
theorem tabV_444 : tabV 444 = T444 := by decide +kernel
theorem bal_444_0 : (List.range' 0 28).all (balRow 444 T444) = true := by decide +kernel
theorem bal_444_1 : (List.range' 28 33).all (balRow 444 T444) = true := by decide +kernel
theorem bal_444_2 : (List.range' 61 42).all (balRow 444 T444) = true := by decide +kernel
theorem bal_444_3 : (List.range' 103 71).all (balRow 444 T444) = true := by decide +kernel
theorem bal_444_4 : (List.range' 174 48).all (balRow 444 T444) = true := by decide +kernel
theorem small_444 : checkSmallFast 444 T444 = true := by decide +kernel
theorem checkN_444 : checkN 444 = true := by
  have h : (List.range' 0 28).all (balRow 444 T444) = true := bal_444_0
  have h : (List.range' 0 61).all (balRow 444 T444) = true := all_range'_append (by decide) (by decide) h bal_444_1
  have h : (List.range' 0 103).all (balRow 444 T444) = true := all_range'_append (by decide) (by decide) h bal_444_2
  have h : (List.range' 0 174).all (balRow 444 T444) = true := all_range'_append (by decide) (by decide) h bal_444_3
  have h : (List.range' 0 222).all (balRow 444 T444) = true := all_range'_append (by decide) (by decide) h bal_444_4
  exact checkN_of_parts tabV_444 (by decide +kernel) (by decide) h small_444

end Sweep

theorem chunk_440_444 : (List.range' 440 5).all checkN = true := by
  have h : (List.range' 440 1).all checkN = true := all_range'_one Sweep.checkN_440
  have h : (List.range' 440 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_441
  have h : (List.range' 440 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_442
  have h : (List.range' 440 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_443
  have h : (List.range' 440 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_444
  exact h

end BGSpiderTable
end R3Cert
