/- Generated by proof/verification/finite_cert/gen_mid_lean.py: root certificate, root degree k = 19. -/
import R3Cert.BGSpiderMidCellsD19
import R3Cert.BGSpiderMidSpiders

namespace R3Cert
namespace BGSCL

def WA_19 : ℕ → ℤ
  | 1 => -39640480599
  | 2 => -7013700050
  | 3 => 5334184812
  | 4 => 9826143512
  | 5 => 10462543454
  | 6 => 8921708734
  | 7 => 6031208487
  | 8 => 2246367517
  | 9 => -2161597450
  | 10 => -7021082254
  | 11 => -12218192081
  | 12 => -17674363825
  | 13 => -23333636373
  | 14 => -29155043769
  | 15 => -35107953399
  | 16 => -41168841663
  | 17 => -47319263260
  | 18 => -53544232128
  | _ => 0

def tys_19 : List (ℕ × ℤ) := [(3, 6768967336), (1, -161373089580), (2, 8063698928), (3, -39640480599), (5, -7013700050), (7, 5334184812), (9, 9826143512), (11, 10462543454), (13, 8921708734), (15, 6031208487), (17, 2246367517), (19, -2161597450), (21, -7021082254), (23, -12218192081), (25, -17674363825), (27, -23333636373), (29, -29155043769), (31, -35107953399), (33, -41168841663), (35, -47319263260), (37, -53544232128)]

theorem check_19 : (List.range' 149 342).all (fun N => decide
    ((12332129788 : ℤ) + 6768967336 + (dpRow tys_19 491 18).getD (N - 3) NEGI - 420000000 * (N : ℤ)
      < lowTabGet N)) = true := by decide +kernel

theorem midroot_19 (cs : List Branch) (hlen : cs.length = 19) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 19)
    (hna : ∃ c ∈ cs, ¬ IsAtom c) (h1 : 149 ≤ bsizeList cs) (h2 : bsizeList cs ≤ 490) :
    phiRoot cs < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 := by
  have hσ : (1 / ((cs.length : ℝ) * (47/40 : ℝ))) = 1 / (((19:ℕ):ℝ) * (47/40 : ℝ)) := by rw [hlen]
  obtain ⟨ht, hn⟩ := htype_of (D := 19) (by norm_num) (by norm_num) rateCellKap_19
    (SC := 10 ^ 12) (σ := 1 / (((19:ℕ):ℝ) * (47/40 : ℝ))) (by norm_num) (by positivity)
    (tys := tys_19) (VNI := 6768967336) (WL := -161373089580) (WC := 8063698928) (WA := WA_19)
    (by unfold NbK; simp only [max_le_iff]; norm_num) (by norm_num) (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 18 := (by omega); interval_cases j <;> norm_num [bjT, WA_19])
    (by simp [tys_19]) (by simp [tys_19]) (by simp [tys_19])
    (by intro j h1 h2; have h3 : j ≤ 18 := (by omega); interval_cases j <;> simp [tys_19, WA_19])
  have hb := phiRoot_le_dp (D := 19) (tys := tys_19) (SC := 10 ^ 12) (α := (21/50000 : ℝ)) (t := (47/40 : ℝ))
    (VNI := 6768967336) (by norm_num) (by norm_num) cs hcap (by rw [hσ]; exact ht) hna
    (by rw [hσ]; exact hn) 491 (by omega)
  rw [hlen] at hb
  have hlt := log_le_of_taylor (x := (47/40 : ℝ)) (c := (1612683/10000000 : ℝ)) (a := (1612683/10000000 : ℝ)) (by norm_num)
    (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
  have hc := check_19
  rw [List.all_eq_true] at hc
  have hN := hc (bsizeList cs) (List.mem_range'_1.mpr ⟨h1, by omega⟩)
  simp only [decide_eq_true_eq] at hN
  have hNR : (((12332129788 : ℤ) + 6768967336 + (dpRow tys_19 491 18).getD (bsizeList cs - 3) NEGI
      - 420000000 * (bsizeList cs : ℤ) : ℤ) : ℝ) < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) := by exact_mod_cast hN
  push_cast at hNR
  have hNn : (0:ℝ) ≤ (bsizeList cs : ℝ) := Nat.cast_nonneg _
  have hCI : Real.log (47/40 : ℝ) + 1 / (47/40 : ℝ) - 1 ≤ (12332129788 : ℝ) / 10 ^ 12 := by
    have : (1612683/10000000 : ℝ) + 1 / (47/40 : ℝ) - 1 ≤ (12332129788 : ℝ) / 10 ^ 12 := by norm_num
    linarith
  have hal : (420000000 : ℝ) / 10 ^ 12 ≤ (21/50000 : ℝ) := by norm_num
  have hmul : (21/50000 : ℝ) * (bsizeList cs : ℝ) ≥ (420000000 : ℝ) / 10 ^ 12 * (bsizeList cs : ℝ) :=
    mul_le_mul_of_nonneg_right hal hNn
  have hNR' : (((12332129788 : ℝ) + 6768967336 + (((dpRow tys_19 491 18).getD (bsizeList cs - 3) NEGI : ℤ) : ℝ)
      - 420000000 * (bsizeList cs : ℝ))) / 10 ^ 12 < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 :=
    div_lt_div_of_pos_right (by linarith) (by norm_num)
  linarith

end BGSCL
end R3Cert
