-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 469 <= n <= 472, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 469. -/
def T469 : ℕ × ℕ := (1652538865133910178246934126556525793327156508966844567282752119020703349532885594596890012698261831036588054855393317643400020674335767019788603554046972781044885336, 1506449942268372376015559154015899090673644096228176710230486554139608204423573245634419321838537160015407940527718400000000)
theorem tabV_469 : tabV 469 = T469 := by decide +kernel
theorem bal_469_0 : (List.range' 0 27).all (balRow 469 T469) = true := by decide +kernel
theorem bal_469_1 : (List.range' 27 31).all (balRow 469 T469) = true := by decide +kernel
theorem bal_469_2 : (List.range' 58 37).all (balRow 469 T469) = true := by decide +kernel
theorem bal_469_3 : (List.range' 95 52).all (balRow 469 T469) = true := by decide +kernel
theorem bal_469_4 : (List.range' 147 88).all (balRow 469 T469) = true := by decide +kernel
theorem small_469 : checkSmallFast 469 T469 = true := by decide +kernel
theorem checkN_469 : checkN 469 = true := by
  have h : (List.range' 0 27).all (balRow 469 T469) = true := bal_469_0
  have h : (List.range' 0 58).all (balRow 469 T469) = true := all_range'_append (by decide) (by decide) h bal_469_1
  have h : (List.range' 0 95).all (balRow 469 T469) = true := all_range'_append (by decide) (by decide) h bal_469_2
  have h : (List.range' 0 147).all (balRow 469 T469) = true := all_range'_append (by decide) (by decide) h bal_469_3
  have h : (List.range' 0 235).all (balRow 469 T469) = true := all_range'_append (by decide) (by decide) h bal_469_4
  exact checkN_of_parts tabV_469 (by decide +kernel) (by decide) h small_469

/-- The table value at n = 470. -/
def T470 : ℕ × ℕ := (660667279341006457481834166814350160397157395325663267779311201706215306397076901881019610356433174480635302592330209942349023689983312754503959168386905033494287262, 488444755681348979028916832203624869963990331314058657208579227281990318639225540844886807083159266055788530674785111244800)
theorem tabV_470 : tabV 470 = T470 := by decide +kernel
theorem bal_470_0 : (List.range' 0 27).all (balRow 470 T470) = true := by decide +kernel
theorem bal_470_1 : (List.range' 27 31).all (balRow 470 T470) = true := by decide +kernel
theorem bal_470_2 : (List.range' 58 37).all (balRow 470 T470) = true := by decide +kernel
theorem bal_470_3 : (List.range' 95 52).all (balRow 470 T470) = true := by decide +kernel
theorem bal_470_4 : (List.range' 147 88).all (balRow 470 T470) = true := by decide +kernel
theorem small_470 : checkSmallFast 470 T470 = true := by decide +kernel
theorem checkN_470 : checkN 470 = true := by
  have h : (List.range' 0 27).all (balRow 470 T470) = true := bal_470_0
  have h : (List.range' 0 58).all (balRow 470 T470) = true := all_range'_append (by decide) (by decide) h bal_470_1
  have h : (List.range' 0 95).all (balRow 470 T470) = true := all_range'_append (by decide) (by decide) h bal_470_2
  have h : (List.range' 0 147).all (balRow 470 T470) = true := all_range'_append (by decide) (by decide) h bal_470_3
  have h : (List.range' 0 235).all (balRow 470 T470) = true := all_range'_append (by decide) (by decide) h bal_470_4
  exact checkN_of_parts tabV_470 (by decide +kernel) (by decide) h small_470

/-- The table value at n = 471. -/
def T471 : ℕ × ℕ := (5998026712523173338424087969038625349360427708169326154774174884175788675699894634416852291465567316860008108882140824616570083332207778320700964636415019188842930860, 3615479861444093702437341969638157817616745830947624104553167729935059690616575789522606372412489184036979057266524160000000)
theorem tabV_471 : tabV 471 = T471 := by decide +kernel
theorem bal_471_0 : (List.range' 0 26).all (balRow 471 T471) = true := by decide +kernel
theorem bal_471_1 : (List.range' 26 30).all (balRow 471 T471) = true := by decide +kernel
theorem bal_471_2 : (List.range' 56 37).all (balRow 471 T471) = true := by decide +kernel
theorem bal_471_3 : (List.range' 93 51).all (balRow 471 T471) = true := by decide +kernel
theorem bal_471_4 : (List.range' 144 92).all (balRow 471 T471) = true := by decide +kernel
theorem small_471 : checkSmallFast 471 T471 = true := by decide +kernel
theorem checkN_471 : checkN 471 = true := by
  have h : (List.range' 0 26).all (balRow 471 T471) = true := bal_471_0
  have h : (List.range' 0 56).all (balRow 471 T471) = true := all_range'_append (by decide) (by decide) h bal_471_1
  have h : (List.range' 0 93).all (balRow 471 T471) = true := all_range'_append (by decide) (by decide) h bal_471_2
  have h : (List.range' 0 144).all (balRow 471 T471) = true := all_range'_append (by decide) (by decide) h bal_471_3
  have h : (List.range' 0 236).all (balRow 471 T471) = true := all_range'_append (by decide) (by decide) h bal_471_4
  exact checkN_of_parts tabV_471 (by decide +kernel) (by decide) h small_471

/-- The table value at n = 472. -/
def T472 : ℕ × ℕ := (2397911522971802868094374349274061594060698932165907649579813934259799701102524911541437939229851746643736153507995598276253531250715171043008293998766932863306001478, 1172267413635237549669400397288699687913576795153740777300590145476776764734141298027728336999582238533892473619484266987520)
theorem tabV_472 : tabV 472 = T472 := by decide +kernel
theorem bal_472_0 : (List.range' 0 26).all (balRow 472 T472) = true := by decide +kernel
theorem bal_472_1 : (List.range' 26 30).all (balRow 472 T472) = true := by decide +kernel
theorem bal_472_2 : (List.range' 56 37).all (balRow 472 T472) = true := by decide +kernel
theorem bal_472_3 : (List.range' 93 50).all (balRow 472 T472) = true := by decide +kernel
theorem bal_472_4 : (List.range' 143 93).all (balRow 472 T472) = true := by decide +kernel
theorem small_472 : checkSmallFast 472 T472 = true := by decide +kernel
theorem checkN_472 : checkN 472 = true := by
  have h : (List.range' 0 26).all (balRow 472 T472) = true := bal_472_0
  have h : (List.range' 0 56).all (balRow 472 T472) = true := all_range'_append (by decide) (by decide) h bal_472_1
  have h : (List.range' 0 93).all (balRow 472 T472) = true := all_range'_append (by decide) (by decide) h bal_472_2
  have h : (List.range' 0 143).all (balRow 472 T472) = true := all_range'_append (by decide) (by decide) h bal_472_3
  have h : (List.range' 0 236).all (balRow 472 T472) = true := all_range'_append (by decide) (by decide) h bal_472_4
  exact checkN_of_parts tabV_472 (by decide +kernel) (by decide) h small_472

end Sweep

theorem chunk_469_472 : (List.range' 469 4).all checkN = true := by
  have h : (List.range' 469 1).all checkN = true := all_range'_one Sweep.checkN_469
  have h : (List.range' 469 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_470
  have h : (List.range' 469 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_471
  have h : (List.range' 469 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_472
  exact h

end BGSpiderTable
end R3Cert
