-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
import R3Cert.BGSpiderTableData

namespace R3Cert
namespace BGSpiderTable

theorem chunk_252_257 : (List.range' 252 6).all checkN = true := by decide +kernel

end BGSpiderTable
end R3Cert
