/-
  R3Cert.BGSpiderCandBase -- infrastructure for `CandProp 492` (spider certificate, part L2, 2026-09-25).

  * `Φ c a b d`: the closed form of `F` for a centre with `c` cherries and `a`, `b`, `d` arms of 4, 5, 6
    cherries (`F_eq_Φ`, `F_W_eq`, `nv_eq`);
  * `P`: the quadratic whose sign decides `Φ c a (m+k1) d ≤ Φ 0 w4 (m+k2) w6` (`Φ_le_of_P`);
  * `mono_nonneg` / `bern_nonneg`: the two certificate shapes (nonnegative monomial coefficients in
    `t = m - L`, or nonnegative degree-2 Bernstein coefficients on `[L, L+T]`);
  * `w_zero` / `w_six` / `w_four`: the rule winner's arm counts from the residue class.
  The per-combo certificates are generated by `proof/verification/bg_spider_cand_certs.py`
  (files `BGSpiderCandCells*.lean`); the assembly is `BGSpiderCand.candProp_492`.
-/
import Mathlib
import R3Cert.BGSpiderRule

namespace R3Cert
namespace BGSpiderCand

open BGSpiderOpt BGSpiderRule

/-! ### The weights of the admissible children -/

def G4 : ℚ := 513 / 80
def G5 : ℚ := 621 / 64
def G6 : ℚ := 6561 / 448
def B4 : ℚ := 3 / 19
def B5 : ℚ := 3 / 23
def B6 : ℚ := 1 / 9

lemma g_arm4 : (Child.arm 4).g = G4 := by norm_num [Child.g, alpha, G4]
lemma g_arm5 : (Child.arm 5).g = G5 := by norm_num [Child.g, alpha, G5]
lemma g_arm6 : (Child.arm 6).g = G6 := by norm_num [Child.g, alpha, G6]
lemma r_arm4 : (Child.arm 4).r = B4 := by norm_num [Child.r, bb, B4]
lemma r_arm5 : (Child.arm 5).r = B5 := by norm_num [Child.r, bb, B5]
lemma r_arm6 : (Child.arm 6).r = B6 := by norm_num [Child.r, bb, B6]

lemma g_cherry : Child.cherry.g = 3 / 2 := rfl
lemma r_cherry : Child.cherry.r = 1 / 3 := rfl

lemma G5_pos : 0 < G5 := by norm_num [G5]

/-! ### Closed form from the counts -/

/-- `F` of a centre with `c` cherries and `a`, `b`, `d` arms of 4, 5, 6 cherries. -/
def Φ (c a b d : ℕ) : ℚ :=
  (3 / 2 : ℚ) ^ c * G4 ^ a * G5 ^ b * G6 ^ d *
    (1 + ((c : ℚ) / 3 + a * B4 + b * B5 + d * B6) / ((c : ℚ) + a + b + d))

/-- Only cherries and arms of 4, 5, 6 cherries. -/
def Adm (l : List Child) : Prop :=
  ∀ x ∈ l, x = Child.cherry ∨ x = Child.arm 4 ∨ x = Child.arm 5 ∨ x = Child.arm 6

abbrev cC (l : List Child) : ℕ := l.count Child.cherry
abbrev c4 (l : List Child) : ℕ := l.count (Child.arm 4)
abbrev c5 (l : List Child) : ℕ := l.count (Child.arm 5)
abbrev c6 (l : List Child) : ℕ := l.count (Child.arm 6)

theorem counts_eq : ∀ l : List Child, Adm l →
    (l.map Child.g).prod = (3 / 2 : ℚ) ^ cC l * G4 ^ c4 l * G5 ^ c5 l * G6 ^ c6 l ∧
    (l.map Child.r).sum = (cC l : ℚ) / 3 + c4 l * B4 + c5 l * B5 + c6 l * B6 ∧
    l.length = cC l + c4 l + c5 l + c6 l ∧
    (l.map Child.cost).sum = 2 * cC l + 9 * c4 l + 11 * c5 l + 13 * c6 l
  | [], _ => by simp
  | x :: t, h => by
    obtain ⟨ih1, ih2, ih3, ih4⟩ := counts_eq t (fun y hy => h y (List.mem_cons_of_mem _ hy))
    simp only [List.map_cons, List.prod_cons, List.sum_cons, List.length_cons, cC, c4, c5, c6,
      List.count_cons] at ih1 ih2 ih3 ih4 ⊢
    rcases h x (by simp) with rfl | rfl | rfl | rfl <;> refine ⟨?_, ?_, ?_, ?_⟩ <;>
      simp [ih1, ih2, ih3, ih4, Child.cost, g_arm4, g_arm5, g_arm6, r_arm4, r_arm5, r_arm6,
        g_cherry, r_cherry, pow_succ] <;> ring

theorem F_eq_Φ (l : List Child) (h : Adm l) : F l = Φ (cC l) (c4 l) (c5 l) (c6 l) := by
  obtain ⟨h1, h2, h3, -⟩ := counts_eq l h
  unfold F Φ
  rw [h1, h2, h3]
  push_cast
  ring

theorem nv_eq (l : List Child) (h : Adm l) :
    nv l = 1 + 2 * cC l + 9 * c4 l + 11 * c5 l + 13 * c6 l := by
  obtain ⟨-, -, -, h4⟩ := counts_eq l h
  unfold nv
  omega

theorem F_W_eq (n : ℕ) : F (W n) = Φ 0 (w4 n) (w5 n) (w6 n) := by
  have hadm : Adm (W n) := by
    intro x hx
    simp only [W, List.mem_append, List.mem_replicate] at hx
    rcases hx with (⟨-, rfl⟩ | ⟨-, rfl⟩) | ⟨-, rfl⟩ <;> simp
  rw [F_eq_Φ _ hadm]
  simp [cC, c4, c5, c6, W, List.count_append, List.count_replicate]

/-! ### The comparison quadratic -/

/-- `P ≥ 0` at `x = m` is equivalent to `Φ c a (m+k1) d ≤ Φ 0 w4 (m+k2) w6`. -/
def P (c a d k1 w4 w6 k2 : ℕ) (x : ℚ) : ℚ :=
  G4 ^ w4 * G5 ^ k2 * G6 ^ w6 *
      (((w4 : ℚ) + w6 + k2 + x) + ((w4 : ℚ) * B4 + w6 * B6 + ((k2 : ℚ) + x) * B5)) *
      ((c : ℚ) + a + d + k1 + x) -
    (3 / 2 : ℚ) ^ c * G4 ^ a * G5 ^ k1 * G6 ^ d *
      (((c : ℚ) + a + d + k1 + x) + ((c : ℚ) / 3 + a * B4 + d * B6 + ((k1 : ℚ) + x) * B5)) *
      ((w4 : ℚ) + w6 + k2 + x)

lemma key_ineq {A1 A2 D1 D2 R1 R2 : ℚ} (h1 : 0 < D1) (h2 : 0 < D2)
    (h : A1 * (D1 + R1) * D2 ≤ A2 * (D2 + R2) * D1) : A1 * (1 + R1 / D1) ≤ A2 * (1 + R2 / D2) := by
  rw [show A1 * (1 + R1 / D1) = A1 * (D1 + R1) / D1 by field_simp,
    show A2 * (1 + R2 / D2) = A2 * (D2 + R2) / D2 by field_simp, div_le_div_iff₀ h1 h2]
  linarith

theorem Φ_le_of_P (c a d k1 w4 w6 k2 m : ℕ) (hD1 : 0 < c + a + d + k1 + m)
    (hD2 : 0 < w4 + w6 + k2 + m) (hP : 0 ≤ P c a d k1 w4 w6 k2 (m : ℚ)) :
    Φ c a (m + k1) d ≤ Φ 0 w4 (m + k2) w6 := by
  have hD1' : (0 : ℚ) < (c : ℚ) + a + d + k1 + m := by exact_mod_cast hD1
  have hD2' : (0 : ℚ) < (w4 : ℚ) + w6 + k2 + m := by exact_mod_cast hD2
  have e1 : Φ c a (m + k1) d = G5 ^ m * ((3 / 2 : ℚ) ^ c * G4 ^ a * G5 ^ k1 * G6 ^ d *
      (1 + ((c : ℚ) / 3 + a * B4 + d * B6 + ((k1 : ℚ) + m) * B5) / ((c : ℚ) + a + d + k1 + m))) := by
    unfold Φ; rw [pow_add]; push_cast; ring
  have e2 : Φ 0 w4 (m + k2) w6 = G5 ^ m * (G4 ^ w4 * G5 ^ k2 * G6 ^ w6 *
      (1 + ((w4 : ℚ) * B4 + w6 * B6 + ((k2 : ℚ) + m) * B5) / ((w4 : ℚ) + w6 + k2 + m))) := by
    unfold Φ; rw [pow_add]; push_cast; ring
  rw [e1, e2]
  apply mul_le_mul_of_nonneg_left _ (pow_pos G5_pos m).le
  apply key_ineq hD1' hD2'
  unfold P at hP
  linarith

/-! ### Certificate shapes -/

lemma mono_nonneg {c0 c1 c2 t : ℚ} (h0 : 0 ≤ c0) (h1 : 0 ≤ c1) (h2 : 0 ≤ c2) (ht : 0 ≤ t) :
    0 ≤ c0 + c1 * t + c2 * t ^ 2 := by positivity

lemma bern_nonneg {b0 b1 b2 T t : ℚ} (h0 : 0 ≤ b0) (h1 : 0 ≤ b1) (h2 : 0 ≤ b2) (ht : 0 ≤ t)
    (htT : t ≤ T) : 0 ≤ b0 * (T - t) ^ 2 + b1 * (t * (T - t)) + b2 * t ^ 2 := by
  have : 0 ≤ T - t := sub_nonneg.2 htT
  positivity

/-! ### The rule winner's arm counts -/

lemma w_zero (n : ℕ) (h : sres n = 0) : w4 n = 0 ∧ w6 n = 0 := by
  unfold w4 w6; simp [h]

lemma w_six (n s : ℕ) (h : sres n = s) (h1 : 1 ≤ s) (h2 : s ≤ 4)
    (hx : ¬ ((s = 3 ∧ n ≤ 722) ∨ (s = 4 ∧ n ≤ 2319))) : w4 n = 0 ∧ w6 n = s := by
  unfold w4 w6; simp only [h]; split_ifs <;> omega

lemma w_four (n s : ℕ) (h : sres n = s) (_h0 : s ≠ 0)
    (hx : ¬ (s ≤ 4 ∧ ¬ ((s = 3 ∧ n ≤ 722) ∨ (s = 4 ∧ n ≤ 2319)))) :
    w4 n = 11 - s ∧ w6 n = 0 := by
  unfold w4 w6; simp only [h]; split_ifs <;> omega

end BGSpiderCand
end R3Cert
