-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 445 <= n <= 448, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 445. -/
def T445 : ℕ × ℕ := (816630804193204666845125875066802560176810233257118943319461337625583731160594894333668290540956985290140871182440172012196001104607810085698372677128355912, 105956048571029061853725930928390988674174967533752141820039006439484404808739362252755808760892326565677017826590720)
theorem tabV_445 : tabV 445 = T445 := by decide +kernel
theorem bal_445_0 : (List.range' 0 28).all (balRow 445 T445) = true := by decide +kernel
theorem bal_445_1 : (List.range' 28 33).all (balRow 445 T445) = true := by decide +kernel
theorem bal_445_2 : (List.range' 61 42).all (balRow 445 T445) = true := by decide +kernel
theorem bal_445_3 : (List.range' 103 71).all (balRow 445 T445) = true := by decide +kernel
theorem bal_445_4 : (List.range' 174 49).all (balRow 445 T445) = true := by decide +kernel
theorem small_445 : checkSmallFast 445 T445 = true := by decide +kernel
theorem checkN_445 : checkN 445 = true := by
  have h : (List.range' 0 28).all (balRow 445 T445) = true := bal_445_0
  have h : (List.range' 0 61).all (balRow 445 T445) = true := all_range'_append (by decide) (by decide) h bal_445_1
  have h : (List.range' 0 103).all (balRow 445 T445) = true := all_range'_append (by decide) (by decide) h bal_445_2
  have h : (List.range' 0 174).all (balRow 445 T445) = true := all_range'_append (by decide) (by decide) h bal_445_3
  have h : (List.range' 0 223).all (balRow 445 T445) = true := all_range'_append (by decide) (by decide) h bal_445_4
  exact checkN_of_parts tabV_445 (by decide +kernel) (by decide) h small_445

/-- The table value at n = 446. -/
def T446 : ℕ × ℕ := (5556679225233276418585652322193654179272658034963076223895041586274932062980606419678801276039260015688395735331455762157060884075826684309006240601506698930, 584890602585258214172707626085718396947153484331015578782669968936779700581122188172454471547159314021133764788224000)
theorem tabV_446 : tabV 446 = T446 := by decide +kernel
theorem bal_446_0 : (List.range' 0 28).all (balRow 446 T446) = true := by decide +kernel
theorem bal_446_1 : (List.range' 28 33).all (balRow 446 T446) = true := by decide +kernel
theorem bal_446_2 : (List.range' 61 42).all (balRow 446 T446) = true := by decide +kernel
theorem bal_446_3 : (List.range' 103 70).all (balRow 446 T446) = true := by decide +kernel
theorem bal_446_4 : (List.range' 173 50).all (balRow 446 T446) = true := by decide +kernel
theorem small_446 : checkSmallFast 446 T446 = true := by decide +kernel
theorem checkN_446 : checkN 446 = true := by
  have h : (List.range' 0 28).all (balRow 446 T446) = true := bal_446_0
  have h : (List.range' 0 61).all (balRow 446 T446) = true := all_range'_append (by decide) (by decide) h bal_446_1
  have h : (List.range' 0 103).all (balRow 446 T446) = true := all_range'_append (by decide) (by decide) h bal_446_2
  have h : (List.range' 0 173).all (balRow 446 T446) = true := all_range'_append (by decide) (by decide) h bal_446_3
  have h : (List.range' 0 223).all (balRow 446 T446) = true := all_range'_append (by decide) (by decide) h bal_446_4
  exact checkN_of_parts tabV_446 (by decide +kernel) (by decide) h small_446

/-- The table value at n = 447. -/
def T447 : ℕ × ℕ := (50509259883751075460369119336648338702564120201178207537236500940204000223313659917629607626058583694958664481336353004923299109340707401908464029151778545572, 4334174096054377857394301937881128026158191893543687596839737659380777760911940334103130611481744577985196851200000000)
theorem tabV_447 : tabV 447 = T447 := by decide +kernel
theorem bal_447_0 : (List.range' 0 28).all (balRow 447 T447) = true := by decide +kernel
theorem bal_447_1 : (List.range' 28 33).all (balRow 447 T447) = true := by decide +kernel
theorem bal_447_2 : (List.range' 61 42).all (balRow 447 T447) = true := by decide +kernel
theorem bal_447_3 : (List.range' 103 69).all (balRow 447 T447) = true := by decide +kernel
theorem bal_447_4 : (List.range' 172 52).all (balRow 447 T447) = true := by decide +kernel
theorem small_447 : checkSmallFast 447 T447 = true := by decide +kernel
theorem checkN_447 : checkN 447 = true := by
  have h : (List.range' 0 28).all (balRow 447 T447) = true := bal_447_0
  have h : (List.range' 0 61).all (balRow 447 T447) = true := all_range'_append (by decide) (by decide) h bal_447_1
  have h : (List.range' 0 103).all (balRow 447 T447) = true := all_range'_append (by decide) (by decide) h bal_447_2
  have h : (List.range' 0 172).all (balRow 447 T447) = true := all_range'_append (by decide) (by decide) h bal_447_3
  have h : (List.range' 0 224).all (balRow 447 T447) = true := all_range'_append (by decide) (by decide) h bal_447_4
  exact checkN_of_parts tabV_447 (by decide +kernel) (by decide) h small_447

/-- The table value at n = 448. -/
def T448 : ℕ × ℕ := (20167584632617431884800680105500665201585111189529991224875910032858634001051414623483241749918715227285727793708430225432390241246617031477377940228002765226, 1403737446204619714014498302605724152673168362394437389078407925448271281394693251613890731713182353650721035491737600)
theorem tabV_448 : tabV 448 = T448 := by decide +kernel
theorem bal_448_0 : (List.range' 0 28).all (balRow 448 T448) = true := by decide +kernel
theorem bal_448_1 : (List.range' 28 33).all (balRow 448 T448) = true := by decide +kernel
theorem bal_448_2 : (List.range' 61 42).all (balRow 448 T448) = true := by decide +kernel
theorem bal_448_3 : (List.range' 103 68).all (balRow 448 T448) = true := by decide +kernel
theorem bal_448_4 : (List.range' 171 53).all (balRow 448 T448) = true := by decide +kernel
theorem small_448 : checkSmallFast 448 T448 = true := by decide +kernel
theorem checkN_448 : checkN 448 = true := by
  have h : (List.range' 0 28).all (balRow 448 T448) = true := bal_448_0
  have h : (List.range' 0 61).all (balRow 448 T448) = true := all_range'_append (by decide) (by decide) h bal_448_1
  have h : (List.range' 0 103).all (balRow 448 T448) = true := all_range'_append (by decide) (by decide) h bal_448_2
  have h : (List.range' 0 171).all (balRow 448 T448) = true := all_range'_append (by decide) (by decide) h bal_448_3
  have h : (List.range' 0 224).all (balRow 448 T448) = true := all_range'_append (by decide) (by decide) h bal_448_4
  exact checkN_of_parts tabV_448 (by decide +kernel) (by decide) h small_448

end Sweep

theorem chunk_445_448 : (List.range' 445 4).all checkN = true := by
  have h : (List.range' 445 1).all checkN = true := all_range'_one Sweep.checkN_445
  have h : (List.range' 445 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_446
  have h : (List.range' 445 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_447
  have h : (List.range' 445 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_448
  exact h

end BGSpiderTable
end R3Cert
