-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 134 <= n <= 168, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 134. -/
def T134 : ℕ × ℕ := (4613022903887886347579248931817616892664206246670, 4693416198736149833936317702937247744)
theorem tabV_134 : tabV 134 = T134 := by decide +kernel
theorem bal_134_0 : (List.range' 0 67).all (balRow 134 T134) = true := by decide +kernel
theorem small_134 : checkSmallFast 134 T134 = true := by decide +kernel
theorem checkN_134 : checkN 134 = true := by
  have h : (List.range' 0 67).all (balRow 134 T134) = true := bal_134_0
  exact checkN_of_parts tabV_134 (by decide +kernel) (by decide) h small_134

/-- The table value at n = 135. -/
def T135 : ℕ × ℕ := (39095615749558659876171710685485783609967701842284, 32380140804643009021347144646262784000)
theorem tabV_135 : tabV 135 = T135 := by decide +kernel
theorem bal_135_0 : (List.range' 0 68).all (balRow 135 T135) = true := by decide +kernel
theorem small_135 : checkSmallFast 135 T135 = true := by decide +kernel
theorem checkN_135 : checkN 135 = true := by
  have h : (List.range' 0 68).all (balRow 135 T135) = true := bal_135_0
  exact checkN_of_parts tabV_135 (by decide +kernel) (by decide) h small_135

/-- The table value at n = 136. -/
def T136 : ℕ × ℕ := (14742043407743841051200067862957575686769442090422, 9938999009088317295394555135631818752)
theorem tabV_136 : tabV 136 = T136 := by decide +kernel
theorem bal_136_0 : (List.range' 0 68).all (balRow 136 T136) = true := by decide +kernel
theorem small_136 : checkSmallFast 136 T136 = true := by decide +kernel
theorem checkN_136 : checkN 136 = true := by
  have h : (List.range' 0 68).all (balRow 136 T136) = true := bal_136_0
  exact checkN_of_parts tabV_136 (by decide +kernel) (by decide) h small_136

/-- The table value at n = 137. -/
def T137 : ℕ × ℕ := (141773412528886278779039822737065461274403642207248, 77712337931143221651233147151030681600)
theorem tabV_137 : tabV 137 = T137 := by decide +kernel
theorem bal_137_0 : (List.range' 0 69).all (balRow 137 T137) = true := by decide +kernel
theorem small_137 : checkSmallFast 137 T137 = true := by decide +kernel
theorem checkN_137 : checkN 137 = true := by
  have h : (List.range' 0 69).all (balRow 137 T137) = true := bal_137_0
  exact checkN_of_parts tabV_137 (by decide +kernel) (by decide) h small_137

/-- The table value at n = 138. -/
def T138 : ℕ × ℕ := (1338350122855617779373274887268100525760729116818890, 597289923696756893839953840046080000000)
theorem tabV_138 : tabV 138 = T138 := by decide +kernel
theorem bal_138_0 : (List.range' 0 69).all (balRow 138 T138) = true := by decide +kernel
theorem small_138 : checkSmallFast 138 T138 = true := by decide +kernel
theorem checkN_138 : checkN 138 = true := by
  have h : (List.range' 0 69).all (balRow 138 T138) = true := bal_138_0
  exact checkN_of_parts tabV_138 (by decide +kernel) (by decide) h small_138

/-- The table value at n = 139. -/
def T139 : ℕ × ℕ := (455240544062088635351820242133973721191327986334188, 165138718103679346008870437695940198400)
theorem tabV_139 : tabV 139 = T139 := by decide +kernel
theorem bal_139_0 : (List.range' 0 70).all (balRow 139 T139) = true := by decide +kernel
theorem small_139 : checkSmallFast 139 T139 = true := by decide +kernel
theorem checkN_139 : checkN 139 = true := by
  have h : (List.range' 0 70).all (balRow 139 T139) = true := bal_139_0
  exact checkN_of_parts tabV_139 (by decide +kernel) (by decide) h small_139

/-- The table value at n = 140. -/
def T140 : ℕ × ℕ := (4853723916538136812896498791363661853541421195711186, 1433495816872216545215889216110592000000)
theorem tabV_140 : tabV 140 = T140 := by decide +kernel
theorem bal_140_0 : (List.range' 0 70).all (balRow 140 T140) = true := by decide +kernel
theorem small_140 : checkSmallFast 140 T140 = true := by decide +kernel
theorem checkN_140 : checkN 140 = true := by
  have h : (List.range' 0 70).all (balRow 140 T140) = true := bal_140_0
  exact checkN_of_parts tabV_140 (by decide +kernel) (by decide) h small_140

/-- The table value at n = 141. -/
def T141 : ℕ × ℕ := (1651004168948924089675455447484001552279478751999680, 396332923448830430421289050470256476160)
theorem tabV_141 : tabV 141 = T141 := by decide +kernel
theorem bal_141_0 : (List.range' 0 71).all (balRow 141 T141) = true := by decide +kernel
theorem small_141 : checkSmallFast 141 T141 = true := by decide +kernel
theorem checkN_141 : checkN 141 = true := by
  have h : (List.range' 0 71).all (balRow 141 T141) = true := bal_141_0
  exact checkN_of_parts tabV_141 (by decide +kernel) (by decide) h small_141

/-- The table value at n = 142. -/
def T142 : ℕ × ℕ := (17602712394037114891463872832886689132517382409916882, 3440389960493319708518134118665420800000)
theorem tabV_142 : tabV 142 = T142 := by decide +kernel
theorem bal_142_0 : (List.range' 0 71).all (balRow 142 T142) = true := by decide +kernel
theorem small_142 : checkSmallFast 142 T142 = true := by decide +kernel
theorem checkN_142 : checkN 142 = true := by
  have h : (List.range' 0 71).all (balRow 142 T142) = true := bal_142_0
  exact checkN_of_parts tabV_142 (by decide +kernel) (by decide) h small_142

/-- The table value at n = 143. -/
def T143 : ℕ × ℕ := (8508730561163555065740451419097023757704006430932276, 1351703865236011152173659498445927350272)
theorem tabV_143 : tabV 143 = T143 := by decide +kernel
theorem bal_143_0 : (List.range' 0 72).all (balRow 143 T143) = true := by decide +kernel
theorem small_143 : checkSmallFast 143 T143 = true := by decide +kernel
theorem checkN_143 : checkN 143 = true := by
  have h : (List.range' 0 72).all (balRow 143 T143) = true := bal_143_0
  exact checkN_of_parts tabV_143 (by decide +kernel) (by decide) h small_143

/-- The table value at n = 144. -/
def T144 : ℕ × ℕ := (63838593713371872241601229424228545209833435916955978, 8256935905183967300443521884797009920000)
theorem tabV_144 : tabV 144 = T144 := by decide +kernel
theorem bal_144_0 : (List.range' 0 72).all (balRow 144 T144) = true := by decide +kernel
theorem small_144 : checkSmallFast 144 T144 = true := by decide +kernel
theorem checkN_144 : checkN 144 = true := by
  have h : (List.range' 0 72).all (balRow 144 T144) = true := bal_144_0
  exact checkN_of_parts tabV_144 (by decide +kernel) (by decide) h small_144

/-- The table value at n = 145. -/
def T145 : ℕ × ℕ := (27208433542288044278986658406052373964463241194614384, 2862431714617435381073631879061963800576)
theorem tabV_145 : tabV 145 = T145 := by decide +kernel
theorem bal_145_0 : (List.range' 0 73).all (balRow 145 T145) = true := by decide +kernel
theorem small_145 : checkSmallFast 145 T145 = true := by decide +kernel
theorem checkN_145 : checkN 145 = true := by
  have h : (List.range' 0 73).all (balRow 145 T145) = true := bal_145_0
  exact checkN_of_parts tabV_145 (by decide +kernel) (by decide) h small_145

/-- The table value at n = 146. -/
def T146 : ℕ × ℕ := (231518778416759958501991481974941048698803355458848474, 19816646172441521521064452523512823808000)
theorem tabV_146 : tabV 146 = T146 := by decide +kernel
theorem bal_146_0 : (List.range' 0 73).all (balRow 146 T146) = true := by decide +kernel
theorem small_146 : checkSmallFast 146 T146 = true := by decide +kernel
theorem checkN_146 : checkN 146 = true := by
  have h : (List.range' 0 73).all (balRow 146 T146) = true := bal_146_0
  exact checkN_of_parts tabV_146 (by decide +kernel) (by decide) h small_146

/-- The table value at n = 147. -/
def T147 : ℕ × ℕ := (2468328168348816970293774322955393747981678729406412308, 172019498024665985425906705933271040000000)
theorem tabV_147 : tabV 147 = T147 := by decide +kernel
theorem bal_147_0 : (List.range' 0 74).all (balRow 147 T147) = true := by decide +kernel
theorem small_147 : checkSmallFast 147 T147 = true := by decide +kernel
theorem checkN_147 : checkN 147 = true := by
  have h : (List.range' 0 74).all (balRow 147 T147) = true := bal_147_0
  exact checkN_of_parts tabV_147 (by decide +kernel) (by decide) h small_147

/-- The table value at n = 148. -/
def T148 : ℕ × ℕ := (839630726701886779639773441688485667435582852112114370, 47559950813859651650554686056430777139200)
theorem tabV_148 : tabV 148 = T148 := by decide +kernel
theorem bal_148_0 : (List.range' 0 74).all (balRow 148 T148) = true := by decide +kernel
theorem small_148 : checkSmallFast 148 T148 = true := by decide +kernel
theorem checkN_148 : checkN 148 = true := by
  have h : (List.range' 0 74).all (balRow 148 T148) = true := bal_148_0
  exact checkN_of_parts tabV_148 (by decide +kernel) (by decide) h small_148

/-- The table value at n = 149. -/
def T149 : ℕ × ℕ := (8951632413002510580593233108851009945030372242837549856, 412846795259198365022176094239850496000000)
theorem tabV_149 : tabV 149 = T149 := by decide +kernel
theorem bal_149_0 : (List.range' 0 75).all (balRow 149 T149) = true := by decide +kernel
theorem small_149 : checkSmallFast 149 T149 = true := by decide +kernel
theorem checkN_149 : checkN 149 = true := by
  have h : (List.range' 0 75).all (balRow 149 T149) = true := bal_149_0
  exact checkN_of_parts tabV_149 (by decide +kernel) (by decide) h small_149

/-- The table value at n = 150. -/
def T150 : ℕ × ℕ := (3045016236482418209937685646605304950584751974787773666, 114143881953263163961331246535433865134080)
theorem tabV_150 : tabV 150 = T150 := by decide +kernel
theorem bal_150_0 : (List.range' 0 75).all (balRow 150 T150) = true := by decide +kernel
theorem small_150 : checkSmallFast 150 T150 = true := by decide +kernel
theorem checkN_150 : checkN 150 = true := by
  have h : (List.range' 0 75).all (balRow 150 T150) = true := bal_150_0
  exact checkN_of_parts tabV_150 (by decide +kernel) (by decide) h small_150

/-- The table value at n = 151. -/
def T151 : ℕ × ℕ := (28646043468166001120772026647325873857974941211168331476, 874263801725361243576372905449095168000000)
theorem tabV_151 : tabV 151 = T151 := by decide +kernel
theorem bal_151_0 : (List.range' 0 76).all (balRow 151 T151) = true := by decide +kernel
theorem small_151 : checkSmallFast 151 T151 = true := by decide +kernel
theorem checkN_151 : checkN 151 = true := by
  have h : (List.range' 0 76).all (balRow 151 T151) = true := bal_151_0
  exact checkN_of_parts tabV_151 (by decide +kernel) (by decide) h small_151

/-- The table value at n = 152. -/
def T152 : ℕ × ℕ := (15692793179791350764247639751719812156269873511105071146, 389290713187971211826013935552427076878336)
theorem tabV_152 : tabV 152 = T152 := by decide +kernel
theorem bal_152_0 : (List.range' 0 76).all (balRow 152 T152) = true := by decide +kernel
theorem small_152 : checkSmallFast 152 T152 = true := by decide +kernel
theorem checkN_152 : checkN 152 = true := by
  have h : (List.range' 0 76).all (balRow 152 T152) = true := bal_152_0
  exact checkN_of_parts tabV_152 (by decide +kernel) (by decide) h small_152

/-- The table value at n = 153. -/
def T153 : ℕ × ℕ := (103896404538998196111078487803277988474203004617202158320, 2098233124140866984583294973077828403200000)
theorem tabV_153 : tabV 153 = T153 := by decide +kernel
theorem bal_153_0 : (List.range' 0 77).all (balRow 153 T153) = true := by decide +kernel
theorem small_153 : checkSmallFast 153 T153 = true := by decide +kernel
theorem checkN_153 : checkN 153 = true := by
  have h : (List.range' 0 77).all (balRow 153 T153) = true := bal_153_0
  exact checkN_of_parts tabV_153 (by decide +kernel) (by decide) h small_153

/-- The table value at n = 154. -/
def T154 : ℕ × ℕ := (50212396122313569522071680884301743382796946936401320266, 824380333809821389749205981169845574565888)
theorem tabV_154 : tabV 154 = T154 := by decide +kernel
theorem bal_154_0 : (List.range' 0 77).all (balRow 154 T154) = true := by decide +kernel
theorem small_154 : checkSmallFast 154 T154 = true := by decide +kernel
theorem checkN_154 : checkN 154 = true := by
  have h : (List.range' 0 77).all (balRow 154 T154) = true := bal_154_0
  exact checkN_of_parts tabV_154 (by decide +kernel) (by decide) h small_154

/-- The table value at n = 155. -/
def T155 : ℕ × ℕ := (376821495150456894369119601529851524491804939057982362764, 5035759497938080762999907935386788167680000)
theorem tabV_155 : tabV 155 = T155 := by decide +kernel
theorem bal_155_0 : (List.range' 0 78).all (balRow 155 T155) = true := by decide +kernel
theorem small_155 : checkSmallFast 155 T155 = true := by decide +kernel
theorem checkN_155 : checkN 155 = true := by
  have h : (List.range' 0 78).all (balRow 155 T155) = true := bal_155_0
  exact checkN_of_parts tabV_155 (by decide +kernel) (by decide) h small_155

/-- The table value at n = 156. -/
def T156 : ℕ × ℕ := (160039238115759260254201327540332150890352820018462281282, 1740358482487400711692768182469673990750208)
theorem tabV_156 : tabV 156 = T156 := by decide +kernel
theorem bal_156_0 : (List.range' 0 78).all (balRow 156 T156) = true := by decide +kernel
theorem small_156 : checkSmallFast 156 T156 = true := by decide +kernel
theorem checkN_156 : checkN 156 = true := by
  have h : (List.range' 0 78).all (balRow 156 T156) = true := bal_156_0
  exact checkN_of_parts tabV_156 (by decide +kernel) (by decide) h small_156

/-- The table value at n = 157. -/
def T157 : ℕ × ℕ := (1366690244527223172717415276398515773107567992320028474808, 12085822795051393831199779044928291602432000)
theorem tabV_157 : tabV 157 = T157 := by decide +kernel
theorem bal_157_0 : (List.range' 0 79).all (balRow 157 T157) = true := by decide +kernel
theorem small_157 : checkSmallFast 157 T157 = true := by decide +kernel
theorem checkN_157 : checkN 157 = true := by
  have h : (List.range' 0 79).all (balRow 157 T157) = true := bal_157_0
  exact checkN_of_parts tabV_157 (by decide +kernel) (by decide) h small_157

/-- The table value at n = 158. -/
def T158 : ℕ × ℕ := (14574517928700961891874067575926006317596486688750095518398, 104911656207043349229164748653891420160000000)
theorem tabV_158 : tabV 158 = T158 := by decide +kernel
theorem bal_158_0 : (List.range' 0 79).all (balRow 158 T158) = true := by decide +kernel
theorem small_158 : checkSmallFast 158 T158 = true := by decide +kernel
theorem checkN_158 : checkN 158 = true := by
  have h : (List.range' 0 79).all (balRow 158 T158) = true := bal_158_0
  exact checkN_of_parts tabV_158 (by decide +kernel) (by decide) h small_158

/-- The table value at n = 159. -/
def T159 : ℕ × ℕ := (4956827376008459514608544132502175204937839227169143024452, 29005974708123345194879469707827899845836800)
theorem tabV_159 : tabV 159 = T159 := by decide +kernel
theorem bal_159_0 : (List.range' 0 80).all (balRow 159 T159) = true := by decide +kernel
theorem small_159 : checkSmallFast 159 T159 = true := by decide +kernel
theorem checkN_159 : checkN 159 = true := by
  have h : (List.range' 0 80).all (balRow 159 T159) = true := bal_159_0
  exact checkN_of_parts tabV_159 (by decide +kernel) (by decide) h small_159

/-- The table value at n = 160. -/
def T160 : ℕ × ℕ := (52859789025226834019053960848529001716919751235573715718870, 251787974896904038149995396769339408384000000)
theorem tabV_160 : tabV 160 = T160 := by decide +kernel
theorem bal_160_0 : (List.range' 0 80).all (balRow 160 T160) = true := by decide +kernel
theorem small_160 : checkSmallFast 160 T160 = true := by decide +kernel
theorem checkN_160 : checkN 160 = true := by
  have h : (List.range' 0 80).all (balRow 160 T160) = true := bal_160_0
  exact checkN_of_parts tabV_160 (by decide +kernel) (by decide) h small_160

/-- The table value at n = 161. -/
def T161 : ℕ × ℕ := (17977809212465571529074760621848669782775299839894286541696, 69614339299496028467710727298786959630008320)
theorem tabV_161 : tabV 161 = T161 := by decide +kernel
theorem bal_161_0 : (List.range' 0 81).all (balRow 161 T161) = true := by decide +kernel
theorem small_161 : checkSmallFast 161 T161 = true := by decide +kernel
theorem checkN_161 : checkN 161 = true := by
  have h : (List.range' 0 81).all (balRow 161 T161) = true := bal_161_0
  exact checkN_of_parts tabV_161 (by decide +kernel) (by decide) h small_161

/-- The table value at n = 162. -/
def T162 : ℕ × ℕ := (191714922342380828894036148520385945771985359043033456653142, 604291139752569691559988952246414580121600000)
theorem tabV_162 : tabV 162 = T162 := by decide +kernel
theorem bal_162_0 : (List.range' 0 81).all (balRow 162 T162) = true := by decide +kernel
theorem small_162 : checkSmallFast 162 T162 = true := by decide +kernel
theorem checkN_162 : checkN 162 = true := by
  have h : (List.range' 0 81).all (balRow 162 T162) = true := bal_162_0
  exact checkN_of_parts tabV_162 (by decide +kernel) (by decide) h small_162

/-- The table value at n = 163. -/
def T163 : ℕ × ℕ := (92657200274606826885104837565592303912035305107240748369820, 237421536137228560247771322576915525474975744)
theorem tabV_163 : tabV 163 = T163 := by decide +kernel
theorem bal_163_0 : (List.range' 0 82).all (balRow 163 T163) = true := by decide +kernel
theorem small_163 : checkSmallFast 163 T163 = true := by decide +kernel
theorem checkN_163 : checkN 163 = true := by
  have h : (List.range' 0 82).all (balRow 163 T163) = true := bal_163_0
  exact checkN_of_parts tabV_163 (by decide +kernel) (by decide) h small_163

/-- The table value at n = 164. -/
def T164 : ℕ × ℕ := (695321525852126250956916547979516267700528187751432860961214, 1450298735406167259743973485391394992291840000)
theorem tabV_164 : tabV 164 = T164 := by decide +kernel
theorem bal_164_0 : (List.range' 0 82).all (balRow 164 T164) = true := by decide +kernel
theorem small_164 : checkSmallFast 164 T164 = true := by decide +kernel
theorem checkN_164 : checkN 164 = true := by
  have h : (List.range' 0 82).all (balRow 164 T164) = true := bal_164_0
  exact checkN_of_parts tabV_164 (by decide +kernel) (by decide) h small_164

/-- The table value at n = 165. -/
def T165 : ℕ × ℕ := (295487619505869442450032961442053265078381082588570496171152, 501223242956371404967517236551266109336059904)
theorem tabV_165 : tabV 165 = T165 := by decide +kernel
theorem bal_165_0 : (List.range' 0 83).all (balRow 165 T165) = true := by decide +kernel
theorem small_165 : checkSmallFast 165 T165 = true := by decide +kernel
theorem checkN_165 : checkN 165 = true := by
  have h : (List.range' 0 83).all (balRow 165 T165) = true := bal_165_0
  exact checkN_of_parts tabV_165 (by decide +kernel) (by decide) h small_165

/-- The table value at n = 166. -/
def T166 : ℕ × ℕ := (2521823533274791976854651206916161124904051561995497712783086, 3480716964974801423385536364939347981500416000)
theorem tabV_166 : tabV 166 = T166 := by decide +kernel
theorem bal_166_0 : (List.range' 0 83).all (balRow 166 T166) = true := by decide +kernel
theorem small_166 : checkSmallFast 166 T166 = true := by decide +kernel
theorem checkN_166 : checkN 166 = true := by
  have h : (List.range' 0 83).all (balRow 166 T166) = true := bal_166_0
  exact checkN_of_parts tabV_166 (by decide +kernel) (by decide) h small_166

/-- The table value at n = 167. -/
def T167 : ℕ × ℕ := (23658236830064441340331114922491344519548703732994957583146068, 26577619572450981804721736325652493107200000000)
theorem tabV_167 : tabV 167 = T167 := by decide +kernel
theorem bal_167_0 : (List.range' 0 84).all (balRow 167 T167) = true := by decide +kernel
theorem small_167 : checkSmallFast 167 T167 = true := by decide +kernel
theorem checkN_167 : checkN 167 = true := by
  have h : (List.range' 0 84).all (balRow 167 T167) = true := bal_167_0
  exact checkN_of_parts tabV_167 (by decide +kernel) (by decide) h small_167

/-- The table value at n = 168. -/
def T168 : ℕ × ℕ := (9146247976910059508329683600010242434837142641738568287758758, 8353720715939523416125287275854435155600998400)
theorem tabV_168 : tabV 168 = T168 := by decide +kernel
theorem bal_168_0 : (List.range' 0 84).all (balRow 168 T168) = true := by decide +kernel
theorem small_168 : checkSmallFast 168 T168 = true := by decide +kernel
theorem checkN_168 : checkN 168 = true := by
  have h : (List.range' 0 84).all (balRow 168 T168) = true := bal_168_0
  exact checkN_of_parts tabV_168 (by decide +kernel) (by decide) h small_168

end Sweep

theorem chunk_134_168 : (List.range' 134 35).all checkN = true := by
  have h : (List.range' 134 1).all checkN = true := all_range'_one Sweep.checkN_134
  have h : (List.range' 134 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_135
  have h : (List.range' 134 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_136
  have h : (List.range' 134 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_137
  have h : (List.range' 134 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_138
  have h : (List.range' 134 6).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_139
  have h : (List.range' 134 7).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_140
  have h : (List.range' 134 8).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_141
  have h : (List.range' 134 9).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_142
  have h : (List.range' 134 10).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_143
  have h : (List.range' 134 11).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_144
  have h : (List.range' 134 12).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_145
  have h : (List.range' 134 13).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_146
  have h : (List.range' 134 14).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_147
  have h : (List.range' 134 15).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_148
  have h : (List.range' 134 16).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_149
  have h : (List.range' 134 17).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_150
  have h : (List.range' 134 18).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_151
  have h : (List.range' 134 19).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_152
  have h : (List.range' 134 20).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_153
  have h : (List.range' 134 21).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_154
  have h : (List.range' 134 22).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_155
  have h : (List.range' 134 23).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_156
  have h : (List.range' 134 24).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_157
  have h : (List.range' 134 25).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_158
  have h : (List.range' 134 26).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_159
  have h : (List.range' 134 27).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_160
  have h : (List.range' 134 28).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_161
  have h : (List.range' 134 29).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_162
  have h : (List.range' 134 30).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_163
  have h : (List.range' 134 31).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_164
  have h : (List.range' 134 32).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_165
  have h : (List.range' 134 33).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_166
  have h : (List.range' 134 34).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_167
  have h : (List.range' 134 35).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_168
  exact h

end BGSpiderTable
end R3Cert
