/- Generated by proof/verification/finite_cert/gen_mid_lean.py: credited rate cells, cap D = 15. -/
import R3Cert.BGSpiderMid

namespace R3Cert
namespace BGSCL

theorem mcell_15_1 (cs : List Branch) (hlen : cs.length = 1) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_oneK (D := 15) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (49/100 : ℝ)) (ℓ := (138043/11000000 : ℝ))
    (u := (19834498199377/79184490000000 : ℝ)) (by norm_num)
    (by
      have e : (1 + (49/100 : ℝ) / ((1:ℝ) + 1)) = (249/200 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (249/200 : ℝ) ^ 11 * (64 / 621)) (c := (138043/1000000 : ℝ)) (a := (138043/1000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold Nb1K; simp only [max_le_iff]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_2 (cs : List Branch) (hlen : cs.length = 2) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 2) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (67/75 : ℝ))
    (ℓ := (297419/5500000 : ℝ)) (umax := (634443819/8030000000 : ℝ)) (unc := (112273114963/1421310000000 : ℝ)) (ρm := (29/2848 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (67/75 : ℝ) / ((((2:ℕ):ℝ)) + 1)) = (292/225 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (292/225 : ℝ) ^ 11 * (64 / 621)) (c := (297419/500000 : ℝ)) (a := (297419/500000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len2_le (D := 15) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_3 (cs : List Branch) (hlen : cs.length = 3) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 3) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (107/100 : ℝ))
    (ℓ := (3350669/110000000 : ℝ)) (umax := (9894541763/167310000000 : ℝ)) (unc := (3040666921/55770000000 : ℝ)) (ρm := (29/45696 : ℝ))
    (km := (1/200 : ℝ)) (by norm_num)
    (by
      have e : (1 + (107/100 : ℝ) / ((((3:ℕ):ℝ)) + 1)) = (507/400 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (507/400 : ℝ) ^ 11 * (64 / 621)) (c := (3350669/10000000 : ℝ)) (a := (3350669/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h hc => le_trans (rho_len3_le (D := 15) (by norm_num) cs' h hc) (by norm_num))
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_4 (cs : List Branch) (hlen : cs.length = 4) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 4) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (7/5 : ℝ))
    (ℓ := (1107581/27500000 : ℝ)) (umax := (15007109/330000000 : ℝ)) (unc := (12581609/330000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (7/5 : ℝ) / ((((4:ℕ):ℝ)) + 1)) = (32/25 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (32/25 : ℝ) ^ 11 * (64 / 621)) (c := (1107581/2500000 : ℝ)) (a := (1107581/2500000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_5 (cs : List Branch) (hlen : cs.length = 5) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 5) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (26/15 : ℝ))
    (ℓ := (648977/13750000 : ℝ)) (umax := (116422887/3190000000 : ℝ)) (unc := (261741661/9570000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (26/15 : ℝ) / ((((5:ℕ):ℝ)) + 1)) = (58/45 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (58/45 : ℝ) ^ 11 * (64 / 621)) (c := (648977/1250000 : ℝ)) (a := (648977/1250000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_6 (cs : List Branch) (hlen : cs.length = 6) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 6) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (19/10 : ℝ))
    (ℓ := (1845551/55000000 : ℝ)) (umax := (905945201/29370000000 : ℝ)) (unc := (2211107/101673600 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (19/10 : ℝ) / ((((6:ℕ):ℝ)) + 1)) = (89/70 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (89/70 : ℝ) ^ 11 * (64 / 621)) (c := (1845551/5000000 : ℝ)) (a := (1845551/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_7 (cs : List Branch) (hlen : cs.length = 7) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 7) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (161/75 : ℝ))
    (ℓ := (1711483/55000000 : ℝ)) (umax := (2196907483/83710000000 : ℝ)) (unc := (6198086421/318098000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (161/75 : ℝ) / ((((7:ℕ):ℝ)) + 1)) = (761/600 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (761/600 : ℝ) ^ 11 * (64 / 621)) (c := (1711483/5000000 : ℝ)) (a := (1711483/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_8 (cs : List Branch) (hlen : cs.length = 8) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 8) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (62/25 : ℝ))
    (ℓ := (80953/2200000 : ℝ)) (umax := (2124227783/94710000000 : ℝ)) (unc := (2120697507/119966000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (62/25 : ℝ) / ((((8:ℕ):ℝ)) + 1)) = (287/225 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (287/225 : ℝ) ^ 11 * (64 / 621)) (c := (80953/200000 : ℝ)) (a := (80953/200000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_9 (cs : List Branch) (hlen : cs.length = 9) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 9) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (141/50 : ℝ))
    (ℓ := (920413/22000000 : ℝ)) (umax := (4102369369/211530000000 : ℝ)) (unc := (4351279101/267938000000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (141/50 : ℝ) / ((((9:ℕ):ℝ)) + 1)) = (641/500 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (641/500 : ℝ) ^ 11 * (64 / 621)) (c := (920413/2000000 : ℝ)) (a := (920413/2000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_10 (cs : List Branch) (hlen : cs.length = 10) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 10) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (47/15 : ℝ))
    (ℓ := (4846301/110000000 : ℝ)) (umax := (98979759/5830000000 : ℝ)) (unc := (372499/24380000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (47/15 : ℝ) / ((((10:ℕ):ℝ)) + 1)) = (212/165 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (212/165 : ℝ) ^ 11 * (64 / 621)) (c := (4846301/10000000 : ℝ)) (a := (4846301/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_11 (cs : List Branch) (hlen : cs.length = 11) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 11) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (517/150 : ℝ))
    (ℓ := (2524741/55000000 : ℝ)) (umax := (3816011351/254870000000 : ℝ)) (unc := (15448211/1065820000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (517/150 : ℝ) / ((((11:ℕ):ℝ)) + 1)) = (2317/1800 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (2317/1800 : ℝ) ^ 11 * (64 / 621)) (c := (2524741/5000000 : ℝ)) (a := (2524741/5000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_12 (cs : List Branch) (hlen : cs.length = 12) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 12) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (76/25 : ℝ))
    (ℓ := (97627/27500000 : ℝ)) (umax := (2615983/184460000 : ℝ)) (unc := (2615983/184460000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (76/25 : ℝ) / ((((12:ℕ):ℝ)) + 1)) = (401/325 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (401/325 : ℝ) ^ 11 * (64 / 621)) (c := (97627/2500000 : ℝ)) (a := (97627/2500000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_13 (cs : List Branch) (hlen : cs.length = 13) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 13) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (611/300 : ℝ))
    (ℓ := (-706127/10000000 : ℝ)) (umax := (31389013/2213060000 : ℝ)) (unc := (31389013/2213060000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (611/300 : ℝ) / ((((13:ℕ):ℝ)) + 1)) = (4811/4200 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (4811/4200 : ℝ) ^ 11 * (64 / 621)) (c := (-7767397/10000000 : ℝ)) (a := (7767397/10000000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem mcell_15_14 (cs : List Branch) (hlen : cs.length = 14) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 15)
    (hna : ¬ IsAtom (Branch.node cs)) :
    (Real.log (1 + (cs.map bY).sum / ((cs.length : ℝ) + 1)) - FSTAR) + ρwit (Branch.node cs) + (11/20000 : ℝ)
      + kapF (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) (Branch.node cs)
      + (cs.map (rateGK (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ))).sum ≤ 0 :=
  rate_cell_genericK (D := 15) (K := 14) (by norm_num) (by norm_num) (α := (11/20000 : ℝ)) (k1 := (0 : ℝ)) (k2 := (1/200 : ℝ)) (k3 := (1/200 : ℝ)) (k4 := (1/500 : ℝ)) (S0 := (161/75 : ℝ))
    (ℓ := (-31979/440000 : ℝ)) (umax := (4039469/295780000 : ℝ)) (unc := (4039469/295780000 : ℝ)) (ρm := (0 : ℝ))
    (km := (1/500 : ℝ)) (by norm_num)
    (by
      have e : (1 + (161/75 : ℝ) / ((((14:ℕ):ℝ)) + 1)) = (1286/1125 : ℝ) := by norm_num
      rw [e, log_sub_fstar_eq (by norm_num)]
      have h := log_le_of_taylor (x := (1286/1125 : ℝ) ^ 11 * (64 / 621)) (c := (-31979/40000 : ℝ)) (a := (31979/40000 : ℝ))
        (by norm_num) (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
      linarith)
    (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 14 := (by omega); interval_cases j <;> norm_num [bjT])
    (by unfold NbK; simp only [max_le_iff]; norm_num)
    (by norm_num) (by norm_num)
    (fun cs' h _ => by rw [ρwit_node_of_four_le cs' (by omega)])
    (fun cs' h => by rw [kapF_node_len, h]; norm_num)
    (by norm_num) cs hlen hcap hna

theorem rateCellKap_15 : RateCellKap 15 (11/20000 : ℝ) (0 : ℝ) (1/200 : ℝ) (1/200 : ℝ) (1/500 : ℝ) := by
  intro cs hlen hcap hna
  obtain ⟨K, hK⟩ : ∃ K, cs.length = K := ⟨_, rfl⟩
  have hK0 : 1 ≤ K := by
    rcases cs with _ | ⟨a, t⟩
    · exact absurd (Or.inr ⟨0, rfl⟩) hna
    · simp at hK; omega
  have hKD : K ≤ 14 := by omega
  interval_cases K
  · exact mcell_15_1 cs hK hcap hna
  · exact mcell_15_2 cs hK hcap hna
  · exact mcell_15_3 cs hK hcap hna
  · exact mcell_15_4 cs hK hcap hna
  · exact mcell_15_5 cs hK hcap hna
  · exact mcell_15_6 cs hK hcap hna
  · exact mcell_15_7 cs hK hcap hna
  · exact mcell_15_8 cs hK hcap hna
  · exact mcell_15_9 cs hK hcap hna
  · exact mcell_15_10 cs hK hcap hna
  · exact mcell_15_11 cs hK hcap hna
  · exact mcell_15_12 cs hK hcap hna
  · exact mcell_15_13 cs hK hcap hna
  · exact mcell_15_14 cs hK hcap hna

end BGSCL
end R3Cert
