/-
  R3Cert.BGSpiderCandCells8 -- GENERATED by proof/verification/bg_spider_cand_certs.py; do not edit.

  Per-combo certificates for `CandProp 492` with 8 cherries at the centre: for each (k4, k6) the
  comparison `Φ C k4 k5 k6 ≤ F (W n)` for every n >= 492 in the combo's residue class.
-/
import Mathlib
import R3Cert.BGSpiderCandBase

namespace R3Cert
namespace BGSpiderCand

open BGSpiderOpt BGSpiderRule

theorem cert_8_0_0_0 (m : ℕ) (hm : 43 ≤ m) :
    Φ 8 0 (m + 1) 0 ≤ Φ 0 3 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 0 1 3 0 0 (43 + t) =
      (13617900063 / 588800 : ℚ) + (15074284599 / 11776000 : ℚ) * t + (399427119 / 23552000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (43 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 43)
  rw [show (43 : ℚ) + ((m : ℚ) - 43) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 0) :
    Φ 8 0 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 0) = 8 := by unfold sres; omega
  have hw := w_four _ 8 hs (by omega) (by omega)
  obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
  have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * (m + 1) + 13 * 0) = 3 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * (m + 1) + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * (m + 1) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_0_0_0 m (by omega)

theorem cert_8_1_0_0 (m : ℕ) (hm : 42 ≤ m) :
    Φ 8 1 (m + 1) 0 ≤ Φ 0 4 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 1 0 1 4 0 0 (42 + t) =
      (70048293839343 / 471040000 : ℚ) + (773559673749 / 94208000 : ℚ) * t + (204906112047 / 1884160000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (42 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 42)
  rw [show (42 : ℚ) + ((m : ℚ) - 42) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_1_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 1 + 11 * b + 13 * 0) :
    Φ 8 1 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 1 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 1 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 1 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 1 + 11 * b + 13 * 0) = 7 := by unfold sres; omega
  have hw := w_four _ 7 hs (by omega) (by omega)
  obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
  have h4 : w4 (1 + 2 * 8 + 9 * 1 + 11 * (m + 1) + 13 * 0) = 4 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 1 + 11 * (m + 1) + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 1 + 11 * (m + 1) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_1_0_0 m (by omega)

theorem cert_8_2_0_0 (m : ℕ) (hm : 41 ≤ m) :
    Φ 8 2 (m + 1) 0 ≤ Φ 0 5 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 2 0 1 5 0 0 (41 + t) =
      (4503932257796181 / 4710400000 : ℚ) + (3969637849030509 / 75366400000 : ℚ) * t + (105116835480111 / 150732800000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (41 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 41)
  rw [show (41 : ℚ) + ((m : ℚ) - 41) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_2_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 2 + 11 * b + 13 * 0) :
    Φ 8 2 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 2 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 2 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 2 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 2 + 11 * b + 13 * 0) = 6 := by unfold sres; omega
  have hw := w_four _ 6 hs (by omega) (by omega)
  obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
  have h4 : w4 (1 + 2 * 8 + 9 * 2 + 11 * (m + 1) + 13 * 0) = 5 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 2 + 11 * (m + 1) + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 2 + 11 * (m + 1) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_2_0_0 m (by omega)

theorem cert_8_3_0_0 (m : ℕ) (hm : 40 ≤ m) :
    Φ 8 3 (m + 1) 0 ≤ Φ 0 6 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 3 0 1 6 0 0 (40 + t) =
      (18533736530584995681 / 3014656000000 : ℚ) + (11071082474439111 / 32768000000 : ℚ) * t + (53924936601296943 / 12058624000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (40 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 40)
  rw [show (40 : ℚ) + ((m : ℚ) - 40) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_3_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 3 + 11 * b + 13 * 0) :
    Φ 8 3 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 3 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 3 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 3 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 3 + 11 * b + 13 * 0) = 5 := by unfold sres; omega
  have hw := w_four _ 5 hs (by omega) (by omega)
  obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
  have h4 : w4 (1 + 2 * 8 + 9 * 3 + 11 * (m + 1) + 13 * 0) = 6 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 3 + 11 * (m + 1) + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 3 + 11 * (m + 1) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_3_0_0 m (by omega)

theorem cert_8_4_0_0 (m : ℕ) (hm : 39 ≤ m) (hmU : m ≤ 205) :
    Φ 8 4 (m + 1) 0 ≤ Φ 0 7 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 4 0 1 7 0 0 (39 + t) =
      (4766625446782250153997 / 120586240000000 : ℚ) + (1045357610763003108003 / 482344960000000 : ℚ) * t + (27663492476465331759 / 964689920000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_8_4_0_1 (m : ℕ) (hm : 207 ≤ m) :
    Φ 8 4 (m + 0) 0 ≤ Φ 0 0 (m + 0) 4 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 4 0 0 0 4 0 (207 + t) =
      (38594450996044361379 / 314703872000 : ℚ) + (6293375735402330667 / 5170135040000 : ℚ) * t + (54535215302707347 / 18095472640000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (207 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 207)
  rw [show (207 : ℚ) + ((m : ℚ) - 207) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_4_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 4 + 11 * b + 13 * 0) :
    Φ 8 4 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 4 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 4 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 4 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 4 + 11 * b + 13 * 0) = 4 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 8 + 9 * 4 + 11 * b + 13 * 0) 2320 with hlo | hhi
  · have hw := w_four _ 4 hs (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
    have h4 : w4 (1 + 2 * 8 + 9 * 4 + 11 * (m + 1) + 13 * 0) = 7 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 8 + 9 * 4 + 11 * (m + 1) + 13 * 0) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 8 + 9 * 4 + 11 * (m + 1) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_8_4_0_0 m (by omega) (by omega)
  · have hw := w_six _ 4 hs (by omega) (by omega) (by omega)
    have h4 : w4 (1 + 2 * 8 + 9 * 4 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 8 + 9 * 4 + 11 * b + 13 * 0) = 4 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 8 + 9 * 4 + 11 * b + 13 * 0) = b + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_8_4_0_1 b (by omega)

theorem cert_8_5_0_0 (m : ℕ) (hm : 39 ≤ m) (hmU : m ≤ 59) :
    Φ 8 5 (m + 1) 0 ≤ Φ 0 8 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 5 0 1 8 0 0 (39 + t) =
      (20701515041077362207114231 / 77175193600000000 : ℚ) + (23940530034764577647643 / 1677721600000000 : ℚ) * t + (14191371640426715192367 / 77175193600000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_8_5_0_1 (m : ℕ) (hm : 61 ≤ m) :
    Φ 8 5 (m + 0) 0 ≤ Φ 0 0 (m + 2) 3 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 5 0 0 0 3 2 (61 + t) =
      (107496464960937557876517 / 1654443212800000 : ℚ) + (15340277990941511936499 / 6617772851200000 : ℚ) * t + (267017837841018814797 / 13235545702400000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (61 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 61)
  rw [show (61 : ℚ) + ((m : ℚ) - 61) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_5_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 5 + 11 * b + 13 * 0) :
    Φ 8 5 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 5 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 5 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 5 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 5 + 11 * b + 13 * 0) = 3 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 8 + 9 * 5 + 11 * b + 13 * 0) 723 with hlo | hhi
  · have hw := w_four _ 3 hs (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
    have h4 : w4 (1 + 2 * 8 + 9 * 5 + 11 * (m + 1) + 13 * 0) = 8 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 8 + 9 * 5 + 11 * (m + 1) + 13 * 0) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 8 + 9 * 5 + 11 * (m + 1) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_8_5_0_0 m (by omega) (by omega)
  · have hw := w_six _ 3 hs (by omega) (by omega) (by omega)
    have h4 : w4 (1 + 2 * 8 + 9 * 5 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 8 + 9 * 5 + 11 * b + 13 * 0) = 3 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 8 + 9 * 5 + 11 * b + 13 * 0) = b + 2 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_8_5_0_1 b (by omega)

theorem cert_8_6_0_0 (m : ℕ) (hm : 39 ≤ m) :
    Φ 8 6 (m + 0) 0 ≤ Φ 0 0 (m + 4) 2 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 6 0 0 0 2 4 (39 + t) =
      (4218150938051083591949337 / 24202140712960000 : ℚ) + (602221193666192341850823 / 60505351782400000 : ℚ) * t + (81575360276976175896117 / 605053517824000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_6_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 6 + 11 * b + 13 * 0) :
    Φ 8 6 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 6 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 6 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 6 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 6 + 11 * b + 13 * 0) = 2 := by unfold sres; omega
  have hw := w_six _ 2 hs (by omega) (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 6 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 6 + 11 * b + 13 * 0) = 2 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 6 + 11 * b + 13 * 0) = b + 4 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_6_0_0 b (by omega)

theorem cert_8_7_0_0 (m : ℕ) (hm : 38 ≤ m) :
    Φ 8 7 (m + 0) 0 ≤ Φ 0 0 (m + 6) 1 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 7 0 0 0 1 6 (38 + t) =
      (6636138344969555300477022819 / 5531917877248000000 : ℚ) + (232282649427944100048671157 / 3457448673280000000 : ℚ) * t + (24883357992504232620679137 / 27659589386240000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (38 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 38)
  rw [show (38 : ℚ) + ((m : ℚ) - 38) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_7_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 7 + 11 * b + 13 * 0) :
    Φ 8 7 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 7 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 7 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 7 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 7 + 11 * b + 13 * 0) = 1 := by unfold sres; omega
  have hw := w_six _ 1 hs (by omega) (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 7 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 7 + 11 * b + 13 * 0) = 1 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 7 + 11 * b + 13 * 0) = b + 6 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_7_0_0 b (by omega)

theorem cert_8_8_0_0 (m : ℕ) (hm : 37 ≤ m) :
    Φ 8 8 (m + 0) 0 ≤ Φ 0 0 (m + 8) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 8 0 0 0 0 8 (37 + t) =
      (2078735167005176418246419583033 / 252887674388480000000 : ℚ) + (286023750526944834806796760701 / 632219185971200000000 : ℚ) * t + (7579487265382297798212153357 / 1264438371942400000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (37 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 37)
  rw [show (37 : ℚ) + ((m : ℚ) - 37) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_8_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 8 + 11 * b + 13 * 0) :
    Φ 8 8 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 8 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 8 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 8 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 8 + 11 * b + 13 * 0) = 0 := by unfold sres; omega
  have hw := w_zero _ hs
  have h4 : w4 (1 + 2 * 8 + 9 * 8 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 8 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 8 + 11 * b + 13 * 0) = b + 8 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_8_0_0 b (by omega)

theorem cert_8_9_0_0 (m : ℕ) (hm : 36 ≤ m) :
    Φ 8 9 (m + 0) 0 ≤ Φ 0 1 (m + 8) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 9 0 0 1 0 8 (36 + t) =
      (1069480589518863403290741341160891 / 20231013951078400000000 : ℚ) + (73388705028180425748007030059111 / 25288767438848000000000 : ℚ) * t + (3888276967141118770482834672141 / 101155069755392000000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (36 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 36)
  rw [show (36 : ℚ) + ((m : ℚ) - 36) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_9_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 9 + 11 * b + 13 * 0) :
    Φ 8 9 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 9 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 9 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 9 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 9 + 11 * b + 13 * 0) = 10 := by unfold sres; omega
  have hw := w_four _ 10 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 9 + 11 * b + 13 * 0) = 1 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 9 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 9 + 11 * b + 13 * 0) = b + 8 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_9_0_0 b (by omega)

theorem cert_8_10_0_0 (m : ℕ) (hm : 35 ≤ m) :
    Φ 8 10 (m + 0) 0 ≤ Φ 0 2 (m + 8) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 10 0 0 2 0 8 (35 + t) =
      (550228429680768578962808620783862589 / 1618481116086272000000000 : ℚ) + (75321038315400688403640528964374303 / 4046202790215680000000000 : ℚ) * t + (1994686084143393929257694186808333 / 8092405580431360000000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (35 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 35)
  rw [show (35 : ℚ) + ((m : ℚ) - 35) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_10_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 10 + 11 * b + 13 * 0) :
    Φ 8 10 b 0 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 10 + 11 * b + 13 * 0)) (w5 (1 + 2 * 8 + 9 * 10 + 11 * b + 13 * 0)) (w6 (1 + 2 * 8 + 9 * 10 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 8 + 9 * 10 + 11 * b + 13 * 0) = 9 := by unfold sres; omega
  have hw := w_four _ 9 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 10 + 11 * b + 13 * 0) = 2 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 10 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 10 + 11 * b + 13 * 0) = b + 8 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_10_0_0 b (by omega)

theorem cert_8_0_1_0 (m : ℕ) (hm : 42 ≤ m) :
    Φ 8 0 (m + 0) 1 ≤ Φ 0 2 (m + 1) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 1 0 2 0 1 (42 + t) =
      (291816556011 / 8243200 : ℚ) + (32761034739 / 16486400 : ℚ) * t + (440879517 / 16486400 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (42 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 42)
  rw [show (42 : ℚ) + ((m : ℚ) - 42) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_1 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 1) :
    Φ 8 0 b 1 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 1)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 1)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 1)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 1) = 9 := by unfold sres; omega
  have hw := w_four _ 9 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 1) = 2 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 1) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 1) = b + 1 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_0_1_0 b (by omega)

theorem cert_8_0_2_0 (m : ℕ) (hm : 41 ≤ m) :
    Φ 8 0 (m + 0) 2 ≤ Φ 0 1 (m + 3) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 2 0 1 0 3 (41 + t) =
      (6542693016439113 / 11817451520 : ℚ) + (25881947820891 / 844103680 : ℚ) * t + (4826834671581 / 11817451520 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (41 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 41)
  rw [show (41 : ℚ) + ((m : ℚ) - 41) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_2 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 2) :
    Φ 8 0 b 2 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 2)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 2)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 2)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 2) = 10 := by unfold sres; omega
  have hw := w_four _ 10 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 2) = 1 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 2) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 2) = b + 3 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_0_2_0 b (by omega)

theorem cert_8_0_3_0 (m : ℕ) (hm : 40 ≤ m) :
    Φ 8 0 (m + 0) 3 ≤ Φ 0 0 (m + 5) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 3 0 0 0 5 (40 + t) =
      (36528011341076329785 / 4235374624768 : ℚ) + (15616048689003681 / 33088864256 : ℚ) * t + (26380458818560431 / 4235374624768 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (40 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 40)
  rw [show (40 : ℚ) + ((m : ℚ) - 40) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_3 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 3) :
    Φ 8 0 b 3 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 3)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 3)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 3)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 3) = 0 := by unfold sres; omega
  have hw := w_zero _ hs
  have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 3) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 3) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 3) = b + 5 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_0_3_0 b (by omega)

theorem cert_8_0_4_0 (m : ℕ) (hm : 39 ≤ m) :
    Φ 8 0 (m + 0) 4 ≤ Φ 0 0 (m + 5) 1 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 4 0 0 1 5 (39 + t) =
      (239250026713098545505351 / 1897447831896064 : ℚ) + (6555761973747499316301 / 948723915948032 : ℚ) * t + (173082190308574987791 / 1897447831896064 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_4 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 4) :
    Φ 8 0 b 4 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 4)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 4)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 4)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 4) = 1 := by unfold sres; omega
  have hw := w_six _ 1 hs (by omega) (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 4) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 4) = 1 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 4) = b + 5 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_0_4_0 b (by omega)

theorem cert_8_0_5_0 (m : ℕ) (hm : 38 ≤ m) :
    Φ 8 0 (m + 0) 5 ≤ Φ 0 0 (m + 5) 2 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 5 0 0 2 5 (38 + t) =
      (31980157911125112370659813 / 17348094463049728 : ℚ) + (21501324196542711846890829 / 212514157172359168 : ℚ) * t + (1135592250614560494896751 / 850056628689436672 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (38 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 38)
  rw [show (38 : ℚ) + ((m : ℚ) - 38) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_5 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 5) :
    Φ 8 0 b 5 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 5)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 5)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 5)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 5) = 2 := by unfold sres; omega
  have hw := w_six _ 2 hs (by omega) (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 5) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 5) = 2 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 5) = b + 5 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_0_5_0 b (by omega)

theorem cert_8_0_6_0 (m : ℕ) (hm : 37 ≤ m) (hmU : m ≤ 57) :
    Φ 8 0 (m + 0) 6 ≤ Φ 0 8 (m + 2) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 6 0 8 0 2 (37 + t) =
      (68151433306327528981093124108156073 / 2324373594072678400000000 : ℚ) + (3453582066656254060604522402566881 / 2324373594072678400000000 : ℚ) * t + (21438821932288385572303089070779 / 1162186797036339200000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (37 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 37)
  rw [show (37 : ℚ) + ((m : ℚ) - 37) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_8_0_6_1 (m : ℕ) (hm : 58 ≤ m) :
    Φ 8 0 (m + 0) 6 ≤ Φ 0 0 (m + 5) 3 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 6 0 0 3 5 (58 + t) =
      (793642306013249387831279303247 / 11900792801652113408 : ℚ) + (219269865734836880870336133393 / 95206342413216907264 : ℚ) * t + (7450620756282131407017583311 / 380825369652867629056 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (58 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 58)
  rw [show (58 : ℚ) + ((m : ℚ) - 58) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_6 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6) :
    Φ 8 0 b 6 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6) = 3 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6) 723 with hlo | hhi
  · have hw := w_four _ 3 hs (by omega) (by omega)
    have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6) = 8 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6) = b + 2 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_8_0_6_0 b (by omega) (by omega)
  · have hw := w_six _ 3 hs (by omega) (by omega) (by omega)
    have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6) = 3 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 6) = b + 5 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_8_0_6_1 b (by omega)

theorem cert_8_0_7_0 (m : ℕ) (hm : 35 ≤ m) (hmU : m ≤ 201) :
    Φ 8 0 (m + 0) 7 ≤ Φ 0 7 (m + 4) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 7 0 7 0 4 (35 + t) =
      (312917092672280481377131619315686653 / 724396083578824294400000 : ℚ) + (37110159437247362704451540229841589613 / 1666110992231295877120000000 : ℚ) * t + (938015999657623251479545471861093143 / 3332221984462591754240000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (35 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 35)
  rw [show (35 : ℚ) + ((m : ℚ) - 35) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_8_0_7_1 (m : ℕ) (hm : 202 ≤ m) :
    Φ 8 0 (m + 0) 7 ≤ Φ 0 0 (m + 5) 4 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 7 0 0 4 5 (202 + t) =
      (289793348149788035651727587600913627 / 24372823657783528259584 : ℚ) + (4982476086835364247333473083376439 / 42652441401121174454272 : ℚ) * t + (48883522781967064161442364103471 / 170609765604484697817088 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (202 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 202)
  rw [show (202 : ℚ) + ((m : ℚ) - 202) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_7 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7) :
    Φ 8 0 b 7 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7) = 4 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7) 2320 with hlo | hhi
  · have hw := w_four _ 4 hs (by omega) (by omega)
    have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7) = 7 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7) = b + 4 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_8_0_7_0 b (by omega) (by omega)
  · have hw := w_six _ 4 hs (by omega) (by omega) (by omega)
    have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7) = 4 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 7) = b + 5 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_8_0_7_1 b (by omega)

theorem cert_8_0_8_0 (m : ℕ) (hm : 34 ≤ m) :
    Φ 8 0 (m + 0) 8 ≤ Φ 0 6 (m + 6) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 8 0 6 0 6 (34 + t) =
      (3468139597753700694798195295312590703503 / 519247112709301254225920000 : ℚ) + (102010233694141891057316891021380564029747 / 298567089807848221179904000000 : ℚ) * t + (5122322120301535734730998386776881294357 / 1194268359231392884719616000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (34 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 34)
  rw [show (34 : ℚ) + ((m : ℚ) - 34) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_8 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 8) :
    Φ 8 0 b 8 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 8)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 8)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 8)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 8) = 5 := by unfold sres; omega
  have hw := w_four _ 5 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 8) = 6 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 8) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 8) = b + 6 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_0_8_0 b (by omega)

theorem cert_8_0_9_0 (m : ℕ) (hm : 33 ≤ m) :
    Φ 8 0 (m + 0) 9 ≤ Φ 0 5 (m + 8) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 9 0 5 0 8 (33 + t) =
      (299484892575895331340863461829129860448667 / 2907783831172087023665152000 : ℚ) + (159920905247436621645871046816932875616075557 / 30573269996323657848822169600000 : ℚ) * t + (27932496751290048542512962930676083243155643 / 428025779948531209883510374400000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (33 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 33)
  rw [show (33 : ℚ) + ((m : ℚ) - 33) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_9 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 9) :
    Φ 8 0 b 9 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 9)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 9)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 9)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 9) = 6 := by unfold sres; omega
  have hw := w_four _ 6 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 9) = 5 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 9) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 9) = b + 8 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_0_9_0 b (by omega)

theorem cert_8_0_10_0 (m : ℕ) (hm : 32 ≤ m) :
    Φ 8 0 (m + 0) 10 ≤ Φ 0 4 (m + 10) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 8 0 10 0 4 0 10 (32 + t) =
      (105669149719525329792392525864992447869399602721 / 66697582405892863314021790515200 : ℚ) + (1532823578650151354998183421916567760100477020677 / 19175554941694198202781264773120000 : ℚ) * t + (152118686739193101642463449238048088902889064357 / 153404439533553585622250118184960000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (32 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 32)
  rw [show (32 : ℚ) + ((m : ℚ) - 32) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_8_0_10 (b : ℕ) (hn : 492 ≤ 1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 10) :
    Φ 8 0 b 10 ≤ Φ 0 (w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 10)) (w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 10)) (w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 10)) := by
  have hs : sres (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 10) = 7 := by unfold sres; omega
  have hw := w_four _ 7 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 10) = 4 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 10) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 8 + 9 * 0 + 11 * b + 13 * 10) = b + 10 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_8_0_10_0 b (by omega)

end BGSpiderCand
end R3Cert
