-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 420 <= n <= 424, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 420. -/
def T420 : ℕ × ℕ := (12847423963356607756856559684696966230991065917182936033897860793623130192667400211040345069664009723750488316034679562159282403725055735968573825502, 291130659147171131707413221273843958436965187955046806583357047639457831575806177369278573233210769643929600000)
theorem tabV_420 : tabV 420 = T420 := by decide +kernel
theorem bal_420_0 : (List.range' 0 30).all (balRow 420 T420) = true := by decide +kernel
theorem bal_420_1 : (List.range' 30 37).all (balRow 420 T420) = true := by decide +kernel
theorem bal_420_2 : (List.range' 67 50).all (balRow 420 T420) = true := by decide +kernel
theorem bal_420_3 : (List.range' 117 93).all (balRow 420 T420) = true := by decide +kernel
theorem small_420 : checkSmallFast 420 T420 = true := by decide +kernel
theorem checkN_420 : checkN 420 = true := by
  have h : (List.range' 0 30).all (balRow 420 T420) = true := bal_420_0
  have h : (List.range' 0 67).all (balRow 420 T420) = true := all_range'_append (by decide) (by decide) h bal_420_1
  have h : (List.range' 0 117).all (balRow 420 T420) = true := all_range'_append (by decide) (by decide) h bal_420_2
  have h : (List.range' 0 210).all (balRow 420 T420) = true := all_range'_append (by decide) (by decide) h bal_420_3
  exact checkN_of_parts tabV_420 (by decide +kernel) (by decide) h small_420

/-- The table value at n = 421. -/
def T421 : ℕ × ℕ := (7055046875113792513994977395705045645381689066798969311861855326564755138613588483166918312624223567568730189806914115060575204601780633342561972744, 130025222881631335721829058136433840784745756806310627905192129781423332827358210023093918344452337339555905536)
theorem tabV_421 : tabV 421 = T421 := by decide +kernel
theorem bal_421_0 : (List.range' 0 30).all (balRow 421 T421) = true := by decide +kernel
theorem bal_421_1 : (List.range' 30 36).all (balRow 421 T421) = true := by decide +kernel
theorem bal_421_2 : (List.range' 66 50).all (balRow 421 T421) = true := by decide +kernel
theorem bal_421_3 : (List.range' 116 95).all (balRow 421 T421) = true := by decide +kernel
theorem small_421 : checkSmallFast 421 T421 = true := by decide +kernel
theorem checkN_421 : checkN 421 = true := by
  have h : (List.range' 0 30).all (balRow 421 T421) = true := bal_421_0
  have h : (List.range' 0 66).all (balRow 421 T421) = true := all_range'_append (by decide) (by decide) h bal_421_1
  have h : (List.range' 0 116).all (balRow 421 T421) = true := all_range'_append (by decide) (by decide) h bal_421_2
  have h : (List.range' 0 211).all (balRow 421 T421) = true := all_range'_append (by decide) (by decide) h bal_421_3
  exact checkN_of_parts tabV_421 (by decide +kernel) (by decide) h small_421

/-- The table value at n = 422. -/
def T422 : ℕ × ℕ := (46627464238387874074464735177498453676230929295109709397622310147754490599904392690638443173387520445627293098952249419610784064670596816479287258878, 698713581953210716097791731057225500248716451092112335800056914334698795781934825686268575759705847145431040000)
theorem tabV_422 : tabV 422 = T422 := by decide +kernel
theorem bal_422_0 : (List.range' 0 30).all (balRow 422 T422) = true := by decide +kernel
theorem bal_422_1 : (List.range' 30 36).all (balRow 422 T422) = true := by decide +kernel
theorem bal_422_2 : (List.range' 66 49).all (balRow 422 T422) = true := by decide +kernel
theorem bal_422_3 : (List.range' 115 96).all (balRow 422 T422) = true := by decide +kernel
theorem small_422 : checkSmallFast 422 T422 = true := by decide +kernel
theorem checkN_422 : checkN 422 = true := by
  have h : (List.range' 0 30).all (balRow 422 T422) = true := bal_422_0
  have h : (List.range' 0 66).all (balRow 422 T422) = true := all_range'_append (by decide) (by decide) h bal_422_1
  have h : (List.range' 0 115).all (balRow 422 T422) = true := all_range'_append (by decide) (by decide) h bal_422_2
  have h : (List.range' 0 211).all (balRow 422 T422) = true := all_range'_append (by decide) (by decide) h bal_422_3
  exact checkN_of_parts tabV_422 (by decide +kernel) (by decide) h small_422

/-- The table value at n = 423. -/
def T423 : ℕ × ℕ := (424404893335324256502248681057746664254686643978002372903879903546837693227920507279547533419471268634270739931649077167676562023420050178383237845004, 5183950483389799353764480435787819772737984116008668208393109822639918653415352161133877728511587778560000000000)
theorem tabV_423 : tabV 423 = T423 := by decide +kernel
theorem bal_423_0 : (List.range' 0 30).all (balRow 423 T423) = true := by decide +kernel
theorem bal_423_1 : (List.range' 30 36).all (balRow 423 T423) = true := by decide +kernel
theorem bal_423_2 : (List.range' 66 49).all (balRow 423 T423) = true := by decide +kernel
theorem bal_423_3 : (List.range' 115 97).all (balRow 423 T423) = true := by decide +kernel
theorem small_423 : checkSmallFast 423 T423 = true := by decide +kernel
theorem checkN_423 : checkN 423 = true := by
  have h : (List.range' 0 30).all (balRow 423 T423) = true := bal_423_0
  have h : (List.range' 0 66).all (balRow 423 T423) = true := all_range'_append (by decide) (by decide) h bal_423_1
  have h : (List.range' 0 115).all (balRow 423 T423) = true := all_range'_append (by decide) (by decide) h bal_423_2
  have h : (List.range' 0 212).all (balRow 423 T423) = true := all_range'_append (by decide) (by decide) h bal_423_3
  exact checkN_of_parts tabV_423 (by decide +kernel) (by decide) h small_423

/-- The table value at n = 424. -/
def T424 : ℕ × ℕ := (169226110092831568678261648134511604746063799944791411587750642573331167605705887063963753805960466242821849398370328484152721034435774221225238807654, 1676912596687705718634700154537341200596919482621069605920136594403277109876643581647044581823294033149034496000)
theorem tabV_424 : tabV 424 = T424 := by decide +kernel
theorem bal_424_0 : (List.range' 0 30).all (balRow 424 T424) = true := by decide +kernel
theorem bal_424_1 : (List.range' 30 36).all (balRow 424 T424) = true := by decide +kernel
theorem bal_424_2 : (List.range' 66 49).all (balRow 424 T424) = true := by decide +kernel
theorem bal_424_3 : (List.range' 115 97).all (balRow 424 T424) = true := by decide +kernel
theorem small_424 : checkSmallFast 424 T424 = true := by decide +kernel
theorem checkN_424 : checkN 424 = true := by
  have h : (List.range' 0 30).all (balRow 424 T424) = true := bal_424_0
  have h : (List.range' 0 66).all (balRow 424 T424) = true := all_range'_append (by decide) (by decide) h bal_424_1
  have h : (List.range' 0 115).all (balRow 424 T424) = true := all_range'_append (by decide) (by decide) h bal_424_2
  have h : (List.range' 0 212).all (balRow 424 T424) = true := all_range'_append (by decide) (by decide) h bal_424_3
  exact checkN_of_parts tabV_424 (by decide +kernel) (by decide) h small_424

end Sweep

theorem chunk_420_424 : (List.range' 420 5).all checkN = true := by
  have h : (List.range' 420 1).all checkN = true := all_range'_one Sweep.checkN_420
  have h : (List.range' 420 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_421
  have h : (List.range' 420 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_422
  have h : (List.range' 420 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_423
  have h : (List.range' 420 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_424
  exact h

end BGSpiderTable
end R3Cert
