-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 461 <= n <= 464, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 461. -/
def T461 : ℕ × ℕ := (419069175850877714160895292355981672961968337533687724269421406251988863265963548419789113599091500916543818578239638742919698112837917728008797269785298484285880, 1987856563819443519303731293851961680086007162324657325848868948240658273531731852275702121850066780459604485304358010880)
theorem tabV_461 : tabV 461 = T461 := by decide +kernel
theorem bal_461_0 : (List.range' 0 27).all (balRow 461 T461) = true := by decide +kernel
theorem bal_461_1 : (List.range' 27 31).all (balRow 461 T461) = true := by decide +kernel
theorem bal_461_2 : (List.range' 58 39).all (balRow 461 T461) = true := by decide +kernel
theorem bal_461_3 : (List.range' 97 56).all (balRow 461 T461) = true := by decide +kernel
theorem bal_461_4 : (List.range' 153 78).all (balRow 461 T461) = true := by decide +kernel
theorem small_461 : checkSmallFast 461 T461 = true := by decide +kernel
theorem checkN_461 : checkN 461 = true := by
  have h : (List.range' 0 27).all (balRow 461 T461) = true := bal_461_0
  have h : (List.range' 0 58).all (balRow 461 T461) = true := all_range'_append (by decide) (by decide) h bal_461_1
  have h : (List.range' 0 97).all (balRow 461 T461) = true := all_range'_append (by decide) (by decide) h bal_461_2
  have h : (List.range' 0 153).all (balRow 461 T461) = true := all_range'_append (by decide) (by decide) h bal_461_3
  have h : (List.range' 0 231).all (balRow 461 T461) = true := all_range'_append (by decide) (by decide) h bal_461_4
  exact checkN_of_parts tabV_461 (by decide +kernel) (by decide) h small_461

/-- The table value at n = 462. -/
def T462 : ℕ × ℕ := (3806974702665583807714099200562022332173395659445347266900988698999337119818050403471274207610888717111716597690536414835945072363661709310669919706350133885044398, 14722124435804548220152055368791741113401521849502636031797936779091625634139465809609097917967522245605123055157248000000)
theorem tabV_462 : tabV 462 = T462 := by decide +kernel
theorem bal_462_0 : (List.range' 0 27).all (balRow 462 T462) = true := by decide +kernel
theorem bal_462_1 : (List.range' 27 31).all (balRow 462 T462) = true := by decide +kernel
theorem bal_462_2 : (List.range' 58 38).all (balRow 462 T462) = true := by decide +kernel
theorem bal_462_3 : (List.range' 96 55).all (balRow 462 T462) = true := by decide +kernel
theorem bal_462_4 : (List.range' 151 80).all (balRow 462 T462) = true := by decide +kernel
theorem small_462 : checkSmallFast 462 T462 = true := by decide +kernel
theorem checkN_462 : checkN 462 = true := by
  have h : (List.range' 0 27).all (balRow 462 T462) = true := bal_462_0
  have h : (List.range' 0 58).all (balRow 462 T462) = true := all_range'_append (by decide) (by decide) h bal_462_1
  have h : (List.range' 0 96).all (balRow 462 T462) = true := all_range'_append (by decide) (by decide) h bal_462_2
  have h : (List.range' 0 151).all (balRow 462 T462) = true := all_range'_append (by decide) (by decide) h bal_462_3
  have h : (List.range' 0 231).all (balRow 462 T462) = true := all_range'_append (by decide) (by decide) h bal_462_4
  exact checkN_of_parts tabV_462 (by decide +kernel) (by decide) h small_462

/-- The table value at n = 463. -/
def T463 : ℕ × ℕ := (2161425451461115044564620066899502310990610835628192301751378742504363491209875213089507386546844521596727203986148484180207033165918792399833143521098600789061092, 6779637122921049476362199360084585098398592848349357616579300412947087164466117054077131447151806703883282665669599952896)
theorem tabV_463 : tabV 463 = T463 := by decide +kernel
theorem bal_463_0 : (List.range' 0 27).all (balRow 463 T463) = true := by decide +kernel
theorem bal_463_1 : (List.range' 27 31).all (balRow 463 T463) = true := by decide +kernel
theorem bal_463_2 : (List.range' 58 38).all (balRow 463 T463) = true := by decide +kernel
theorem bal_463_3 : (List.range' 96 55).all (balRow 463 T463) = true := by decide +kernel
theorem bal_463_4 : (List.range' 151 81).all (balRow 463 T463) = true := by decide +kernel
theorem small_463 : checkSmallFast 463 T463 = true := by decide +kernel
theorem checkN_463 : checkN 463 = true := by
  have h : (List.range' 0 27).all (balRow 463 T463) = true := bal_463_0
  have h : (List.range' 0 58).all (balRow 463 T463) = true := all_range'_append (by decide) (by decide) h bal_463_1
  have h : (List.range' 0 96).all (balRow 463 T463) = true := all_range'_append (by decide) (by decide) h bal_463_2
  have h : (List.range' 0 151).all (balRow 463 T463) = true := all_range'_append (by decide) (by decide) h bal_463_3
  have h : (List.range' 0 232).all (balRow 463 T463) = true := all_range'_append (by decide) (by decide) h bal_463_4
  exact checkN_of_parts tabV_463 (by decide +kernel) (by decide) h small_463

/-- The table value at n = 464. -/
def T464 : ℕ × ℕ := (13817545381628522821083439451103751378330722898435499118659876205310538844048941315906547065102683806003593636296041304478983009123876571094305332895458552296553014, 35333098645930915728364932885100178672163652438806326476315048269819901521934717943061835003122053389452295332377395200000)
theorem tabV_464 : tabV 464 = T464 := by decide +kernel
theorem bal_464_0 : (List.range' 0 27).all (balRow 464 T464) = true := by decide +kernel
theorem bal_464_1 : (List.range' 27 31).all (balRow 464 T464) = true := by decide +kernel
theorem bal_464_2 : (List.range' 58 38).all (balRow 464 T464) = true := by decide +kernel
theorem bal_464_3 : (List.range' 96 55).all (balRow 464 T464) = true := by decide +kernel
theorem bal_464_4 : (List.range' 151 81).all (balRow 464 T464) = true := by decide +kernel
theorem small_464 : checkSmallFast 464 T464 = true := by decide +kernel
theorem checkN_464 : checkN 464 = true := by
  have h : (List.range' 0 27).all (balRow 464 T464) = true := bal_464_0
  have h : (List.range' 0 58).all (balRow 464 T464) = true := all_range'_append (by decide) (by decide) h bal_464_1
  have h : (List.range' 0 96).all (balRow 464 T464) = true := all_range'_append (by decide) (by decide) h bal_464_2
  have h : (List.range' 0 151).all (balRow 464 T464) = true := all_range'_append (by decide) (by decide) h bal_464_3
  have h : (List.range' 0 232).all (balRow 464 T464) = true := all_range'_append (by decide) (by decide) h bal_464_4
  exact checkN_of_parts tabV_464 (by decide +kernel) (by decide) h small_464

end Sweep

theorem chunk_461_464 : (List.range' 461 4).all checkN = true := by
  have h : (List.range' 461 1).all checkN = true := all_range'_one Sweep.checkN_461
  have h : (List.range' 461 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_462
  have h : (List.range' 461 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_463
  have h : (List.range' 461 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_464
  exact h

end BGSpiderTable
end R3Cert
