/-
  R3Cert.BGSpiderCandCells3 -- GENERATED by proof/verification/bg_spider_cand_certs.py; do not edit.

  Per-combo certificates for `CandProp 492` with 3 cherries at the centre: for each (k4, k6) the
  comparison `Φ C k4 k5 k6 ≤ F (W n)` for every n >= 492 in the combo's residue class.
-/
import Mathlib
import R3Cert.BGSpiderCandBase

namespace R3Cert
namespace BGSpiderCand

open BGSpiderOpt BGSpiderRule

theorem cert_3_0_0_0 (m : ℕ) (hm : 39 ≤ m) (hmU : m ≤ 59) :
    Φ 3 0 (m + 6) 0 ≤ Φ 0 8 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 0 6 8 0 0 (39 + t) =
      (141937915666978498523842197 / 2469606195200000000 : ℚ) + (4269446776737817439103513 / 1234803097600000000 : ℚ) * t + (118126378299838896837369 / 2469606195200000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_3_0_0_1 (m : ℕ) (hm : 63 ≤ m) :
    Φ 3 0 (m + 3) 0 ≤ Φ 0 0 (m + 0) 3 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 0 3 0 3 0 (63 + t) =
      (3622973065983 / 22478848 : ℚ) + (27974035467603 / 4136108032 : ℚ) * t + (540587631051 / 8272216064 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (63 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 63)
  rw [show (63 : ℚ) + ((m : ℚ) - 63) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 0) :
    Φ 3 0 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 0) = 3 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 0) 723 with hlo | hhi
  · have hw := w_four _ 3 hs (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 6 := by exact ⟨b - 6, by omega⟩
    have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * (m + 6) + 13 * 0) = 8 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * (m + 6) + 13 * 0) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * (m + 6) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_3_0_0_0 m (by omega) (by omega)
  · have hw := w_six _ 3 hs (by omega) (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 3 := by exact ⟨b - 3, by omega⟩
    have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * (m + 3) + 13 * 0) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * (m + 3) + 13 * 0) = 3 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * (m + 3) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_3_0_0_1 m (by omega)

theorem cert_3_1_0_0 (m : ℕ) (hm : 43 ≤ m) :
    Φ 3 1 (m + 1) 0 ≤ Φ 0 0 (m + 0) 2 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 1 0 1 0 2 0 (43 + t) =
      (20929386609 / 4616192 : ℚ) + (380019681 / 1154048 : ℚ) * t + (116936703 / 23080960 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (43 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 43)
  rw [show (43 : ℚ) + ((m : ℚ) - 43) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_1_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 1 + 11 * b + 13 * 0) :
    Φ 3 1 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 1 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 1 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 1 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 1 + 11 * b + 13 * 0) = 2 := by unfold sres; omega
  have hw := w_six _ 2 hs (by omega) (by omega) (by omega)
  obtain ⟨m, rfl⟩ : ∃ m, b = m + 1 := by exact ⟨b - 1, by omega⟩
  have h4 : w4 (1 + 2 * 3 + 9 * 1 + 11 * (m + 1) + 13 * 0) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 1 + 11 * (m + 1) + 13 * 0) = 2 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 1 + 11 * (m + 1) + 13 * 0) = m + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_1_0_0 m (by omega)

theorem cert_3_2_0_0 (m : ℕ) (hm : 43 ≤ m) :
    Φ 3 2 (m + 0) 0 ≤ Φ 0 0 (m + 1) 1 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 2 0 0 0 1 1 (43 + t) =
      (3162723489 / 824320 : ℚ) + (2097597627 / 8243200 : ℚ) * t + (30961359 / 8243200 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (43 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 43)
  rw [show (43 : ℚ) + ((m : ℚ) - 43) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_2_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 2 + 11 * b + 13 * 0) :
    Φ 3 2 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 2 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 2 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 2 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 2 + 11 * b + 13 * 0) = 1 := by unfold sres; omega
  have hw := w_six _ 1 hs (by omega) (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 2 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 2 + 11 * b + 13 * 0) = 1 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 2 + 11 * b + 13 * 0) = b + 1 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_2_0_0 b (by omega)

theorem cert_3_3_0_0 (m : ℕ) (hm : 42 ≤ m) :
    Φ 3 3 (m + 0) 0 ≤ Φ 0 0 (m + 3) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 3 0 0 0 0 3 (42 + t) =
      (282730332087 / 9420800 : ℚ) + (704194813449 / 376832000 : ℚ) * t + (10063976949 / 376832000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (42 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 42)
  rw [show (42 : ℚ) + ((m : ℚ) - 42) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_3_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 3 + 11 * b + 13 * 0) :
    Φ 3 3 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 3 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 3 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 3 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 3 + 11 * b + 13 * 0) = 0 := by unfold sres; omega
  have hw := w_zero _ hs
  have h4 : w4 (1 + 2 * 3 + 9 * 3 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 3 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 3 + 11 * b + 13 * 0) = b + 3 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_3_0_0 b (by omega)

theorem cert_3_4_0_0 (m : ℕ) (hm : 41 ≤ m) :
    Φ 3 4 (m + 0) 0 ≤ Φ 0 1 (m + 3) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 4 0 0 1 0 3 (41 + t) =
      (145545464474829 / 753664000 : ℚ) + (361377351935163 / 30146560000 : ℚ) * t + (5162820174837 / 30146560000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (41 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 41)
  rw [show (41 : ℚ) + ((m : ℚ) - 41) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_4_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 4 + 11 * b + 13 * 0) :
    Φ 3 4 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 4 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 4 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 4 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 4 + 11 * b + 13 * 0) = 10 := by unfold sres; omega
  have hw := w_four _ 10 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 4 + 11 * b + 13 * 0) = 1 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 4 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 4 + 11 * b + 13 * 0) = b + 3 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_4_0_0 b (by omega)

theorem cert_3_5_0_0 (m : ℕ) (hm : 40 ≤ m) :
    Φ 3 5 (m + 0) 0 ≤ Φ 0 2 (m + 3) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 5 0 0 2 0 3 (40 + t) =
      (74923787786170851 / 60293120000 : ℚ) + (185450918224917357 / 2411724800000 : ℚ) * t + (2648526749691381 / 2411724800000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (40 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 40)
  rw [show (40 : ℚ) + ((m : ℚ) - 40) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_5_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 5 + 11 * b + 13 * 0) :
    Φ 3 5 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 5 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 5 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 5 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 5 + 11 * b + 13 * 0) = 9 := by unfold sres; omega
  have hw := w_four _ 9 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 5 + 11 * b + 13 * 0) = 2 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 5 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 5 + 11 * b + 13 * 0) = b + 3 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_5_0_0 b (by omega)

theorem cert_3_6_0_0 (m : ℕ) (hm : 40 ≤ m) :
    Φ 3 6 (m + 0) 0 ≤ Φ 0 3 (m + 3) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 6 0 0 3 0 3 (40 + t) =
      (17818240186079704089 / 2097152000000 : ℚ) + (97886714212523653641 / 192937984000000 : ℚ) * t + (1358694222591678453 / 192937984000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (40 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 40)
  rw [show (40 : ℚ) + ((m : ℚ) - 40) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_6_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 6 + 11 * b + 13 * 0) :
    Φ 3 6 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 6 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 6 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 6 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 6 + 11 * b + 13 * 0) = 8 := by unfold sres; omega
  have hw := w_four _ 8 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 6 + 11 * b + 13 * 0) = 3 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 6 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 6 + 11 * b + 13 * 0) = b + 3 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_6_0_0 b (by omega)

theorem cert_3_7_0_0 (m : ℕ) (hm : 39 ≤ m) :
    Φ 3 7 (m + 0) 0 ≤ Φ 0 4 (m + 3) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 7 0 0 4 0 3 (39 + t) =
      (18341144619433929433161 / 335544320000000 : ℚ) + (10046563162267386123711 / 3087007744000000 : ℚ) * t + (697010136189531046389 / 15435038720000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_7_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 7 + 11 * b + 13 * 0) :
    Φ 3 7 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 7 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 7 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 7 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 7 + 11 * b + 13 * 0) = 7 := by unfold sres; omega
  have hw := w_four _ 7 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 7 + 11 * b + 13 * 0) = 4 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 7 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 7 + 11 * b + 13 * 0) = b + 3 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_7_0_0 b (by omega)

theorem cert_3_8_0_0 (m : ℕ) (hm : 38 ≤ m) :
    Φ 3 8 (m + 0) 0 ≤ Φ 0 5 (m + 3) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 8 0 0 5 0 3 (38 + t) =
      (294987421139949759613347 / 838860800000000 : ℚ) + (25778120329836053409589101 / 1234803097600000000 : ℚ) * t + (357566199865229426797557 / 1234803097600000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (38 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 38)
  rw [show (38 : ℚ) + ((m : ℚ) - 38) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_8_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 8 + 11 * b + 13 * 0) :
    Φ 3 8 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 8 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 8 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 8 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 8 + 11 * b + 13 * 0) = 6 := by unfold sres; omega
  have hw := w_four _ 6 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 8 + 11 * b + 13 * 0) = 5 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 8 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 8 + 11 * b + 13 * 0) = b + 3 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_8_0_0 b (by omega)

theorem cert_3_9_0_0 (m : ℕ) (hm : 37 ≤ m) :
    Φ 3 9 (m + 0) 0 ≤ Φ 0 6 (m + 3) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 9 0 0 6 0 3 (37 + t) =
      (971641264503004546525972299 / 429496729600000000 : ℚ) + (13228631554158062104283916831 / 98784247808000000000 : ℚ) * t + (183431460530862695947146741 / 98784247808000000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (37 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 37)
  rw [show (37 : ℚ) + ((m : ℚ) - 37) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_9_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 9 + 11 * b + 13 * 0) :
    Φ 3 9 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 9 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 9 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 9 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 9 + 11 * b + 13 * 0) = 5 := by unfold sres; omega
  have hw := w_four _ 5 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 9 + 11 * b + 13 * 0) = 6 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 9 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 9 + 11 * b + 13 * 0) = b + 3 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_9_0_0 b (by omega)

theorem cert_3_10_0_0 (m : ℕ) (hm : 36 ≤ m) (hmU : m ≤ 202) :
    Φ 3 10 (m + 0) 0 ≤ Φ 0 7 (m + 3) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 10 0 0 7 0 3 (36 + t) =
      (1250155129306535649236160280647 / 85899345920000000000 : ℚ) + (6788573825483547379247144547537 / 7902739824640000000000 : ℚ) * t + (94100339252332563020886278133 / 7902739824640000000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (36 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 36)
  rw [show (36 : ℚ) + ((m : ℚ) - 36) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_3_10_0_1 (m : ℕ) (hm : 203 ≤ m) :
    Φ 3 10 (m + 0) 0 ≤ Φ 0 0 (m + 4) 4 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 10 0 0 0 4 4 (203 + t) =
      (921261452938698347455161839972769693 / 1897447831896064000000000 : ℚ) + (16247126876026041153791558334992889 / 3299909272862720000000000 : ℚ) * t + (943035594569196845238896472951957 / 75897913275842560000000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (203 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 203)
  rw [show (203 : ℚ) + ((m : ℚ) - 203) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_10_0 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0) :
    Φ 3 10 b 0 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0)) (w5 (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0)) (w6 (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0)) := by
  have hs : sres (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0) = 4 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0) 2320 with hlo | hhi
  · have hw := w_four _ 4 hs (by omega) (by omega)
    have h4 : w4 (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0) = 7 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0) = b + 3 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_3_10_0_0 b (by omega) (by omega)
  · have hw := w_six _ 4 hs (by omega) (by omega) (by omega)
    have h4 : w4 (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0) = 4 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 3 + 9 * 10 + 11 * b + 13 * 0) = b + 4 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_3_10_0_1 b (by omega)

theorem cert_3_0_1_0 (m : ℕ) (hm : 39 ≤ m) (hmU : m ≤ 205) :
    Φ 3 0 (m + 4) 1 ≤ Φ 0 7 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 1 4 7 0 0 (39 + t) =
      (37145509083780962588001 / 3376414720000000 : ℚ) + (17244136366954209315783 / 27011317760000000 : ℚ) * t + (471059656310211337629 / 54022635520000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem cert_3_0_1_1 (m : ℕ) (hm : 207 ≤ m) :
    Φ 3 0 (m + 3) 1 ≤ Φ 0 0 (m + 0) 4 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 1 3 0 4 0 (207 + t) =
      (5935743322067275137 / 161128382464 : ℚ) + (697792672074154095 / 1852976398336 : ℚ) * t + (3546795447325611 / 3705952796672 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (207 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 207)
  rw [show (207 : ℚ) + ((m : ℚ) - 207) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_1 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 1) :
    Φ 3 0 b 1 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 1)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 1)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 1)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 1) = 4 := by unfold sres; omega
  rcases Nat.lt_or_ge (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 1) 2320 with hlo | hhi
  · have hw := w_four _ 4 hs (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 4 := by exact ⟨b - 4, by omega⟩
    have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * (m + 4) + 13 * 1) = 7 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * (m + 4) + 13 * 1) = 0 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * (m + 4) + 13 * 1) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_3_0_1_0 m (by omega) (by omega)
  · have hw := w_six _ 4 hs (by omega) (by omega) (by omega)
    obtain ⟨m, rfl⟩ : ∃ m, b = m + 3 := by exact ⟨b - 3, by omega⟩
    have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * (m + 3) + 13 * 1) = 0 := by have := hw.1; omega
    have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * (m + 3) + 13 * 1) = 4 := by have := hw.2; omega
    have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * (m + 3) + 13 * 1) = m + 0 := by unfold w5; rw [h4, h6]; omega
    rw [h4, h5, h6]
    exact cert_3_0_1_1 m (by omega)

theorem cert_3_0_2_0 (m : ℕ) (hm : 40 ≤ m) :
    Φ 3 0 (m + 2) 2 ≤ Φ 0 6 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 2 2 6 0 0 (40 + t) =
      (89267010367038339699 / 42205184000000 : ℚ) + (34654780868067259821 / 295436288000000 : ℚ) * t + (1838629920079943289 / 1181745152000000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (40 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 40)
  rw [show (40 : ℚ) + ((m : ℚ) - 40) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_2 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 2) :
    Φ 3 0 b 2 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 2)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 2)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 2)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 2) = 5 := by unfold sres; omega
  have hw := w_four _ 5 hs (by omega) (by omega)
  obtain ⟨m, rfl⟩ : ∃ m, b = m + 2 := by exact ⟨b - 2, by omega⟩
  have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * (m + 2) + 13 * 2) = 6 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * (m + 2) + 13 * 2) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * (m + 2) + 13 * 2) = m + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_0_2_0 m (by omega)

theorem cert_3_0_3_0 (m : ℕ) (hm : 41 ≤ m) :
    Φ 3 0 (m + 0) 3 ≤ Φ 0 5 (m + 0) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 3 0 5 0 0 (41 + t) =
      (1266391166452822251 / 3231334400000 : ℚ) + (136047393059874273 / 6462668800000 : ℚ) * t + (7060526866089099 / 25850675200000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (41 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 41)
  rw [show (41 : ℚ) + ((m : ℚ) - 41) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_3 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 3) :
    Φ 3 0 b 3 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 3)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 3)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 3)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 3) = 6 := by unfold sres; omega
  have hw := w_four _ 6 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 3) = 5 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 3) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 3) = b + 0 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_0_3_0 b (by omega)

theorem cert_3_0_4_0 (m : ℕ) (hm : 40 ≤ m) :
    Φ 3 0 (m + 0) 4 ≤ Φ 0 4 (m + 2) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 4 0 4 0 2 (40 + t) =
      (670934858463248934483 / 100705239040000 : ℚ) + (323776824596332918821 / 926488199168000 : ℚ) * t + (20645874017555218263 / 4632440995840000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (40 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 40)
  rw [show (40 : ℚ) + ((m : ℚ) - 40) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_4 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 4) :
    Φ 3 0 b 4 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 4)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 4)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 4)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 4) = 7 := by unfold sres; omega
  have hw := w_four _ 7 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 4) = 4 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 4) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 4) = b + 2 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_0_4_0 b (by omega)

theorem cert_3_0_5_0 (m : ℕ) (hm : 39 ≤ m) :
    Φ 3 0 (m + 0) 5 ≤ Φ 0 3 (m + 4) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 5 0 3 0 4 (39 + t) =
      (401016321519523661565261 / 3609275767193600 : ℚ) + (1357186400312152081552767 / 237180978987008000 : ℚ) * t + (119501985790723043091987 / 1660266852909056000 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (39 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 39)
  rw [show (39 : ℚ) + ((m : ℚ) - 39) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_5 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 5) :
    Φ 3 0 b 5 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 5)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 5)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 5)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 5) = 8 := by unfold sres; omega
  have hw := w_four _ 8 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 5) = 3 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 5) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 5) = b + 4 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_0_5_0 b (by omega)

theorem cert_3_0_6_0 (m : ℕ) (hm : 37 ≤ m) :
    Φ 3 0 (m + 0) 6 ≤ Φ 0 2 (m + 6) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 6 0 2 0 6 (37 + t) =
      (515963210844426699635401178259 / 297519820041302835200 : ℚ) + (53769621172111756255866191931 / 595039640082605670400 : ℚ) * t + (685841004187569273963288213 / 595039640082605670400 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (37 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 37)
  rw [show (37 : ℚ) + ((m : ℚ) - 37) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_6 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 6) :
    Φ 3 0 b 6 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 6)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 6)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 6)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 6) = 9 := by unfold sres; omega
  have hw := w_four _ 9 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 6) = 2 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 6) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 6) = b + 6 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_0_6_0 b (by omega)

theorem cert_3_0_7_0 (m : ℕ) (hm : 36 ≤ m) :
    Φ 3 0 (m + 0) 7 ≤ Φ 0 1 (m + 8) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 7 0 1 0 8 (36 + t) =
      (3005031574541013271516748291452443 / 106631103502802936135680 : ℚ) + (44194336761414436969542589999089 / 30466029572229410324480 : ℚ) * t + (3908199354162871569234529565547 / 213262207005605872271360 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (36 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 36)
  rw [show (36 : ℚ) + ((m : ℚ) - 36) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_7 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 7) :
    Φ 3 0 b 7 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 7)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 7)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 7)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 7) = 10 := by unfold sres; omega
  have hw := w_four _ 10 hs (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 7) = 1 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 7) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 7) = b + 8 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_0_7_0 b (by omega)

theorem cert_3_0_8_0 (m : ℕ) (hm : 35 ≤ m) :
    Φ 3 0 (m + 0) 8 ≤ Φ 0 0 (m + 10) 0 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 8 0 0 0 10 (35 + t) =
      (17333338486525772880519443361576675015 / 38216587495404572311027712 : ℚ) + (1766489720683897929165066696014510679 / 76433174990809144622055424 : ℚ) * t + (22135980472950054840192155356789941 / 76433174990809144622055424 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (35 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 35)
  rw [show (35 : ℚ) + ((m : ℚ) - 35) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_8 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 8) :
    Φ 3 0 b 8 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 8)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 8)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 8)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 8) = 0 := by unfold sres; omega
  have hw := w_zero _ hs
  have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 8) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 8) = 0 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 8) = b + 10 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_0_8_0 b (by omega)

theorem cert_3_0_9_0 (m : ℕ) (hm : 34 ≤ m) :
    Φ 3 0 (m + 0) 9 ≤ Φ 0 0 (m + 10) 1 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 9 0 0 1 10 (34 + t) =
      (113632329575380730286498327294497022159801 / 17121031197941248395340414976 : ℚ) + (11587456422058626530178387195435035354613 / 34242062395882496790680829952 : ℚ) * t + (145234167883025309806500731295898802901 / 34242062395882496790680829952 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (34 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 34)
  rw [show (34 : ℚ) + ((m : ℚ) - 34) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_9 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 9) :
    Φ 3 0 b 9 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 9)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 9)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 9)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 9) = 1 := by unfold sres; omega
  have hw := w_six _ 1 hs (by omega) (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 9) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 9) = 1 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 9) = b + 10 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_0_9_0 b (by omega)

theorem cert_3_0_10_0 (m : ℕ) (hm : 33 ≤ m) :
    Φ 3 0 (m + 0) 10 ≤ Φ 0 0 (m + 10) 2 := by
  apply Φ_le_of_P _ _ _ _ _ _ _ _ (by omega) (by omega)
  have key : ∀ t : ℚ, P 3 0 10 0 0 2 10 (33 + t) =
      (106420006122872676903192033899613810757504701 / 1095745996668239897301786558464 : ℚ) + (76009013014605613979754407768770080772798227 / 15340443953355358562225011818496 : ℚ) * t + (952881375480529057640451298032392045833461 / 15340443953355358562225011818496 : ℚ) * t ^ 2 := by
    intro t; simp only [P, G4, G5, G6, B4, B5, B6]; push_cast; ring
  have hm' : (33 : ℚ) ≤ (m : ℚ) := by exact_mod_cast hm
  have e := key ((m : ℚ) - 33)
  rw [show (33 : ℚ) + ((m : ℚ) - 33) = m by ring] at e
  rw [e]
  exact mono_nonneg (by norm_num) (by norm_num) (by norm_num) (by linarith)

theorem combo_3_0_10 (b : ℕ) (hn : 492 ≤ 1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 10) :
    Φ 3 0 b 10 ≤ Φ 0 (w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 10)) (w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 10)) (w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 10)) := by
  have hs : sres (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 10) = 2 := by unfold sres; omega
  have hw := w_six _ 2 hs (by omega) (by omega) (by omega)
  have h4 : w4 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 10) = 0 := by have := hw.1; omega
  have h6 : w6 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 10) = 2 := by have := hw.2; omega
  have h5 : w5 (1 + 2 * 3 + 9 * 0 + 11 * b + 13 * 10) = b + 10 := by unfold w5; rw [h4, h6]; omega
  rw [h4, h5, h6]
  exact cert_3_0_10_0 b (by omega)

end BGSpiderCand
end R3Cert
