-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 465 <= n <= 468, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 465. -/
def T465 : ℕ × ℕ := (7608878512358096344172059557054721943324806802154095021167777627698112853910349054010267761145317933647723859995194472737585007341848859246044243413021734645868192, 15819153286815782111511798506864031896263383312815167772018367630209870050420939792846640043354215642394326219895733223424)
theorem tabV_465 : tabV 465 = T465 := by decide +kernel
theorem bal_465_0 : (List.range' 0 27).all (balRow 465 T465) = true := by decide +kernel
theorem bal_465_1 : (List.range' 27 31).all (balRow 465 T465) = true := by decide +kernel
theorem bal_465_2 : (List.range' 58 38).all (balRow 465 T465) = true := by decide +kernel
theorem bal_465_3 : (List.range' 96 54).all (balRow 465 T465) = true := by decide +kernel
theorem bal_465_4 : (List.range' 150 83).all (balRow 465 T465) = true := by decide +kernel
theorem small_465 : checkSmallFast 465 T465 = true := by decide +kernel
theorem checkN_465 : checkN 465 = true := by
  have h : (List.range' 0 27).all (balRow 465 T465) = true := bal_465_0
  have h : (List.range' 0 58).all (balRow 465 T465) = true := all_range'_append (by decide) (by decide) h bal_465_1
  have h : (List.range' 0 96).all (balRow 465 T465) = true := all_range'_append (by decide) (by decide) h bal_465_2
  have h : (List.range' 0 150).all (balRow 465 T465) = true := all_range'_append (by decide) (by decide) h bal_465_3
  have h : (List.range' 0 233).all (balRow 465 T465) = true := all_range'_append (by decide) (by decide) h bal_465_4
  exact checkN_of_parts tabV_465 (by decide +kernel) (by decide) h small_465

/-- The table value at n = 466. -/
def T466 : ℕ × ℕ := (50151239421715075701811501238000686400292572590245374934655369014926284824494698502438309978570071349508420478569463793102379391688119034296867299528973231841733030, 84799436750234197748075838924240428813192765853135183543156115847567763652643323063348404007492928134685508797705748480000)
theorem tabV_466 : tabV 466 = T466 := by decide +kernel
theorem bal_466_0 : (List.range' 0 27).all (balRow 466 T466) = true := by decide +kernel
theorem bal_466_1 : (List.range' 27 31).all (balRow 466 T466) = true := by decide +kernel
theorem bal_466_2 : (List.range' 58 38).all (balRow 466 T466) = true := by decide +kernel
theorem bal_466_3 : (List.range' 96 54).all (balRow 466 T466) = true := by decide +kernel
theorem bal_466_4 : (List.range' 150 83).all (balRow 466 T466) = true := by decide +kernel
theorem small_466 : checkSmallFast 466 T466 = true := by decide +kernel
theorem checkN_466 : checkN 466 = true := by
  have h : (List.range' 0 27).all (balRow 466 T466) = true := bal_466_0
  have h : (List.range' 0 58).all (balRow 466 T466) = true := all_range'_append (by decide) (by decide) h bal_466_1
  have h : (List.range' 0 96).all (balRow 466 T466) = true := all_range'_append (by decide) (by decide) h bal_466_2
  have h : (List.range' 0 150).all (balRow 466 T466) = true := all_range'_append (by decide) (by decide) h bal_466_3
  have h : (List.range' 0 233).all (balRow 466 T466) = true := all_range'_append (by decide) (by decide) h bal_466_4
  exact checkN_of_parts tabV_466 (by decide +kernel) (by decide) h small_466

/-- The table value at n = 467. -/
def T467 : ℕ × ℕ := (26785574574687885011335768715800112095309702178203380637202917790608770563028297357584120444033284904679190769355339131784316432427477604188006798327015242936625820, 36911357669236824926860863182682741091281227729902058134709524470489696784315526183308826767826503165586761179756710854656)
theorem tabV_467 : tabV 467 = T467 := by decide +kernel
theorem bal_467_0 : (List.range' 0 27).all (balRow 467 T467) = true := by decide +kernel
theorem bal_467_1 : (List.range' 27 31).all (balRow 467 T467) = true := by decide +kernel
theorem bal_467_2 : (List.range' 58 38).all (balRow 467 T467) = true := by decide +kernel
theorem bal_467_3 : (List.range' 96 54).all (balRow 467 T467) = true := by decide +kernel
theorem bal_467_4 : (List.range' 150 84).all (balRow 467 T467) = true := by decide +kernel
theorem small_467 : checkSmallFast 467 T467 = true := by decide +kernel
theorem checkN_467 : checkN 467 = true := by
  have h : (List.range' 0 27).all (balRow 467 T467) = true := bal_467_0
  have h : (List.range' 0 58).all (balRow 467 T467) = true := all_range'_append (by decide) (by decide) h bal_467_1
  have h : (List.range' 0 96).all (balRow 467 T467) = true := all_range'_append (by decide) (by decide) h bal_467_2
  have h : (List.range' 0 150).all (balRow 467 T467) = true := all_range'_append (by decide) (by decide) h bal_467_3
  have h : (List.range' 0 234).all (balRow 467 T467) = true := all_range'_append (by decide) (by decide) h bal_467_4
  exact checkN_of_parts tabV_467 (by decide +kernel) (by decide) h small_467

/-- The table value at n = 468. -/
def T468 : ℕ × ℕ := (182025529644885128362801941881808419471840868731778287464616916741421726795867284953911850933121466698138418815522663199141276062513772168826588281024071042673504446, 203518648200562074595382013418177029151662638047524440503574678034162632766343975352036169617983027523245221114493796352000)
theorem tabV_468 : tabV 468 = T468 := by decide +kernel
theorem bal_468_0 : (List.range' 0 27).all (balRow 468 T468) = true := by decide +kernel
theorem bal_468_1 : (List.range' 27 31).all (balRow 468 T468) = true := by decide +kernel
theorem bal_468_2 : (List.range' 58 38).all (balRow 468 T468) = true := by decide +kernel
theorem bal_468_3 : (List.range' 96 53).all (balRow 468 T468) = true := by decide +kernel
theorem bal_468_4 : (List.range' 149 85).all (balRow 468 T468) = true := by decide +kernel
theorem small_468 : checkSmallFast 468 T468 = true := by decide +kernel
theorem checkN_468 : checkN 468 = true := by
  have h : (List.range' 0 27).all (balRow 468 T468) = true := bal_468_0
  have h : (List.range' 0 58).all (balRow 468 T468) = true := all_range'_append (by decide) (by decide) h bal_468_1
  have h : (List.range' 0 96).all (balRow 468 T468) = true := all_range'_append (by decide) (by decide) h bal_468_2
  have h : (List.range' 0 149).all (balRow 468 T468) = true := all_range'_append (by decide) (by decide) h bal_468_3
  have h : (List.range' 0 234).all (balRow 468 T468) = true := all_range'_append (by decide) (by decide) h bal_468_4
  exact checkN_of_parts tabV_468 (by decide +kernel) (by decide) h small_468

end Sweep

theorem chunk_465_468 : (List.range' 465 4).all checkN = true := by
  have h : (List.range' 465 1).all checkN = true := all_range'_one Sweep.checkN_465
  have h : (List.range' 465 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_466
  have h : (List.range' 465 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_467
  have h : (List.range' 465 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_468
  exact h

end BGSpiderTable
end R3Cert
