-- GENERATED by proof/verification/gen_spider_table_lean.py.  Do not edit.
-- The spider-table check `checkN n` for 231 <= n <= 245, as small kernel declarations (see the generator).
import R3Cert.BGSpiderTableData

set_option Elab.async false

namespace R3Cert
namespace BGSpiderTable
namespace Sweep

/-- The table value at n = 231. -/
def T231 : ℕ × ℕ := (395290201888398224284808334873152415172221070995096258854663136962834469326626067220, 809193820464130368120215807691780273164303423581760520192000000)
theorem tabV_231 : tabV 231 = T231 := by decide +kernel
theorem bal_231_0 : (List.range' 0 77).all (balRow 231 T231) = true := by decide +kernel
theorem bal_231_1 : (List.range' 77 39).all (balRow 231 T231) = true := by decide +kernel
theorem small_231 : checkSmallFast 231 T231 = true := by decide +kernel
theorem checkN_231 : checkN 231 = true := by
  have h : (List.range' 0 77).all (balRow 231 T231) = true := bal_231_0
  have h : (List.range' 0 116).all (balRow 231 T231) = true := all_range'_append (by decide) (by decide) h bal_231_1
  exact checkN_of_parts tabV_231 (by decide +kernel) (by decide) h small_231

/-- The table value at n = 232. -/
def T232 : ℕ × ℕ := (134374592501432078801770251636094940645965891854080077000791163698362584239347961402, 223725907481922764177877266510623409924466610551885148622684160)
theorem tabV_232 : tabV 232 = T232 := by decide +kernel
theorem bal_232_0 : (List.range' 0 76).all (balRow 232 T232) = true := by decide +kernel
theorem bal_232_1 : (List.range' 76 40).all (balRow 232 T232) = true := by decide +kernel
theorem small_232 : checkSmallFast 232 T232 = true := by decide +kernel
theorem checkN_232 : checkN 232 = true := by
  have h : (List.range' 0 76).all (balRow 232 T232) = true := bal_232_0
  have h : (List.range' 0 116).all (balRow 232 T232) = true := all_range'_append (by decide) (by decide) h bal_232_1
  exact checkN_of_parts tabV_232 (by decide +kernel) (by decide) h small_232

/-- The table value at n = 233. -/
def T233 : ℕ × ℕ := (1433952956366365293245081296839569238512172609470674599522271502407197154696884954864, 1942065169113912883488517938460272655594328216596225248460800000)
theorem tabV_233 : tabV 233 = T233 := by decide +kernel
theorem bal_233_0 : (List.range' 0 75).all (balRow 233 T233) = true := by decide +kernel
theorem bal_233_1 : (List.range' 75 42).all (balRow 233 T233) = true := by decide +kernel
theorem small_233 : checkSmallFast 233 T233 = true := by decide +kernel
theorem checkN_233 : checkN 233 = true := by
  have h : (List.range' 0 75).all (balRow 233 T233) = true := bal_233_0
  have h : (List.range' 0 117).all (balRow 233 T233) = true := all_range'_append (by decide) (by decide) h bal_233_1
  exact checkN_of_parts tabV_233 (by decide +kernel) (by decide) h small_233

/-- The table value at n = 234. -/
def T234 : ℕ × ℕ := (692703566916592679718172503047944596174336482847123620668730886845441121564098190570, 763023094990978690459286677362547208584496650724324085828943872)
theorem tabV_234 : tabV 234 = T234 := by decide +kernel
theorem bal_234_0 : (List.range' 0 75).all (balRow 234 T234) = true := by decide +kernel
theorem bal_234_1 : (List.range' 75 42).all (balRow 234 T234) = true := by decide +kernel
theorem small_234 : checkSmallFast 234 T234 = true := by decide +kernel
theorem checkN_234 : checkN 234 = true := by
  have h : (List.range' 0 75).all (balRow 234 T234) = true := bal_234_0
  have h : (List.range' 0 117).all (balRow 234 T234) = true := all_range'_append (by decide) (by decide) h bal_234_1
  exact checkN_of_parts tabV_234 (by decide +kernel) (by decide) h small_234

/-- The table value at n = 235. -/
def T235 : ℕ × ℕ := (5201795014963838928167952016571390290149507099790735489031425718093119199864724780108, 4660956405873390920372443052304654373426387719830940596305920000)
theorem tabV_235 : tabV 235 = T235 := by decide +kernel
theorem bal_235_0 : (List.range' 0 74).all (balRow 235 T235) = true := by decide +kernel
theorem bal_235_1 : (List.range' 74 44).all (balRow 235 T235) = true := by decide +kernel
theorem small_235 : checkSmallFast 235 T235 = true := by decide +kernel
theorem checkN_235 : checkN 235 = true := by
  have h : (List.range' 0 74).all (balRow 235 T235) = true := bal_235_0
  have h : (List.range' 0 118).all (balRow 235 T235) = true := all_range'_append (by decide) (by decide) h bal_235_1
  exact checkN_of_parts tabV_235 (by decide +kernel) (by decide) h small_235

/-- The table value at n = 236. -/
def T236 : ℕ × ℕ := (48362616147071842751966133037227623757914534057286583577020420706356871154958030151790, 35248973239914769823418491622937398262838974890872143872000000000)
theorem tabV_236 : tabV 236 = T236 := by decide +kernel
theorem bal_236_0 : (List.range' 0 73).all (balRow 236 T236) = true := by decide +kernel
theorem bal_236_1 : (List.range' 73 45).all (balRow 236 T236) = true := by decide +kernel
theorem small_236 : checkSmallFast 236 T236 = true := by decide +kernel
theorem checkN_236 : checkN 236 = true := by
  have h : (List.range' 0 73).all (balRow 236 T236) = true := bal_236_0
  have h : (List.range' 0 118).all (balRow 236 T236) = true := all_range'_append (by decide) (by decide) h bal_236_1
  exact checkN_of_parts tabV_236 (by decide +kernel) (by decide) h small_236

/-- The table value at n = 237. -/
def T237 : ℕ × ℕ := (18869962614888976477885147183371180598935052138397303833559178974735437364358557072952, 11186295374096138208893863325531170496223330527594257431134208000)
theorem tabV_237 : tabV 237 = T237 := by decide +kernel
theorem bal_237_0 : (List.range' 0 72).all (balRow 237 T237) = true := by decide +kernel
theorem bal_237_1 : (List.range' 72 47).all (balRow 237 T237) = true := by decide +kernel
theorem small_237 : checkSmallFast 237 T237 = true := by decide +kernel
theorem checkN_237 : checkN 237 = true := by
  have h : (List.range' 0 72).all (balRow 237 T237) = true := bal_237_0
  have h : (List.range' 0 119).all (balRow 237 T237) = true := all_range'_append (by decide) (by decide) h bal_237_1
  exact checkN_of_parts tabV_237 (by decide +kernel) (by decide) h small_237

/-- The table value at n = 238. -/
def T238 : ℕ × ℕ := (175448910435035529864589219985767144487930741314912529478086994224233263198513873969006, 84597535775795447576204379895049755830813539738093145292800000000)
theorem tabV_238 : tabV 238 = T238 := by decide +kernel
theorem bal_238_0 : (List.range' 0 71).all (balRow 238 T238) = true := by decide +kernel
theorem bal_238_1 : (List.range' 71 48).all (balRow 238 T238) = true := by decide +kernel
theorem small_238 : checkSmallFast 238 T238 = true := by decide +kernel
theorem checkN_238 : checkN 238 = true := by
  have h : (List.range' 0 71).all (balRow 238 T238) = true := bal_238_0
  have h : (List.range' 0 119).all (balRow 238 T238) = true := all_range'_append (by decide) (by decide) h bal_238_1
  exact checkN_of_parts tabV_238 (by decide +kernel) (by decide) h small_238

/-- The table value at n = 239. -/
def T239 : ℕ × ℕ := (68452343240986313540186250315520350024947100844249415480092934703365585204410476363396, 26847108897830731701345271981274809190935993266226217834722099200)
theorem tabV_239 : tabV 239 = T239 := by decide +kernel
theorem bal_239_0 : (List.range' 0 71).all (balRow 239 T239) = true := by decide +kernel
theorem bal_239_1 : (List.range' 71 49).all (balRow 239 T239) = true := by decide +kernel
theorem small_239 : checkSmallFast 239 T239 = true := by decide +kernel
theorem checkN_239 : checkN 239 = true := by
  have h : (List.range' 0 71).all (balRow 239 T239) = true := bal_239_0
  have h : (List.range' 0 120).all (balRow 239 T239) = true := all_range'_append (by decide) (by decide) h bal_239_1
  exact checkN_of_parts tabV_239 (by decide +kernel) (by decide) h small_239

/-- The table value at n = 240. -/
def T240 : ℕ × ℕ := (636489273364138825381834280920888465750480075016507556458032897155054162154427135717622, 203034085861909074182890511748119413993952495371423548702720000000)
theorem tabV_240 : tabV 240 = T240 := by decide +kernel
theorem bal_240_0 : (List.range' 0 70).all (balRow 240 T240) = true := by decide +kernel
theorem bal_240_1 : (List.range' 70 50).all (balRow 240 T240) = true := by decide +kernel
theorem small_240 : checkSmallFast 240 T240 = true := by decide +kernel
theorem checkN_240 : checkN 240 = true := by
  have h : (List.range' 0 70).all (balRow 240 T240) = true := bal_240_0
  have h : (List.range' 0 120).all (balRow 240 T240) = true := all_range'_append (by decide) (by decide) h bal_240_1
  exact checkN_of_parts tabV_240 (by decide +kernel) (by decide) h small_240

/-- The table value at n = 241. -/
def T241 : ℕ × ℕ := (216342587562221158401337814989117933277522860765923786126213659954889543249782063747112, 56134864059100620830085568688120055581047985920291182745328025600)
theorem tabV_241 : tabV 241 = T241 := by decide +kernel
theorem bal_241_0 : (List.range' 0 69).all (balRow 241 T241) = true := by decide +kernel
theorem bal_241_1 : (List.range' 69 52).all (balRow 241 T241) = true := by decide +kernel
theorem small_241 : checkSmallFast 241 T241 = true := by decide +kernel
theorem checkN_241 : checkN 241 = true := by
  have h : (List.range' 0 69).all (balRow 241 T241) = true := bal_241_0
  have h : (List.range' 0 121).all (balRow 241 T241) = true := all_range'_append (by decide) (by decide) h bal_241_1
  exact checkN_of_parts tabV_241 (by decide +kernel) (by decide) h small_241

/-- The table value at n = 242. -/
def T242 : ℕ × ℕ := (2309037706868608981899889773469064216871801931559513186115761985703538634572807190817638, 487281806068581778038937228195486593585485988891416516886528000000)
theorem tabV_242 : tabV 242 = T242 := by decide +kernel
theorem bal_242_0 : (List.range' 0 68).all (balRow 242 T242) = true := by decide +kernel
theorem bal_242_1 : (List.range' 68 53).all (balRow 242 T242) = true := by decide +kernel
theorem small_242 : checkSmallFast 242 T242 = true := by decide +kernel
theorem checkN_242 : checkN 242 = true := by
  have h : (List.range' 0 68).all (balRow 242 T242) = true := bal_242_0
  have h : (List.range' 0 121).all (balRow 242 T242) = true := all_range'_append (by decide) (by decide) h bal_242_1
  exact checkN_of_parts tabV_242 (by decide +kernel) (by decide) h small_242

/-- The table value at n = 243. -/
def T243 : ℕ × ℕ := (784843551890337558958650528314638711025928167290388764653589659537536803142042710351044, 134723673741841489992205364851488133394515166208698838588787261440)
theorem tabV_243 : tabV 243 = T243 := by decide +kernel
theorem bal_243_0 : (List.range' 0 68).all (balRow 243 T243) = true := by decide +kernel
theorem bal_243_1 : (List.range' 68 54).all (balRow 243 T243) = true := by decide +kernel
theorem small_243 : checkSmallFast 243 T243 = true := by decide +kernel
theorem checkN_243 : checkN 243 = true := by
  have h : (List.range' 0 68).all (balRow 243 T243) = true := bal_243_0
  have h : (List.range' 0 122).all (balRow 243 T243) = true := all_range'_append (by decide) (by decide) h bal_243_1
  exact checkN_of_parts tabV_243 (by decide +kernel) (by decide) h small_243

/-- The table value at n = 244. -/
def T244 : ℕ × ℕ := (8376652179841628262877002699644145127977365726857205256783471753904336381807958064189054, 1169476334564596267293449347669167824605166373339399640527667200000)
theorem tabV_244 : tabV 244 = T244 := by decide +kernel
theorem bal_244_0 : (List.range' 0 67).all (balRow 244 T244) = true := by decide +kernel
theorem bal_244_1 : (List.range' 67 55).all (balRow 244 T244) = true := by decide +kernel
theorem small_244 : checkSmallFast 244 T244 = true := by decide +kernel
theorem checkN_244 : checkN 244 = true := by
  have h : (List.range' 0 67).all (balRow 244 T244) = true := bal_244_0
  have h : (List.range' 0 122).all (balRow 244 T244) = true := all_range'_append (by decide) (by decide) h bal_244_1
  exact checkN_of_parts tabV_244 (by decide +kernel) (by decide) h small_244

/-- The table value at n = 245. -/
def T245 : ℕ × ℕ := (4046074327039468421038334071745209205327865212462250658947344949858462505541337904664208, 459478634656385713236574086440864791787609619490720249502811291648)
theorem tabV_245 : tabV 245 = T245 := by decide +kernel
theorem bal_245_0 : (List.range' 0 67).all (balRow 245 T245) = true := by decide +kernel
theorem bal_245_1 : (List.range' 67 56).all (balRow 245 T245) = true := by decide +kernel
theorem small_245 : checkSmallFast 245 T245 = true := by decide +kernel
theorem checkN_245 : checkN 245 = true := by
  have h : (List.range' 0 67).all (balRow 245 T245) = true := bal_245_0
  have h : (List.range' 0 123).all (balRow 245 T245) = true := all_range'_append (by decide) (by decide) h bal_245_1
  exact checkN_of_parts tabV_245 (by decide +kernel) (by decide) h small_245

end Sweep

theorem chunk_231_245 : (List.range' 231 15).all checkN = true := by
  have h : (List.range' 231 1).all checkN = true := all_range'_one Sweep.checkN_231
  have h : (List.range' 231 2).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_232
  have h : (List.range' 231 3).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_233
  have h : (List.range' 231 4).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_234
  have h : (List.range' 231 5).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_235
  have h : (List.range' 231 6).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_236
  have h : (List.range' 231 7).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_237
  have h : (List.range' 231 8).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_238
  have h : (List.range' 231 9).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_239
  have h : (List.range' 231 10).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_240
  have h : (List.range' 231 11).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_241
  have h : (List.range' 231 12).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_242
  have h : (List.range' 231 13).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_243
  have h : (List.range' 231 14).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_244
  have h : (List.range' 231 15).all checkN = true := all_range'_snoc (by decide) (by decide) h Sweep.checkN_245
  exact h

end BGSpiderTable
end R3Cert
