/- Generated by proof/verification/finite_cert/gen_mid_lean.py: root certificate, root degree k = 17. -/
import R3Cert.BGSpiderMidCellsD17
import R3Cert.BGSpiderMidSpiders

namespace R3Cert
namespace BGSCL

def WA_17 : ℕ → ℤ
  | 1 => -37119328720
  | 2 => -5233148855
  | 3 => 6829922355
  | 4 => 11204988941
  | 5 => 11804807070
  | 6 => 10272007369
  | 7 => 7416887943
  | 8 => 3685397893
  | 9 => -656775318
  | 10 => -5441499389
  | 11 => -10557169461
  | 12 => -15926793959
  | 13 => -21495526134
  | 14 => -27223212190
  | 15 => -33079825413
  | 16 => -39042303407
  | _ => 0

def tys_17 : List (ℕ × ℤ) := [(3, 7817308808), (1, -155832401862), (2, 10005594834), (3, -37119328720), (5, -5233148855), (7, 6829922355), (9, 11204988941), (11, 11804807070), (13, 10272007369), (15, 7416887943), (17, 3685397893), (19, -656775318), (21, -5441499389), (23, -10557169461), (25, -15926793959), (27, -21495526134), (29, -27223212190), (31, -33079825413), (33, -39042303407)]

theorem check_17 : (List.range' 149 342).all (fun N => decide
    ((11704754701 : ℤ) + 7817308808 + (dpRow tys_17 491 16).getD (N - 3) NEGI - 477000000 * (N : ℤ)
      < lowTabGet N)) = true := by decide +kernel

theorem midroot_17 (cs : List Branch) (hlen : cs.length = 17) (hcap : ∀ c ∈ cs, maxCh c + 1 ≤ 17)
    (hna : ∃ c ∈ cs, ¬ IsAtom c) (h1 : 149 ≤ bsizeList cs) (h2 : bsizeList cs ≤ 490) :
    phiRoot cs < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 := by
  have hσ : (1 / ((cs.length : ℝ) * (117/100 : ℝ))) = 1 / (((17:ℕ):ℝ) * (117/100 : ℝ)) := by rw [hlen]
  obtain ⟨ht, hn⟩ := htype_of (D := 17) (by norm_num) (by norm_num) rateCellKap_17
    (SC := 10 ^ 12) (σ := 1 / (((17:ℕ):ℝ) * (117/100 : ℝ))) (by norm_num) (by positivity)
    (tys := tys_17) (VNI := 7817308808) (WL := -155832401862) (WC := 10005594834) (WA := WA_17)
    (by unfold NbK; simp only [max_le_iff]; norm_num) (by norm_num) (by norm_num)
    (by intro j h1 h2; have h3 : j ≤ 16 := (by omega); interval_cases j <;> norm_num [bjT, WA_17])
    (by simp [tys_17]) (by simp [tys_17]) (by simp [tys_17])
    (by intro j h1 h2; have h3 : j ≤ 16 := (by omega); interval_cases j <;> simp [tys_17, WA_17])
  have hb := phiRoot_le_dp (D := 17) (tys := tys_17) (SC := 10 ^ 12) (α := (477/1000000 : ℝ)) (t := (117/100 : ℝ))
    (VNI := 7817308808) (by norm_num) (by norm_num) cs hcap (by rw [hσ]; exact ht) hna
    (by rw [hσ]; exact hn) 491 (by omega)
  rw [hlen] at hb
  have hlt := log_le_of_taylor (x := (117/100 : ℝ)) (c := (1570039/10000000 : ℝ)) (a := (1570039/10000000 : ℝ)) (by norm_num)
    (by rw [abs_le]; constructor <;> norm_num) (by norm_num) (by norm_num)
  have hc := check_17
  rw [List.all_eq_true] at hc
  have hN := hc (bsizeList cs) (List.mem_range'_1.mpr ⟨h1, by omega⟩)
  simp only [decide_eq_true_eq] at hN
  have hNR : (((11704754701 : ℤ) + 7817308808 + (dpRow tys_17 491 16).getD (bsizeList cs - 3) NEGI
      - 477000000 * (bsizeList cs : ℤ) : ℤ) : ℝ) < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) := by exact_mod_cast hN
  push_cast at hNR
  have hNn : (0:ℝ) ≤ (bsizeList cs : ℝ) := Nat.cast_nonneg _
  have hCI : Real.log (117/100 : ℝ) + 1 / (117/100 : ℝ) - 1 ≤ (11704754701 : ℝ) / 10 ^ 12 := by
    have : (1570039/10000000 : ℝ) + 1 / (117/100 : ℝ) - 1 ≤ (11704754701 : ℝ) / 10 ^ 12 := by norm_num
    linarith
  have hal : (477000000 : ℝ) / 10 ^ 12 ≤ (477/1000000 : ℝ) := by norm_num
  have hmul : (477/1000000 : ℝ) * (bsizeList cs : ℝ) ≥ (477000000 : ℝ) / 10 ^ 12 * (bsizeList cs : ℝ) :=
    mul_le_mul_of_nonneg_right hal hNn
  have hNR' : (((11704754701 : ℝ) + 7817308808 + (((dpRow tys_17 491 16).getD (bsizeList cs - 3) NEGI : ℤ) : ℝ)
      - 477000000 * (bsizeList cs : ℝ))) / 10 ^ 12 < ((lowTabGet (bsizeList cs) : ℤ) : ℝ) / 10 ^ 12 :=
    div_lt_div_of_pos_right (by linarith) (by norm_num)
  linarith

end BGSCL
end R3Cert
